import { useTranslation } from "react-i18next";

const zh = {
  center: "设置中心", scope: "编辑范围", global: "全局默认", project: "当前项目",
  globalImpact: "修改全局默认，影响继承这些选项的项目；项目覆盖值保持不变。",
  projectImpact: "仅修改当前项目；其他项目不变。留空的选项继续沿用配置。",
  saveGlobal: "保存全局默认", saveProject: "保存本项目",
  groups: { project: "项目", models: "模型与连接", agent: "Agent 与任务", workspace: "工作区", application: "应用与运维", diagnostics: "诊断" },
  resources: "任务与资源保护", connections: "电脑与命令环境", diagnostics: "运行状态与诊断",
  resourcesHint: "配置命令与后台任务的资源保护。修改仅影响后续启动的任务；实际启用情况请查看诊断。",
  projectGeneral: "项目与会话默认", extensions: "项目扩展", advanced: "高级选项",
  search: "搜索设置…", inherited: "沿用配置", overridden: "项目覆盖", restore: "恢复继承",
  inheritanceHint: "沿用值来自生效的全局/项目定义；每项覆盖独立保存。定义文件也可能影响最终值。",
  unsaved: "有未保存的改动", unsavedHint: "切换范围或页面会丢失当前草稿。继续编辑，或丢弃草稿后离开。",
  stay: "继续编辑", discard: "丢弃草稿并离开",
  extensionObjects: "扩展对象",
  extensionHint: "按扩展对象管理 .longx；测试产物不属于待共享扩展。",
  tabs: { overview: "概览", definition: "定义与覆盖", agents: "角色", plugs: "插件", watches: "定时任务", knowledge: "知识", artifacts: "本地产物" },
  allSources: "全部来源", local: "本机 local", shared: "共享 shared", source: "来源",
  findExtension: "搜索名称或路径…", noObjects: "没有匹配的扩展对象。",
  incomplete: "缺少 agent.exs", discovered: "文件已发现", untrusted: "共享代码未信任", loadedRole: "角色已加载",
  prepareShare: "准备共享", view: "查看", viewFiles: "查看文件", openDirectory: "打开 .longx 目录",
  shareHint: "核对文件与内容后，确认移动到 shared。不会提交 Git、自动启用信任或替换已有对象。",
  shareWarning: "角色整套移动；定时任务请审阅通知目标、会话绑定和本机路径。共享代码仍受项目的信任设置控制。",
  conflict: "目标已有共享对象，不能直接替换。请先在文件工作台审阅与合并，再重新预览。",
  confirmShare: "确认移动到 shared", shareSaved: "已准备共享文件；请在 Git 工作台审阅和提交。",
  noText: "二进制或大文件：内容请在文件工作台查看。", target: "目标", bytes: "字节",
  artifactHint: "按运行目录分组，截图、报告、数据库不会出现在提升列表。没有自动删除或保留期限。",
  artifactSafety: "目录是否仍被任务使用无法可靠确认，因此这里不提供一键删除；需要清理时请先检查关联任务，再在文件管理器处理。",
  definitionHint: "本机 agent.exs 是覆盖层；共享前需审阅并合并到 .longx/agent.exs，不移动到 shared/agent.exs。",
  trustScope: "此开关允许加载项目和 shared 的可执行代码；local 本机定义始终加载。",
  realStatus: "生效模型、插件与加载错误", machineScope: "全机任务报告；检测模式按所选范围解析。",
  filesEmpty: "目录为空。", previous: "上一页", next: "下一页", loading: "读取中…",
};

const en: typeof zh = {
  center: "Settings", scope: "Editing scope", global: "Global defaults", project: "Current project",
  globalImpact: "Changes affect projects inheriting these defaults; project overrides stay unchanged.",
  projectImpact: "Changes affect this project only. Empty options keep inherited configuration.",
  saveGlobal: "Save global defaults", saveProject: "Save this project",
  groups: { project: "Project", models: "Models & connections", agent: "Agent & tasks", workspace: "Workspace", application: "App & operations", diagnostics: "Diagnostics" },
  resources: "Tasks & resource protection", connections: "Computer & command environment", diagnostics: "Runtime & diagnostics",
  resourcesHint: "Configure resource protection for commands and background tasks. Changes affect new tasks only; check diagnostics for actual protection status.",
  projectGeneral: "Project & conversation defaults", extensions: "Project extensions", advanced: "Advanced options",
  search: "Search settings…", inherited: "Inherited configuration", overridden: "Project override", restore: "Restore inheritance",
  inheritanceHint: "Inherited values come from effective global/project definitions. Each override is independent; files may also affect the final value.",
  unsaved: "Unsaved changes", unsavedHint: "Changing scope or page discards the current draft. Keep editing or discard it before leaving.",
  stay: "Keep editing", discard: "Discard draft and leave",
  extensionObjects: "Extension objects",
  extensionHint: "Manage .longx as extension objects. Test outputs are not shareable extensions.",
  tabs: { overview: "Overview", definition: "Definitions & overrides", agents: "Roles", plugs: "Plugs", watches: "Watches", knowledge: "Knowledge", artifacts: "Local outputs" },
  allSources: "All sources", local: "Local", shared: "Shared", source: "Source",
  findExtension: "Search names or paths…", noObjects: "No matching extension objects.",
  incomplete: "Missing agent.exs", discovered: "File discovered", untrusted: "Shared code is not trusted", loadedRole: "Role loaded",
  prepareShare: "Prepare sharing", view: "View", viewFiles: "View files", openDirectory: "Open .longx directory",
  shareHint: "Review files and contents before moving to shared. No Git commit, automatic trust or replacement of existing objects.",
  shareWarning: "Roles move as a whole. Review watch recipients, session bindings and machine-specific paths. Shared code remains subject to project trust.",
  conflict: "A shared object already exists. Review and merge in the workbench, then preview again.",
  confirmShare: "Confirm move to shared", shareSaved: "Shared files prepared. Review and commit in the Git workbench.",
  noText: "Binary or large file: inspect contents in the file workbench.", target: "Target", bytes: "bytes",
  artifactHint: "Grouped by run directory. Screenshots, reports and databases are not sharing candidates. Nothing is automatically deleted.",
  artifactSafety: "We cannot reliably confirm whether a task still uses this directory, so there is no one-click deletion. Inspect related tasks before cleaning it in file management.",
  definitionHint: "Local agent.exs is an override layer. Review and merge it into .longx/agent.exs; do not move it to shared/agent.exs.",
  trustScope: "This switch permits executable project/shared definitions. Local definitions always load.",
  realStatus: "Effective model, plugs and loading errors", machineScope: "Machine-wide task reports; detection mode follows the selected scope.",
  filesEmpty: "Empty directory.", previous: "Previous", next: "Next", loading: "Loading…",
};

export function useSettingsCopy() {
  const { i18n } = useTranslation();
  return i18n.resolvedLanguage === "en" ? en : zh;
}
