// Generated by AshTypescript - RPC Actions
// Do not edit this file manually

import * as RpcHooks from "./core/rpcHooks";

import type { AshRpcError, ConditionalPaginatedResultMixed, InferResult, ModelFilterInput, ModelResourceSchema, ModelSortField, ProjectFilterInput, ProjectResourceSchema, ProjectSortField, ProviderFilterInput, ProviderResourceSchema, ProviderSortField, SortString, ThreadFilterInput, ThreadResourceSchema, ThreadSortField, ToolResourceSchema, TurnFilterInput, TurnResourceSchema, TurnSortField, UUID, UUIDv7, UnifiedFieldSelection, UtcDateTimeUsec, ValidationResult } from "./ash_types";
export type * from "./ash_types";

// RPC Action Hook Context Type
export type ActionHookContext = RpcHooks.ActionHookContext;

// RPC Validation Hook Context Type
export type ValidationHookContext = RpcHooks.ValidationHookContext;

// Helper Functions

/**
 * Configuration options for action RPC requests
 */
export interface ActionConfig {
  // Request data
  input?: Record<string, any> | undefined;
  identity?: any;
  fields?: Array<string | Record<string, any>> | undefined; // Field selection
  filter?: Record<string, any> | undefined; // Filter options (for reads)
  sort?: string | string[] | undefined; // Sort options
  page?:
    | {
        // Offset-based pagination
        limit?: number;
        offset?: number;
        count?: boolean;
      }
    | {
        // Keyset pagination
        limit?: number;
        after?: string;
        before?: string;
      }
    | undefined;

  // Metadata
  metadataFields?: ReadonlyArray<string> | undefined;

  // HTTP customization
  headers?: Record<string, string> | undefined; // Custom headers
  fetchOptions?: RequestInit | undefined; // Fetch options (signal, cache, etc.)
  customFetch?: ((
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>) | undefined;

  // Multitenancy
  tenant?: string | undefined; // Tenant parameter

  // Hook context
  hookCtx?: RpcHooks.ActionHookContext | undefined;
}

/**
 * Configuration options for validation RPC requests
 */
export interface ValidationConfig {
  // Request data
  input?: Record<string, any> | undefined;

  // HTTP customization
  headers?: Record<string, string> | undefined;
  fetchOptions?: RequestInit | undefined;
  customFetch?: ((
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>) | undefined;

  // Hook context
  hookCtx?: RpcHooks.ValidationHookContext | undefined;
}




/**
 * Gets the CSRF token from the page's meta tag
 * Returns null if no CSRF token is found
 */
export function getPhoenixCSRFToken(): string | null {
  return document
    ?.querySelector("meta[name='csrf-token']")
    ?.getAttribute("content") || null;
}

/**
 * Builds headers object with CSRF token for Phoenix applications
 * Returns headers object with X-CSRF-Token (if available)
 */
export function buildCSRFHeaders(headers: Record<string, string> = {}): Record<string, string> {
  const csrfToken = getPhoenixCSRFToken();
  if (csrfToken) {
    headers["X-CSRF-Token"] = csrfToken;
  }

  return headers;
}

/**
 * Internal helper function for making action RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ActionConfig
 */
export async function executeActionRpcRequest<T>(
  payload: Record<string, any>,
  config: ActionConfig
): Promise<T> {
    let processedConfig = config;
    if (RpcHooks.beforeRequest) {
      processedConfig = await RpcHooks.beforeRequest(payload.action, config);
    }

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/run", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}


/**
 * Internal helper function for making validation RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ValidationConfig
 */
export async function executeValidationRpcRequest<T>(
  payload: Record<string, any>,
  config: ValidationConfig
): Promise<T> {
    let processedConfig = config;
    if (RpcHooks.beforeValidationRequest) {
      processedConfig = await RpcHooks.beforeValidationRequest(payload.action, config);
    }

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/validate", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}







export type CheckModelInput = {
  id: UUID;
};

export type CheckModelFields = UnifiedFieldSelection<{ok: boolean, latencyMs: number | null, error: string | null, __type: "TypedMap", __primitiveFields: "ok" | "latencyMs" | "error"}>[];

export type InferCheckModelResult<
  Fields extends CheckModelFields | undefined,
> = InferResult<{ok: boolean, latencyMs: number | null, error: string | null, __type: "TypedMap", __primitiveFields: "ok" | "latencyMs" | "error"}, Fields>;

export type CheckModelResult<Fields extends CheckModelFields | undefined = undefined> = | { success: true; data: InferCheckModelResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Model
 *
 * @ashActionType :action
 */
export async function checkModel<Fields extends CheckModelFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CheckModelInput;
  hookCtx?: ActionHookContext;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CheckModelResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "check_model",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CheckModelResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Model
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateCheckModel(
  config: {
  tenant?: string;
  input: CheckModelInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "check_model",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type CreateModelInput = {
  name: string;
  slug?: string | null;
  upstreamId: string;
  contextWindow?: number;
  providerId: UUID;
  reasoningEffort?: string | null;
  reasoningSummary?: "auto" | "concise" | "detailed" | "none" | null;
  maxOutputTokens?: number | null;
};

export type CreateModelFields = UnifiedFieldSelection<ModelResourceSchema>[];

export type InferCreateModelResult<
  Fields extends CreateModelFields | undefined,
> = InferResult<ModelResourceSchema, Fields>;

export type CreateModelResult<Fields extends CreateModelFields | undefined = undefined> = | { success: true; data: InferCreateModelResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Model
 *
 * @ashActionType :create
 */
export async function createModel<Fields extends CreateModelFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CreateModelInput;
  hookCtx?: ActionHookContext;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateModelResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_model",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateModelResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Model
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateCreateModel(
  config: {
  tenant?: string;
  input: CreateModelInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "create_model",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type MakeDefaultModelFields = UnifiedFieldSelection<ModelResourceSchema>[];

export type InferMakeDefaultModelResult<
  Fields extends MakeDefaultModelFields | undefined,
> = InferResult<ModelResourceSchema, Fields>;

export type MakeDefaultModelResult<Fields extends MakeDefaultModelFields | undefined = undefined> = | { success: true; data: InferMakeDefaultModelResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Model
 *
 * @ashActionType :update
 */
export async function makeDefaultModel<Fields extends MakeDefaultModelFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUIDv7;
  hookCtx?: ActionHookContext;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<MakeDefaultModelResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "make_default_model",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<MakeDefaultModelResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Model
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateMakeDefaultModel(
  config: {
  tenant?: string;
  identity: UUIDv7 | string;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "make_default_model",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListModelsFields = UnifiedFieldSelection<ModelResourceSchema>[];


export type InferListModelsResult<
  Fields extends ListModelsFields | undefined,
  Page extends ListModelsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<ModelResourceSchema, Fields>>, {
  results: Array<InferResult<ModelResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<ModelResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string | null;
  nextPage: string | null;
  count?: number | null;
  type: "keyset";
}>;

export type ListModelsConfig = {
  tenant?: string;
  hookCtx?: ActionHookContext;
  fields: ListModelsFields;
  filter?: ModelFilterInput;
  sort?: SortString<ModelSortField> | SortString<ModelSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListModelsResult<Fields extends ListModelsFields, Page extends ListModelsConfig["page"] = undefined> = | { success: true; data: InferListModelsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Model records
 *
 * @ashActionType :read
 */
export async function listModels<Fields extends ListModelsFields, Config extends ListModelsConfig = ListModelsConfig>(
  config: Config & { fields: Fields }
): Promise<ListModelsResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_models",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListModelsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Model records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListModels(
  config: {
  tenant?: string;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_models",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type UpdateModelInput = {
  name?: string;
  slug?: string | null;
  upstreamId?: string;
  contextWindow?: number;
  reasoningEffort?: string | null;
  reasoningSummary?: "auto" | "concise" | "detailed" | "none" | null;
  maxOutputTokens?: number | null;
};

export type UpdateModelFields = UnifiedFieldSelection<ModelResourceSchema>[];

export type InferUpdateModelResult<
  Fields extends UpdateModelFields | undefined,
> = InferResult<ModelResourceSchema, Fields>;

export type UpdateModelResult<Fields extends UpdateModelFields | undefined = undefined> = | { success: true; data: InferUpdateModelResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Model
 *
 * @ashActionType :update
 */
export async function updateModel<Fields extends UpdateModelFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUIDv7;
  input?: UpdateModelInput;
  hookCtx?: ActionHookContext;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<UpdateModelResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "update_model",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<UpdateModelResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Model
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateUpdateModel(
  config: {
  tenant?: string;
  identity: UUIDv7 | string;
  input?: UpdateModelInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "update_model",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type CreateProviderInput = {
  name: string;
  slug: string;
  kind?: "openai" | "openai_compatible";
  baseUrl: string;
  supportsHostedWebSearch?: boolean;
  requestTimeoutMs?: number;
  maxConcurrentRequests?: number | null;
  apiKey?: string | null;
};

export type CreateProviderFields = UnifiedFieldSelection<ProviderResourceSchema>[];

export type InferCreateProviderResult<
  Fields extends CreateProviderFields | undefined,
> = InferResult<ProviderResourceSchema, Fields>;

export type CreateProviderResult<Fields extends CreateProviderFields | undefined = undefined> = | { success: true; data: InferCreateProviderResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Provider
 *
 * @ashActionType :create
 */
export async function createProvider<Fields extends CreateProviderFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CreateProviderInput;
  hookCtx?: ActionHookContext;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateProviderResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_provider",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateProviderResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Provider
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateCreateProvider(
  config: {
  tenant?: string;
  input: CreateProviderInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "create_provider",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListProvidersFields = UnifiedFieldSelection<ProviderResourceSchema>[];


export type InferListProvidersResult<
  Fields extends ListProvidersFields | undefined,
  Page extends ListProvidersConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<ProviderResourceSchema, Fields>>, {
  results: Array<InferResult<ProviderResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<ProviderResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string | null;
  nextPage: string | null;
  count?: number | null;
  type: "keyset";
}>;

export type ListProvidersConfig = {
  tenant?: string;
  hookCtx?: ActionHookContext;
  fields: ListProvidersFields;
  filter?: ProviderFilterInput;
  sort?: SortString<ProviderSortField> | SortString<ProviderSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListProvidersResult<Fields extends ListProvidersFields, Page extends ListProvidersConfig["page"] = undefined> = | { success: true; data: InferListProvidersResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Provider records
 *
 * @ashActionType :read
 */
export async function listProviders<Fields extends ListProvidersFields, Config extends ListProvidersConfig = ListProvidersConfig>(
  config: Config & { fields: Fields }
): Promise<ListProvidersResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_providers",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListProvidersResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Provider records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListProviders(
  config: {
  tenant?: string;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_providers",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type UpdateProviderInput = {
  name?: string;
  kind?: "openai" | "openai_compatible";
  baseUrl?: string;
  supportsHostedWebSearch?: boolean;
  requestTimeoutMs?: number;
  maxConcurrentRequests?: number | null;
  apiKey?: string | null;
};

export type UpdateProviderFields = UnifiedFieldSelection<ProviderResourceSchema>[];

export type InferUpdateProviderResult<
  Fields extends UpdateProviderFields | undefined,
> = InferResult<ProviderResourceSchema, Fields>;

export type UpdateProviderResult<Fields extends UpdateProviderFields | undefined = undefined> = | { success: true; data: InferUpdateProviderResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Provider
 *
 * @ashActionType :update
 */
export async function updateProvider<Fields extends UpdateProviderFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUIDv7;
  input?: UpdateProviderInput;
  hookCtx?: ActionHookContext;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<UpdateProviderResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "update_provider",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<UpdateProviderResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Provider
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateUpdateProvider(
  config: {
  tenant?: string;
  identity: UUIDv7 | string;
  input?: UpdateProviderInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "update_provider",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListToolsFields = UnifiedFieldSelection<{id: UUID, namespace: string, name: string, qualifiedName: string, description: string, inputSchema: Record<string, any>, enabled: boolean, __type: "TypedMap", __primitiveFields: "id" | "namespace" | "name" | "qualifiedName" | "description" | "inputSchema" | "enabled"}>[];

export type InferListToolsResult<
  Fields extends ListToolsFields | undefined,
> = Array<InferResult<{id: UUID, namespace: string, name: string, qualifiedName: string, description: string, inputSchema: Record<string, any>, enabled: boolean, __type: "TypedMap", __primitiveFields: "id" | "namespace" | "name" | "qualifiedName" | "description" | "inputSchema" | "enabled"}, Fields>>;

export type ListToolsResult<Fields extends ListToolsFields | undefined = undefined> = | { success: true; data: InferListToolsResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Tool
 *
 * @ashActionType :action
 */
export async function listTools<Fields extends ListToolsFields | undefined = undefined>(
  config: {
  tenant?: string;
  hookCtx?: ActionHookContext;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListToolsResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "list_tools",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<ListToolsResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Tool
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateListTools(
  config: {
  tenant?: string;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_tools",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type SetToolEnabledInput = {
  enabled?: boolean;
};

export type SetToolEnabledFields = UnifiedFieldSelection<ToolResourceSchema>[];

export type InferSetToolEnabledResult<
  Fields extends SetToolEnabledFields | undefined,
> = InferResult<ToolResourceSchema, Fields>;

export type SetToolEnabledResult<Fields extends SetToolEnabledFields | undefined = undefined> = | { success: true; data: InferSetToolEnabledResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Tool
 *
 * @ashActionType :update
 */
export async function setToolEnabled<Fields extends SetToolEnabledFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUIDv7;
  input?: SetToolEnabledInput;
  hookCtx?: ActionHookContext;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<SetToolEnabledResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "set_tool_enabled",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<SetToolEnabledResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Tool
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateSetToolEnabled(
  config: {
  tenant?: string;
  identity: UUIDv7 | string;
  input?: SetToolEnabledInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "set_tool_enabled",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListProjectsFields = UnifiedFieldSelection<ProjectResourceSchema>[];
export type InferListProjectsResult<
  Fields extends ListProjectsFields,
> = Array<InferResult<ProjectResourceSchema, Fields>>;

export type ListProjectsResult<Fields extends ListProjectsFields> = | { success: true; data: InferListProjectsResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Project records
 *
 * @ashActionType :read
 */
export async function listProjects<Fields extends ListProjectsFields>(
  config: {
  tenant?: string;
  hookCtx?: ActionHookContext;
  fields: Fields;
  filter?: ProjectFilterInput;
  sort?: SortString<ProjectSortField> | SortString<ProjectSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListProjectsResult<Fields>> {
  const payload = {
    action: "list_projects",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<ListProjectsResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Project records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListProjects(
  config: {
  tenant?: string;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_projects",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ArchiveProjectFields = UnifiedFieldSelection<ProjectResourceSchema>[];

export type InferArchiveProjectResult<
  Fields extends ArchiveProjectFields | undefined,
> = InferResult<ProjectResourceSchema, Fields>;

export type ArchiveProjectResult<Fields extends ArchiveProjectFields | undefined = undefined> = | { success: true; data: InferArchiveProjectResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Project
 *
 * @ashActionType :update
 */
export async function archiveProject<Fields extends ArchiveProjectFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUIDv7;
  hookCtx?: ActionHookContext;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ArchiveProjectResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "archive_project",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<ArchiveProjectResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Project
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateArchiveProject(
  config: {
  tenant?: string;
  identity: UUIDv7 | string;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "archive_project",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetProjectInput = {
  slug: string;
};

export type GetProjectFields = UnifiedFieldSelection<ProjectResourceSchema>[];
export type InferGetProjectResult<
  Fields extends GetProjectFields,
> = InferResult<ProjectResourceSchema, Fields>;

export type GetProjectResult<Fields extends GetProjectFields> = | { success: true; data: InferGetProjectResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Project records
 *
 * @ashActionType :read
 */
export async function getProject<Fields extends GetProjectFields>(
  config: {
  tenant?: string;
  input: GetProjectInput;
  hookCtx?: ActionHookContext;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetProjectResult<Fields>> {
  const payload = {
    action: "get_project",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GetProjectResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Project records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetProject(
  config: {
  tenant?: string;
  input: GetProjectInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_project",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ClearCodexHistoryInput = {
  id: UUID;
};

export type InferClearCodexHistoryResult = {};

export type ClearCodexHistoryResult = | { success: true; data: InferClearCodexHistoryResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Project
 *
 * @ashActionType :action
 */
export async function clearCodexHistory(
  config: {
  tenant?: string;
  input: ClearCodexHistoryInput;
  hookCtx?: ActionHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ClearCodexHistoryResult> {
  const payload = {
    action: "clear_codex_history",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<ClearCodexHistoryResult>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Project
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateClearCodexHistory(
  config: {
  tenant?: string;
  input: ClearCodexHistoryInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "clear_codex_history",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type CodexInfoInput = {
  id: UUID;
};

export type CodexInfoFields = UnifiedFieldSelection<{home: string, exists: boolean, bytes: number, files: Record<string, any>, worker: Record<string, any> | null, __type: "TypedMap", __primitiveFields: "home" | "exists" | "bytes" | "files" | "worker"}>[];

export type InferCodexInfoResult<
  Fields extends CodexInfoFields | undefined,
> = InferResult<{home: string, exists: boolean, bytes: number, files: Record<string, any>, worker: Record<string, any> | null, __type: "TypedMap", __primitiveFields: "home" | "exists" | "bytes" | "files" | "worker"}, Fields>;

export type CodexInfoResult<Fields extends CodexInfoFields | undefined = undefined> = | { success: true; data: InferCodexInfoResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Project
 *
 * @ashActionType :action
 */
export async function codexInfo<Fields extends CodexInfoFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CodexInfoInput;
  hookCtx?: ActionHookContext;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CodexInfoResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "codex_info",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CodexInfoResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Project
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateCodexInfo(
  config: {
  tenant?: string;
  input: CodexInfoInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "codex_info",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type CreateProjectInput = {
  name: string;
  description?: string | null;
  rootPath: string;
  approvalPolicy?: "never" | "on_request" | "untrusted";
  sandbox?: "danger_full_access" | "read_only" | "workspace_write";
  tools?: Array<string>;
  dirtyStart?: "ask" | "commit" | "off";
  networkAccess?: boolean;
  webSearch?: boolean;
  memoryLimitMb?: number | null;
  modelId?: UUID | null;
  initGit?: boolean | null;
};

export type CreateProjectFields = UnifiedFieldSelection<ProjectResourceSchema>[];

export type InferCreateProjectResult<
  Fields extends CreateProjectFields | undefined,
> = InferResult<ProjectResourceSchema, Fields>;

export type CreateProjectResult<Fields extends CreateProjectFields | undefined = undefined> = | { success: true; data: InferCreateProjectResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Project
 *
 * @ashActionType :create
 */
export async function createProject<Fields extends CreateProjectFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CreateProjectInput;
  hookCtx?: ActionHookContext;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateProjectResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_project",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateProjectResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Project
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateCreateProject(
  config: {
  tenant?: string;
  input: CreateProjectInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "create_project",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type DeleteProjectInput = {
  confirm?: boolean | null;
};

export type DeleteProjectResult = | { success: true; data: {}; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Delete a Project
 *
 * @ashActionType :destroy
 */
export async function deleteProject(
  config: {
  tenant?: string;
  identity: UUIDv7;
  input?: DeleteProjectInput;
  hookCtx?: ActionHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<DeleteProjectResult> {
  const payload = {
    action: "delete_project",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeActionRpcRequest<DeleteProjectResult>(
    payload,
    config
  );
}


/**
 * Validate: Delete a Project
 *
 * @ashActionType :destroy
 * @validation true
 */
export async function validateDeleteProject(
  config: {
  tenant?: string;
  identity: UUIDv7 | string;
  input?: DeleteProjectInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "delete_project",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GitInfoInput = {
  id: UUID;
};

export type GitInfoFields = UnifiedFieldSelection<{repository: boolean, head: string | null, clean: boolean | null, changes: number, lfs: boolean, __type: "TypedMap", __primitiveFields: "repository" | "head" | "clean" | "changes" | "lfs"}>[];

export type InferGitInfoResult<
  Fields extends GitInfoFields | undefined,
> = InferResult<{repository: boolean, head: string | null, clean: boolean | null, changes: number, lfs: boolean, __type: "TypedMap", __primitiveFields: "repository" | "head" | "clean" | "changes" | "lfs"}, Fields>;

export type GitInfoResult<Fields extends GitInfoFields | undefined = undefined> = | { success: true; data: InferGitInfoResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Project
 *
 * @ashActionType :action
 */
export async function gitInfo<Fields extends GitInfoFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: GitInfoInput;
  hookCtx?: ActionHookContext;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GitInfoResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "git_info",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GitInfoResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Project
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateGitInfo(
  config: {
  tenant?: string;
  input: GitInfoInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "git_info",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type InitGitInput = {
  id: UUID;
};

export type InitGitFields = UnifiedFieldSelection<{repository: boolean, head: string | null, clean: boolean | null, changes: number, lfs: boolean, __type: "TypedMap", __primitiveFields: "repository" | "head" | "clean" | "changes" | "lfs"}>[];

export type InferInitGitResult<
  Fields extends InitGitFields | undefined,
> = InferResult<{repository: boolean, head: string | null, clean: boolean | null, changes: number, lfs: boolean, __type: "TypedMap", __primitiveFields: "repository" | "head" | "clean" | "changes" | "lfs"}, Fields>;

export type InitGitResult<Fields extends InitGitFields | undefined = undefined> = | { success: true; data: InferInitGitResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Project
 *
 * @ashActionType :action
 */
export async function initGit<Fields extends InitGitFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: InitGitInput;
  hookCtx?: ActionHookContext;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<InitGitResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "init_git",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<InitGitResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Project
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateInitGit(
  config: {
  tenant?: string;
  input: InitGitInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "init_git",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListAllProjectsFields = UnifiedFieldSelection<ProjectResourceSchema>[];


export type InferListAllProjectsResult<
  Fields extends ListAllProjectsFields | undefined,
  Page extends ListAllProjectsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<ProjectResourceSchema, Fields>>, {
  results: Array<InferResult<ProjectResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<ProjectResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string | null;
  nextPage: string | null;
  count?: number | null;
  type: "keyset";
}>;

export type ListAllProjectsConfig = {
  tenant?: string;
  hookCtx?: ActionHookContext;
  fields: ListAllProjectsFields;
  filter?: ProjectFilterInput;
  sort?: SortString<ProjectSortField> | SortString<ProjectSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListAllProjectsResult<Fields extends ListAllProjectsFields, Page extends ListAllProjectsConfig["page"] = undefined> = | { success: true; data: InferListAllProjectsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Project records
 *
 * @ashActionType :read
 */
export async function listAllProjects<Fields extends ListAllProjectsFields, Config extends ListAllProjectsConfig = ListAllProjectsConfig>(
  config: Config & { fields: Fields }
): Promise<ListAllProjectsResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_all_projects",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListAllProjectsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Project records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListAllProjects(
  config: {
  tenant?: string;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_all_projects",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type RestartCodexInput = {
  id: UUID;
};

export type InferRestartCodexResult = {};

export type RestartCodexResult = | { success: true; data: InferRestartCodexResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Project
 *
 * @ashActionType :action
 */
export async function restartCodex(
  config: {
  tenant?: string;
  input: RestartCodexInput;
  hookCtx?: ActionHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<RestartCodexResult> {
  const payload = {
    action: "restart_codex",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<RestartCodexResult>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Project
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateRestartCodex(
  config: {
  tenant?: string;
  input: RestartCodexInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "restart_codex",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type StopCodexInput = {
  id: UUID;
  force?: boolean | null;
};

export type InferStopCodexResult = {};

export type StopCodexResult = | { success: true; data: InferStopCodexResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Project
 *
 * @ashActionType :action
 */
export async function stopCodex(
  config: {
  tenant?: string;
  input: StopCodexInput;
  hookCtx?: ActionHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<StopCodexResult> {
  const payload = {
    action: "stop_codex",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<StopCodexResult>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Project
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateStopCodex(
  config: {
  tenant?: string;
  input: StopCodexInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "stop_codex",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type UpdateProjectInput = {
  name?: string;
  slug?: string;
  description?: string | null;
  approvalPolicy?: "never" | "on_request" | "untrusted";
  sandbox?: "danger_full_access" | "read_only" | "workspace_write";
  tools?: Array<string>;
  dirtyStart?: "ask" | "commit" | "off";
  networkAccess?: boolean;
  webSearch?: boolean;
  memoryLimitMb?: number | null;
  modelId?: UUID | null;
};

export type UpdateProjectFields = UnifiedFieldSelection<ProjectResourceSchema>[];

export type InferUpdateProjectResult<
  Fields extends UpdateProjectFields | undefined,
> = InferResult<ProjectResourceSchema, Fields>;

export type UpdateProjectResult<Fields extends UpdateProjectFields | undefined = undefined> = | { success: true; data: InferUpdateProjectResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Project
 *
 * @ashActionType :update
 */
export async function updateProject<Fields extends UpdateProjectFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUIDv7;
  input?: UpdateProjectInput;
  hookCtx?: ActionHookContext;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<UpdateProjectResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "update_project",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<UpdateProjectResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Project
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateUpdateProject(
  config: {
  tenant?: string;
  identity: UUIDv7 | string;
  input?: UpdateProjectInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "update_project",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type AnswerRequestInput = {
  threadId: UUID;
  requestId: string;
  answers: Record<string, any>;
};

export type InferAnswerRequestResult = {};

export type AnswerRequestResult = | { success: true; data: InferAnswerRequestResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Thread
 *
 * @ashActionType :action
 */
export async function answerRequest(
  config: {
  tenant?: string;
  input: AnswerRequestInput;
  hookCtx?: ActionHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<AnswerRequestResult> {
  const payload = {
    action: "answer_request",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<AnswerRequestResult>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Thread
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateAnswerRequest(
  config: {
  tenant?: string;
  input: AnswerRequestInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "answer_request",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ArchiveThreadFields = UnifiedFieldSelection<ThreadResourceSchema>[];

export type InferArchiveThreadResult<
  Fields extends ArchiveThreadFields | undefined,
> = InferResult<ThreadResourceSchema, Fields>;

export type ArchiveThreadResult<Fields extends ArchiveThreadFields | undefined = undefined> = | { success: true; data: InferArchiveThreadResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Thread
 *
 * @ashActionType :update
 */
export async function archiveThread<Fields extends ArchiveThreadFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUIDv7;
  hookCtx?: ActionHookContext;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ArchiveThreadResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "archive_thread",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<ArchiveThreadResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Thread
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateArchiveThread(
  config: {
  tenant?: string;
  identity: UUIDv7 | string;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "archive_thread",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type DeleteThreadInput = {
  threadId: UUID;
};

export type InferDeleteThreadResult = {};

export type DeleteThreadResult = | { success: true; data: InferDeleteThreadResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Thread
 *
 * @ashActionType :action
 */
export async function deleteThread(
  config: {
  tenant?: string;
  input: DeleteThreadInput;
  hookCtx?: ActionHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<DeleteThreadResult> {
  const payload = {
    action: "delete_thread",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<DeleteThreadResult>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Thread
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateDeleteThread(
  config: {
  tenant?: string;
  input: DeleteThreadInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "delete_thread",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListThreadsInput = {
  projectId: UUID;
};

export type ListThreadsFields = UnifiedFieldSelection<ThreadResourceSchema>[];
export type InferListThreadsResult<
  Fields extends ListThreadsFields,
> = Array<InferResult<ThreadResourceSchema, Fields>>;

export type ListThreadsResult<Fields extends ListThreadsFields> = | { success: true; data: InferListThreadsResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Thread records
 *
 * @ashActionType :read
 */
export async function listThreads<Fields extends ListThreadsFields>(
  config: {
  tenant?: string;
  input: ListThreadsInput;
  hookCtx?: ActionHookContext;
  fields: Fields;
  filter?: ThreadFilterInput;
  sort?: SortString<ThreadSortField> | SortString<ThreadSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListThreadsResult<Fields>> {
  const payload = {
    action: "list_threads",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<ListThreadsResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Thread records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListThreads(
  config: {
  tenant?: string;
  input: ListThreadsInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_threads",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type InterruptTurnInput = {
  threadId: UUID;
  codexTurnId: string;
};

export type InferInterruptTurnResult = {};

export type InterruptTurnResult = | { success: true; data: InferInterruptTurnResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Thread
 *
 * @ashActionType :action
 */
export async function interruptTurn(
  config: {
  tenant?: string;
  input: InterruptTurnInput;
  hookCtx?: ActionHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<InterruptTurnResult> {
  const payload = {
    action: "interrupt_turn",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<InterruptTurnResult>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Thread
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateInterruptTurn(
  config: {
  tenant?: string;
  input: InterruptTurnInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "interrupt_turn",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type RenameThreadInput = {
  title?: string | null;
};

export type RenameThreadFields = UnifiedFieldSelection<ThreadResourceSchema>[];

export type InferRenameThreadResult<
  Fields extends RenameThreadFields | undefined,
> = InferResult<ThreadResourceSchema, Fields>;

export type RenameThreadResult<Fields extends RenameThreadFields | undefined = undefined> = | { success: true; data: InferRenameThreadResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Thread
 *
 * @ashActionType :update
 */
export async function renameThread<Fields extends RenameThreadFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUIDv7;
  input?: RenameThreadInput;
  hookCtx?: ActionHookContext;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<RenameThreadResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "rename_thread",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<RenameThreadResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Thread
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateRenameThread(
  config: {
  tenant?: string;
  identity: UUIDv7 | string;
  input?: RenameThreadInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "rename_thread",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type RespondInput = {
  threadId: UUID;
  requestId: string;
  decision: "accept" | "accept_for_session" | "cancel" | "decline";
};

export type InferRespondResult = {};

export type RespondResult = | { success: true; data: InferRespondResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Thread
 *
 * @ashActionType :action
 */
export async function respond(
  config: {
  tenant?: string;
  input: RespondInput;
  hookCtx?: ActionHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<RespondResult> {
  const payload = {
    action: "respond",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<RespondResult>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Thread
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateRespond(
  config: {
  tenant?: string;
  input: RespondInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "respond",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type SendMessageInput = {
  threadId: UUID;
  text: string;
  model?: string | null;
  dirty?: "commit" | "ignore" | null;
  sandbox?: "danger_full_access" | "read_only" | "workspace_write" | null;
  approvalPolicy?: "never" | "on_request" | "untrusted" | null;
  networkAccess?: boolean | null;
};

export type SendMessageFields = UnifiedFieldSelection<TurnResourceSchema>[];

export type InferSendMessageResult<
  Fields extends SendMessageFields | undefined,
> = InferResult<TurnResourceSchema, Fields>;

export type SendMessageResult<Fields extends SendMessageFields | undefined = undefined> = | { success: true; data: InferSendMessageResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Thread
 *
 * @ashActionType :action
 */
export async function sendMessage<Fields extends SendMessageFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: SendMessageInput;
  hookCtx?: ActionHookContext;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<SendMessageResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "send_message",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<SendMessageResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Thread
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateSendMessage(
  config: {
  tenant?: string;
  input: SendMessageInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "send_message",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type StartThreadInput = {
  projectId: UUID;
  model?: string | null;
  tools?: Array<string> | null;
  approvalPolicy?: "never" | "on_request" | "untrusted" | null;
  sandbox?: "danger_full_access" | "read_only" | "workspace_write" | null;
  networkAccess?: boolean | null;
  webSearch?: boolean | null;
};

export type StartThreadFields = UnifiedFieldSelection<ThreadResourceSchema>[];

export type InferStartThreadResult<
  Fields extends StartThreadFields | undefined,
> = InferResult<ThreadResourceSchema, Fields>;

export type StartThreadResult<Fields extends StartThreadFields | undefined = undefined> = | { success: true; data: InferStartThreadResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Thread
 *
 * @ashActionType :action
 */
export async function startThread<Fields extends StartThreadFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: StartThreadInput;
  hookCtx?: ActionHookContext;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<StartThreadResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "start_thread",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<StartThreadResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Thread
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateStartThread(
  config: {
  tenant?: string;
  input: StartThreadInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "start_thread",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListTurnsInput = {
  threadId: UUID;
  includeReverted?: boolean | null;
};

export type ListTurnsFields = UnifiedFieldSelection<TurnResourceSchema>[];
export type InferListTurnsResult<
  Fields extends ListTurnsFields,
> = Array<InferResult<TurnResourceSchema, Fields>>;

export type ListTurnsResult<Fields extends ListTurnsFields> = | { success: true; data: InferListTurnsResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Turn records
 *
 * @ashActionType :read
 */
export async function listTurns<Fields extends ListTurnsFields>(
  config: {
  tenant?: string;
  input: ListTurnsInput;
  hookCtx?: ActionHookContext;
  fields: Fields;
  filter?: TurnFilterInput;
  sort?: SortString<TurnSortField> | SortString<TurnSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListTurnsResult<Fields>> {
  const payload = {
    action: "list_turns",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<ListTurnsResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Turn records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListTurns(
  config: {
  tenant?: string;
  input: ListTurnsInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_turns",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type RedoTurnInput = {
  turnId: UUID;
  text?: string | null;
  model?: string | null;
  mode?: "fork" | "revert" | null;
  restoreFiles?: boolean | null;
};

export type RedoTurnFields = UnifiedFieldSelection<TurnResourceSchema>[];

export type InferRedoTurnResult<
  Fields extends RedoTurnFields | undefined,
> = InferResult<TurnResourceSchema, Fields>;

export type RedoTurnResult<Fields extends RedoTurnFields | undefined = undefined> = | { success: true; data: InferRedoTurnResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Turn
 *
 * @ashActionType :action
 */
export async function redoTurn<Fields extends RedoTurnFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: RedoTurnInput;
  hookCtx?: ActionHookContext;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<RedoTurnResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "redo_turn",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<RedoTurnResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Turn
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateRedoTurn(
  config: {
  tenant?: string;
  input: RedoTurnInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "redo_turn",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type RestoreFilesInput = {
  turnId: UUID;
  confirm?: boolean | null;
  mode?: "reset_hard" | "restore_tree" | null;
};

export type RestoreFilesFields = UnifiedFieldSelection<{safetyCommit: string | null, head: string, __type: "TypedMap", __primitiveFields: "safetyCommit" | "head"}>[];

export type InferRestoreFilesResult<
  Fields extends RestoreFilesFields | undefined,
> = InferResult<{safetyCommit: string | null, head: string, __type: "TypedMap", __primitiveFields: "safetyCommit" | "head"}, Fields>;

export type RestoreFilesResult<Fields extends RestoreFilesFields | undefined = undefined> = | { success: true; data: InferRestoreFilesResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Turn
 *
 * @ashActionType :action
 */
export async function restoreFiles<Fields extends RestoreFilesFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: RestoreFilesInput;
  hookCtx?: ActionHookContext;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<RestoreFilesResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "restore_files",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<RestoreFilesResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Turn
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateRestoreFiles(
  config: {
  tenant?: string;
  input: RestoreFilesInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "restore_files",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type RestoreProposalInput = {
  turnId: UUID;
};

export type RestoreProposalFields = UnifiedFieldSelection<{commit: string, dirtyNow: boolean, changedFiles: Array<string>, laterTurns: number, __type: "TypedMap", __primitiveFields: "commit" | "dirtyNow" | "changedFiles" | "laterTurns"}>[];

export type InferRestoreProposalResult<
  Fields extends RestoreProposalFields | undefined,
> = InferResult<{commit: string, dirtyNow: boolean, changedFiles: Array<string>, laterTurns: number, __type: "TypedMap", __primitiveFields: "commit" | "dirtyNow" | "changedFiles" | "laterTurns"}, Fields>;

export type RestoreProposalResult<Fields extends RestoreProposalFields | undefined = undefined> = | { success: true; data: InferRestoreProposalResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Turn
 *
 * @ashActionType :action
 */
export async function restoreProposal<Fields extends RestoreProposalFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: RestoreProposalInput;
  hookCtx?: ActionHookContext;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<RestoreProposalResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "restore_proposal",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<RestoreProposalResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Turn
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateRestoreProposal(
  config: {
  tenant?: string;
  input: RestoreProposalInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "restore_proposal",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListDirectoryInput = {
  path?: string | null;
  showHidden?: boolean | null;
};

export type ListDirectoryFields = UnifiedFieldSelection<{path: string, parent: string | null, git: boolean, entries: Array<Record<string, any>>, roots: Array<Record<string, any>>, __type: "TypedMap", __primitiveFields: "path" | "parent" | "git" | "entries" | "roots"}>[];

export type InferListDirectoryResult<
  Fields extends ListDirectoryFields | undefined,
> = InferResult<{path: string, parent: string | null, git: boolean, entries: Array<Record<string, any>>, roots: Array<Record<string, any>>, __type: "TypedMap", __primitiveFields: "path" | "parent" | "git" | "entries" | "roots"}, Fields>;

export type ListDirectoryResult<Fields extends ListDirectoryFields | undefined = undefined> = | { success: true; data: InferListDirectoryResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Status
 *
 * @ashActionType :action
 */
export async function listDirectory<Fields extends ListDirectoryFields | undefined = undefined>(
  config: {
  tenant?: string;
  input?: ListDirectoryInput;
  hookCtx?: ActionHookContext;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListDirectoryResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "list_directory",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<ListDirectoryResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Status
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateListDirectory(
  config: {
  tenant?: string;
  input?: ListDirectoryInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_directory",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type SandboxStatusFields = UnifiedFieldSelection<{status: "ok" | "unavailable", reason: string | null, checkedAt: UtcDateTimeUsec, __type: "TypedMap", __primitiveFields: "status" | "reason" | "checkedAt"}>[];

export type InferSandboxStatusResult<
  Fields extends SandboxStatusFields | undefined,
> = InferResult<{status: "ok" | "unavailable", reason: string | null, checkedAt: UtcDateTimeUsec, __type: "TypedMap", __primitiveFields: "status" | "reason" | "checkedAt"}, Fields>;

export type SandboxStatusResult<Fields extends SandboxStatusFields | undefined = undefined> = | { success: true; data: InferSandboxStatusResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Status
 *
 * @ashActionType :action
 */
export async function sandboxStatus<Fields extends SandboxStatusFields | undefined = undefined>(
  config: {
  tenant?: string;
  hookCtx?: ActionHookContext;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<SandboxStatusResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "sandbox_status",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<SandboxStatusResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Status
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateSandboxStatus(
  config: {
  tenant?: string;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "sandbox_status",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}

