// Generated by AshTypescript - Shared Types
// Do not edit this file manually

import * as RpcHooks from "./core/rpcHooks";

export type UUID = string;
export type UUIDv7 = string;
export type UtcDateTimeUsec = string;

// Model Schema
export type ModelResourceSchema = {
  __type: "Resource";
  __primitiveFields: "contextWindow" | "default" | "hostedWebSearch" | "id" | "insertedAt" | "maxOutputTokens" | "name" | "providerId" | "reasoningEffort" | "reasoningLevels" | "reasoningSummary" | "slug" | "updatedAt" | "upstreamId";
  contextWindow: number;
  default: boolean;
  hostedWebSearch: boolean | null;
  id: UUIDv7;
  insertedAt: UtcDateTimeUsec;
  maxOutputTokens: number | null;
  name: string;
  providerId: UUID;
  reasoningEffort: string | null;
  reasoningLevels: Array<string>;
  reasoningSummary: "auto" | "concise" | "detailed" | "none" | null;
  slug: string | null;
  updatedAt: UtcDateTimeUsec;
  upstreamId: string;
  provider: { __type: "Relationship"; __resource: ProviderResourceSchema; };
};



export type ModelAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "contextWindow" | "default" | "hostedWebSearch" | "id" | "insertedAt" | "maxOutputTokens" | "name" | "providerId" | "reasoningEffort" | "reasoningLevels" | "reasoningSummary" | "slug" | "updatedAt" | "upstreamId";
  contextWindow: number;
  default: boolean;
  hostedWebSearch: boolean | null;
  id: UUIDv7;
  insertedAt: UtcDateTimeUsec;
  maxOutputTokens: number | null;
  name: string;
  providerId: UUID;
  reasoningEffort: string | null;
  reasoningLevels: Array<string>;
  reasoningSummary: "auto" | "concise" | "detailed" | "none" | null;
  slug: string | null;
  updatedAt: UtcDateTimeUsec;
  upstreamId: string;
};


// Preset Schema
export type PresetResourceSchema = {
  __type: "Resource";
  __primitiveFields: never;
};



export type PresetAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: never;
};


// Provider Schema
export type ProviderResourceSchema = {
  __type: "Resource";
  __primitiveFields: "baseUrl" | "hasApiKey" | "id" | "insertedAt" | "kind" | "lastCheckedAt" | "lastError" | "lastErrorAt" | "maxConcurrentRequests" | "name" | "requestTimeoutMs" | "slug" | "supportsHostedWebSearch" | "updatedAt";
  baseUrl: string;
  hasApiKey: boolean | null;
  id: UUIDv7;
  insertedAt: UtcDateTimeUsec;
  kind: "openai" | "openai_compatible";
  lastCheckedAt: UtcDateTimeUsec | null;
  lastError: string | null;
  lastErrorAt: UtcDateTimeUsec | null;
  maxConcurrentRequests: number | null;
  name: string;
  requestTimeoutMs: number;
  slug: string;
  supportsHostedWebSearch: boolean;
  updatedAt: UtcDateTimeUsec;
};



export type ProviderAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "baseUrl" | "id" | "insertedAt" | "kind" | "lastCheckedAt" | "lastError" | "lastErrorAt" | "maxConcurrentRequests" | "name" | "requestTimeoutMs" | "slug" | "supportsHostedWebSearch" | "updatedAt";
  baseUrl: string;
  id: UUIDv7;
  insertedAt: UtcDateTimeUsec;
  kind: "openai" | "openai_compatible";
  lastCheckedAt: UtcDateTimeUsec | null;
  lastError: string | null;
  lastErrorAt: UtcDateTimeUsec | null;
  maxConcurrentRequests: number | null;
  name: string;
  requestTimeoutMs: number;
  slug: string;
  supportsHostedWebSearch: boolean;
  updatedAt: UtcDateTimeUsec;
};


// SearchProvider Schema
export type SearchProviderResourceSchema = {
  __type: "Resource";
  __primitiveFields: "baseUrl" | "default" | "hasApiKey" | "id" | "kind" | "name" | "slug";
  baseUrl: string;
  default: boolean;
  hasApiKey: boolean | null;
  id: UUIDv7;
  kind: "tavily";
  name: string;
  slug: string;
};



export type SearchProviderAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "baseUrl" | "default" | "id" | "kind" | "name" | "slug";
  baseUrl: string;
  default: boolean;
  id: UUIDv7;
  kind: "tavily";
  name: string;
  slug: string;
};


// Credential Schema
export type CredentialResourceSchema = {
  __type: "Resource";
  __primitiveFields: "allowedHosts" | "authorizeUrl" | "clientId" | "expiresAt" | "extraParams" | "hasAccessToken" | "hasClientSecret" | "hasRefreshToken" | "hasSecret" | "header" | "id" | "insertedAt" | "kind" | "label" | "lastError" | "lastErrorAt" | "name" | "pkce" | "refreshedAt" | "registrationUrl" | "scheme" | "scopes" | "status" | "tokenUrl" | "updatedAt";
  allowedHosts: Array<string>;
  authorizeUrl: string | null;
  clientId: string | null;
  expiresAt: UtcDateTimeUsec | null;
  extraParams: Record<string, any>;
  hasAccessToken: boolean | null;
  hasClientSecret: boolean | null;
  hasRefreshToken: boolean | null;
  hasSecret: boolean | null;
  header: string;
  id: UUIDv7;
  insertedAt: UtcDateTimeUsec;
  kind: "api_key" | "oauth2";
  label: string | null;
  lastError: string | null;
  lastErrorAt: UtcDateTimeUsec | null;
  name: string;
  pkce: boolean;
  refreshedAt: UtcDateTimeUsec | null;
  registrationUrl: string | null;
  scheme: string;
  scopes: string | null;
  status: "error" | "expired" | "needs_login" | "ready" | null;
  tokenUrl: string | null;
  updatedAt: UtcDateTimeUsec;
};



export type CredentialAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "allowedHosts" | "authorizeUrl" | "clientId" | "expiresAt" | "extraParams" | "header" | "id" | "insertedAt" | "kind" | "label" | "lastError" | "lastErrorAt" | "name" | "pkce" | "refreshedAt" | "registrationUrl" | "scheme" | "scopes" | "tokenUrl" | "updatedAt";
  allowedHosts: Array<string>;
  authorizeUrl: string | null;
  clientId: string | null;
  expiresAt: UtcDateTimeUsec | null;
  extraParams: Record<string, any>;
  header: string;
  id: UUIDv7;
  insertedAt: UtcDateTimeUsec;
  kind: "api_key" | "oauth2";
  label: string | null;
  lastError: string | null;
  lastErrorAt: UtcDateTimeUsec | null;
  name: string;
  pkce: boolean;
  refreshedAt: UtcDateTimeUsec | null;
  registrationUrl: string | null;
  scheme: string;
  scopes: string | null;
  tokenUrl: string | null;
  updatedAt: UtcDateTimeUsec;
};


// ProjectFiles Schema
export type ProjectFilesResourceSchema = {
  __type: "Resource";
  __primitiveFields: never;
};



export type ProjectFilesAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: never;
};


// Project Schema
export type ProjectResourceSchema = {
  __type: "Resource";
  __primitiveFields: "agentSettings" | "archivedAt" | "description" | "dirtyStart" | "id" | "insertedAt" | "modelId" | "name" | "rootPath" | "slug" | "trustLocalAgent" | "updatedAt" | "webSearch";
  agentSettings: Record<string, any> | null;
  archivedAt: UtcDateTimeUsec | null;
  description: string | null;
  dirtyStart: "ask" | "commit" | "off";
  id: UUIDv7;
  insertedAt: UtcDateTimeUsec;
  modelId: UUID | null;
  name: string;
  rootPath: string;
  slug: string;
  trustLocalAgent: boolean;
  updatedAt: UtcDateTimeUsec;
  webSearch: boolean;
  model: { __type: "Relationship"; __resource: ModelResourceSchema | null; };
};



export type ProjectAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "agentSettings" | "archivedAt" | "description" | "dirtyStart" | "id" | "insertedAt" | "modelId" | "name" | "rootPath" | "slug" | "trustLocalAgent" | "updatedAt" | "webSearch";
  agentSettings: Record<string, any> | null;
  archivedAt: UtcDateTimeUsec | null;
  description: string | null;
  dirtyStart: "ask" | "commit" | "off";
  id: UUIDv7;
  insertedAt: UtcDateTimeUsec;
  modelId: UUID | null;
  name: string;
  rootPath: string;
  slug: string;
  trustLocalAgent: boolean;
  updatedAt: UtcDateTimeUsec;
  webSearch: boolean;
};


// ProjectRepo Schema
export type ProjectRepoResourceSchema = {
  __type: "Resource";
  __primitiveFields: never;
};



export type ProjectRepoAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: never;
};


// Thread Schema
export type ThreadResourceSchema = {
  __type: "Resource";
  __primitiveFields: "agentPath" | "cwd" | "id" | "insertedAt" | "kernelThreadId" | "lastActivityAt" | "modelSlug" | "parentThreadId" | "preview" | "projectId" | "reasoningEffort" | "status" | "title" | "updatedAt" | "webSearch";
  agentPath: string | null;
  cwd: string;
  id: UUIDv7;
  insertedAt: UtcDateTimeUsec;
  kernelThreadId: string;
  lastActivityAt: UtcDateTimeUsec | null;
  modelSlug: string | null;
  parentThreadId: UUID | null;
  preview: string | null;
  projectId: UUID;
  reasoningEffort: string | null;
  status: "active" | "archived" | "idle" | "unrecoverable";
  title: string | null;
  updatedAt: UtcDateTimeUsec;
  webSearch: boolean;
  parentThread: { __type: "Relationship"; __resource: ThreadResourceSchema | null; };
  project: { __type: "Relationship"; __resource: ProjectResourceSchema; };
};



export type ThreadAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "agentPath" | "cwd" | "id" | "insertedAt" | "kernelThreadId" | "lastActivityAt" | "modelSlug" | "parentThreadId" | "preview" | "projectId" | "reasoningEffort" | "status" | "title" | "updatedAt" | "webSearch";
  agentPath: string | null;
  cwd: string;
  id: UUIDv7;
  insertedAt: UtcDateTimeUsec;
  kernelThreadId: string;
  lastActivityAt: UtcDateTimeUsec | null;
  modelSlug: string | null;
  parentThreadId: UUID | null;
  preview: string | null;
  projectId: UUID;
  reasoningEffort: string | null;
  status: "active" | "archived" | "idle" | "unrecoverable";
  title: string | null;
  updatedAt: UtcDateTimeUsec;
  webSearch: boolean;
};


// Turn Schema
export type TurnResourceSchema = {
  __type: "Resource";
  __primitiveFields: "commitAfter" | "commitBefore" | "completedAt" | "diff" | "dirtyStart" | "error" | "id" | "insertedAt" | "kernelTurnId" | "modelSlug" | "reasoningEffort" | "startedAt" | "status" | "threadId" | "updatedAt" | "usage" | "userText";
  commitAfter: string | null;
  commitBefore: string | null;
  completedAt: UtcDateTimeUsec | null;
  diff: string | null;
  dirtyStart: boolean;
  error: string | null;
  id: UUIDv7;
  insertedAt: UtcDateTimeUsec;
  kernelTurnId: string;
  modelSlug: string | null;
  reasoningEffort: string | null;
  startedAt: UtcDateTimeUsec;
  status: "completed" | "failed" | "in_progress" | "interrupted" | "reverted";
  threadId: UUID;
  updatedAt: UtcDateTimeUsec;
  usage: Record<string, any> | null;
  userText: string | null;
  thread: { __type: "Relationship"; __resource: ThreadResourceSchema; };
};



export type TurnAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "commitAfter" | "commitBefore" | "completedAt" | "diff" | "dirtyStart" | "error" | "id" | "insertedAt" | "kernelTurnId" | "modelSlug" | "reasoningEffort" | "startedAt" | "status" | "threadId" | "updatedAt" | "usage" | "userText";
  commitAfter: string | null;
  commitBefore: string | null;
  completedAt: UtcDateTimeUsec | null;
  diff: string | null;
  dirtyStart: boolean;
  error: string | null;
  id: UUIDv7;
  insertedAt: UtcDateTimeUsec;
  kernelTurnId: string;
  modelSlug: string | null;
  reasoningEffort: string | null;
  startedAt: UtcDateTimeUsec;
  status: "completed" | "failed" | "in_progress" | "interrupted" | "reverted";
  threadId: UUID;
  updatedAt: UtcDateTimeUsec;
  usage: Record<string, any> | null;
  userText: string | null;
};


// SystemStatus Schema
export type SystemStatusResourceSchema = {
  __type: "Resource";
  __primitiveFields: never;
};



export type SystemStatusAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: never;
};


export type ModelFilterInput = {
  and?: Array<ModelFilterInput>;
  or?: Array<ModelFilterInput>;
  not?: Array<ModelFilterInput>;

  contextWindow?: {
    eq?: number;
    notEq?: number;
    in?: Array<number>;
    lessThan?: number;
    greaterThan?: number;
    lessThanOrEqual?: number;
    greaterThanOrEqual?: number;
  };

  default?: {
    eq?: boolean;
    notEq?: boolean;
    in?: Array<boolean>;
  };

  hostedWebSearch?: {
    isNil?: boolean;
    eq?: boolean;
    notEq?: boolean;
    in?: Array<boolean>;
  };

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
    lessThan?: UUIDv7;
    greaterThan?: UUIDv7;
    lessThanOrEqual?: UUIDv7;
    greaterThanOrEqual?: UUIDv7;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    lessThan?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
  };

  maxOutputTokens?: {
    isNil?: boolean;
    eq?: number;
    notEq?: number;
    in?: Array<number>;
    lessThan?: number;
    greaterThan?: number;
    lessThanOrEqual?: number;
    greaterThanOrEqual?: number;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  providerId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    lessThan?: UUID;
    greaterThan?: UUID;
    lessThanOrEqual?: UUID;
    greaterThanOrEqual?: UUID;
  };

  reasoningEffort?: {
    isNil?: boolean;
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  reasoningLevels?: {
    eq?: Array<string>;
    notEq?: Array<string>;
    in?: Array<Array<string>>;
    has?: string;
  };

  reasoningSummary?: {
    isNil?: boolean;
    eq?: "auto" | "concise" | "detailed" | "none";
    notEq?: "auto" | "concise" | "detailed" | "none";
    in?: Array<"auto" | "concise" | "detailed" | "none">;
    lessThan?: "auto" | "concise" | "detailed" | "none";
    greaterThan?: "auto" | "concise" | "detailed" | "none";
    lessThanOrEqual?: "auto" | "concise" | "detailed" | "none";
    greaterThanOrEqual?: "auto" | "concise" | "detailed" | "none";
  };

  slug?: {
    isNil?: boolean;
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    lessThan?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
  };

  upstreamId?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  provider?: ProviderFilterInput;

};
export type PresetFilterInput = {
  and?: Array<PresetFilterInput>;
  or?: Array<PresetFilterInput>;
  not?: Array<PresetFilterInput>;



};
export type ProviderFilterInput = {
  and?: Array<ProviderFilterInput>;
  or?: Array<ProviderFilterInput>;
  not?: Array<ProviderFilterInput>;

  baseUrl?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  hasApiKey?: {
    isNil?: boolean;
    eq?: boolean;
    notEq?: boolean;
    in?: Array<boolean>;
  };

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
    lessThan?: UUIDv7;
    greaterThan?: UUIDv7;
    lessThanOrEqual?: UUIDv7;
    greaterThanOrEqual?: UUIDv7;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    lessThan?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
  };

  kind?: {
    eq?: "openai" | "openai_compatible";
    notEq?: "openai" | "openai_compatible";
    in?: Array<"openai" | "openai_compatible">;
    lessThan?: "openai" | "openai_compatible";
    greaterThan?: "openai" | "openai_compatible";
    lessThanOrEqual?: "openai" | "openai_compatible";
    greaterThanOrEqual?: "openai" | "openai_compatible";
  };

  lastCheckedAt?: {
    isNil?: boolean;
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    lessThan?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
  };

  lastError?: {
    isNil?: boolean;
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  lastErrorAt?: {
    isNil?: boolean;
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    lessThan?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
  };

  maxConcurrentRequests?: {
    isNil?: boolean;
    eq?: number;
    notEq?: number;
    in?: Array<number>;
    lessThan?: number;
    greaterThan?: number;
    lessThanOrEqual?: number;
    greaterThanOrEqual?: number;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  requestTimeoutMs?: {
    eq?: number;
    notEq?: number;
    in?: Array<number>;
    lessThan?: number;
    greaterThan?: number;
    lessThanOrEqual?: number;
    greaterThanOrEqual?: number;
  };

  slug?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  supportsHostedWebSearch?: {
    eq?: boolean;
    notEq?: boolean;
    in?: Array<boolean>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    lessThan?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
  };


};
export type SearchProviderFilterInput = {
  and?: Array<SearchProviderFilterInput>;
  or?: Array<SearchProviderFilterInput>;
  not?: Array<SearchProviderFilterInput>;

  baseUrl?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  default?: {
    eq?: boolean;
    notEq?: boolean;
    in?: Array<boolean>;
  };

  hasApiKey?: {
    isNil?: boolean;
    eq?: boolean;
    notEq?: boolean;
    in?: Array<boolean>;
  };

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
    lessThan?: UUIDv7;
    greaterThan?: UUIDv7;
    lessThanOrEqual?: UUIDv7;
    greaterThanOrEqual?: UUIDv7;
  };

  kind?: {
    eq?: "tavily";
    notEq?: "tavily";
    in?: Array<"tavily">;
    lessThan?: "tavily";
    greaterThan?: "tavily";
    lessThanOrEqual?: "tavily";
    greaterThanOrEqual?: "tavily";
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  slug?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };


};
export type CredentialFilterInput = {
  and?: Array<CredentialFilterInput>;
  or?: Array<CredentialFilterInput>;
  not?: Array<CredentialFilterInput>;

  allowedHosts?: {
    eq?: Array<string>;
    notEq?: Array<string>;
    in?: Array<Array<string>>;
    has?: string;
  };

  authorizeUrl?: {
    isNil?: boolean;
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  clientId?: {
    isNil?: boolean;
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  expiresAt?: {
    isNil?: boolean;
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    lessThan?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
  };

  extraParams?: {
    eq?: Record<string, any>;
    notEq?: Record<string, any>;
    in?: Array<Record<string, any>>;
    lessThan?: Record<string, any>;
    greaterThan?: Record<string, any>;
    lessThanOrEqual?: Record<string, any>;
    greaterThanOrEqual?: Record<string, any>;
  };

  hasAccessToken?: {
    isNil?: boolean;
    eq?: boolean;
    notEq?: boolean;
    in?: Array<boolean>;
  };

  hasClientSecret?: {
    isNil?: boolean;
    eq?: boolean;
    notEq?: boolean;
    in?: Array<boolean>;
  };

  hasRefreshToken?: {
    isNil?: boolean;
    eq?: boolean;
    notEq?: boolean;
    in?: Array<boolean>;
  };

  hasSecret?: {
    isNil?: boolean;
    eq?: boolean;
    notEq?: boolean;
    in?: Array<boolean>;
  };

  header?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
    lessThan?: UUIDv7;
    greaterThan?: UUIDv7;
    lessThanOrEqual?: UUIDv7;
    greaterThanOrEqual?: UUIDv7;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    lessThan?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
  };

  kind?: {
    eq?: "api_key" | "oauth2";
    notEq?: "api_key" | "oauth2";
    in?: Array<"api_key" | "oauth2">;
    lessThan?: "api_key" | "oauth2";
    greaterThan?: "api_key" | "oauth2";
    lessThanOrEqual?: "api_key" | "oauth2";
    greaterThanOrEqual?: "api_key" | "oauth2";
  };

  label?: {
    isNil?: boolean;
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  lastError?: {
    isNil?: boolean;
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  lastErrorAt?: {
    isNil?: boolean;
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    lessThan?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  pkce?: {
    eq?: boolean;
    notEq?: boolean;
    in?: Array<boolean>;
  };

  refreshedAt?: {
    isNil?: boolean;
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    lessThan?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
  };

  registrationUrl?: {
    isNil?: boolean;
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  scheme?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  scopes?: {
    isNil?: boolean;
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  status?: {
    isNil?: boolean;
    eq?: "error" | "expired" | "needs_login" | "ready";
    notEq?: "error" | "expired" | "needs_login" | "ready";
    in?: Array<"error" | "expired" | "needs_login" | "ready">;
    lessThan?: "error" | "expired" | "needs_login" | "ready";
    greaterThan?: "error" | "expired" | "needs_login" | "ready";
    lessThanOrEqual?: "error" | "expired" | "needs_login" | "ready";
    greaterThanOrEqual?: "error" | "expired" | "needs_login" | "ready";
  };

  tokenUrl?: {
    isNil?: boolean;
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    lessThan?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
  };


};
export type ProjectFilesFilterInput = {
  and?: Array<ProjectFilesFilterInput>;
  or?: Array<ProjectFilesFilterInput>;
  not?: Array<ProjectFilesFilterInput>;



};
export type ProjectFilterInput = {
  and?: Array<ProjectFilterInput>;
  or?: Array<ProjectFilterInput>;
  not?: Array<ProjectFilterInput>;

  agentSettings?: {
    isNil?: boolean;
    eq?: Record<string, any>;
    notEq?: Record<string, any>;
    in?: Array<Record<string, any>>;
    lessThan?: Record<string, any>;
    greaterThan?: Record<string, any>;
    lessThanOrEqual?: Record<string, any>;
    greaterThanOrEqual?: Record<string, any>;
  };

  archivedAt?: {
    isNil?: boolean;
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    lessThan?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
  };

  description?: {
    isNil?: boolean;
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  dirtyStart?: {
    eq?: "ask" | "commit" | "off";
    notEq?: "ask" | "commit" | "off";
    in?: Array<"ask" | "commit" | "off">;
    lessThan?: "ask" | "commit" | "off";
    greaterThan?: "ask" | "commit" | "off";
    lessThanOrEqual?: "ask" | "commit" | "off";
    greaterThanOrEqual?: "ask" | "commit" | "off";
  };

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
    lessThan?: UUIDv7;
    greaterThan?: UUIDv7;
    lessThanOrEqual?: UUIDv7;
    greaterThanOrEqual?: UUIDv7;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    lessThan?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
  };

  modelId?: {
    isNil?: boolean;
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    lessThan?: UUID;
    greaterThan?: UUID;
    lessThanOrEqual?: UUID;
    greaterThanOrEqual?: UUID;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  rootPath?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  slug?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  trustLocalAgent?: {
    eq?: boolean;
    notEq?: boolean;
    in?: Array<boolean>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    lessThan?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
  };

  webSearch?: {
    eq?: boolean;
    notEq?: boolean;
    in?: Array<boolean>;
  };

  model?: ModelFilterInput;

};
export type ProjectRepoFilterInput = {
  and?: Array<ProjectRepoFilterInput>;
  or?: Array<ProjectRepoFilterInput>;
  not?: Array<ProjectRepoFilterInput>;



};
export type ThreadFilterInput = {
  and?: Array<ThreadFilterInput>;
  or?: Array<ThreadFilterInput>;
  not?: Array<ThreadFilterInput>;

  agentPath?: {
    isNil?: boolean;
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  cwd?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
    lessThan?: UUIDv7;
    greaterThan?: UUIDv7;
    lessThanOrEqual?: UUIDv7;
    greaterThanOrEqual?: UUIDv7;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    lessThan?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
  };

  kernelThreadId?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  lastActivityAt?: {
    isNil?: boolean;
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    lessThan?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
  };

  modelSlug?: {
    isNil?: boolean;
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  parentThreadId?: {
    isNil?: boolean;
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    lessThan?: UUID;
    greaterThan?: UUID;
    lessThanOrEqual?: UUID;
    greaterThanOrEqual?: UUID;
  };

  preview?: {
    isNil?: boolean;
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  projectId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    lessThan?: UUID;
    greaterThan?: UUID;
    lessThanOrEqual?: UUID;
    greaterThanOrEqual?: UUID;
  };

  reasoningEffort?: {
    isNil?: boolean;
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  status?: {
    eq?: "active" | "archived" | "idle" | "unrecoverable";
    notEq?: "active" | "archived" | "idle" | "unrecoverable";
    in?: Array<"active" | "archived" | "idle" | "unrecoverable">;
    lessThan?: "active" | "archived" | "idle" | "unrecoverable";
    greaterThan?: "active" | "archived" | "idle" | "unrecoverable";
    lessThanOrEqual?: "active" | "archived" | "idle" | "unrecoverable";
    greaterThanOrEqual?: "active" | "archived" | "idle" | "unrecoverable";
  };

  title?: {
    isNil?: boolean;
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    lessThan?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
  };

  webSearch?: {
    eq?: boolean;
    notEq?: boolean;
    in?: Array<boolean>;
  };

  parentThread?: ThreadFilterInput;

  project?: ProjectFilterInput;

};
export type TurnFilterInput = {
  and?: Array<TurnFilterInput>;
  or?: Array<TurnFilterInput>;
  not?: Array<TurnFilterInput>;

  commitAfter?: {
    isNil?: boolean;
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  commitBefore?: {
    isNil?: boolean;
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  completedAt?: {
    isNil?: boolean;
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    lessThan?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
  };

  diff?: {
    isNil?: boolean;
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  dirtyStart?: {
    eq?: boolean;
    notEq?: boolean;
    in?: Array<boolean>;
  };

  error?: {
    isNil?: boolean;
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
    lessThan?: UUIDv7;
    greaterThan?: UUIDv7;
    lessThanOrEqual?: UUIDv7;
    greaterThanOrEqual?: UUIDv7;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    lessThan?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
  };

  kernelTurnId?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  modelSlug?: {
    isNil?: boolean;
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  reasoningEffort?: {
    isNil?: boolean;
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  startedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    lessThan?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
  };

  status?: {
    eq?: "completed" | "failed" | "in_progress" | "interrupted" | "reverted";
    notEq?: "completed" | "failed" | "in_progress" | "interrupted" | "reverted";
    in?: Array<"completed" | "failed" | "in_progress" | "interrupted" | "reverted">;
    lessThan?: "completed" | "failed" | "in_progress" | "interrupted" | "reverted";
    greaterThan?: "completed" | "failed" | "in_progress" | "interrupted" | "reverted";
    lessThanOrEqual?: "completed" | "failed" | "in_progress" | "interrupted" | "reverted";
    greaterThanOrEqual?: "completed" | "failed" | "in_progress" | "interrupted" | "reverted";
  };

  threadId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    lessThan?: UUID;
    greaterThan?: UUID;
    lessThanOrEqual?: UUID;
    greaterThanOrEqual?: UUID;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    lessThan?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
  };

  usage?: {
    isNil?: boolean;
    eq?: Record<string, any>;
    notEq?: Record<string, any>;
    in?: Array<Record<string, any>>;
    lessThan?: Record<string, any>;
    greaterThan?: Record<string, any>;
    lessThanOrEqual?: Record<string, any>;
    greaterThanOrEqual?: Record<string, any>;
  };

  userText?: {
    isNil?: boolean;
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    lessThan?: string;
    greaterThan?: string;
    lessThanOrEqual?: string;
    greaterThanOrEqual?: string;
    contains?: string;
    stringEndsWith?: string;
    stringStartsWith?: string;
  };

  thread?: ThreadFilterInput;

};
export type SystemStatusFilterInput = {
  and?: Array<SystemStatusFilterInput>;
  or?: Array<SystemStatusFilterInput>;
  not?: Array<SystemStatusFilterInput>;



};


export const modelFilterFields = ["contextWindow", "default", "hostedWebSearch", "id", "insertedAt", "maxOutputTokens", "name", "providerId", "reasoningEffort", "reasoningLevels", "reasoningSummary", "slug", "updatedAt", "upstreamId", "provider"] as const;
export type ModelFilterField = (typeof modelFilterFields)[number];


export const providerFilterFields = ["baseUrl", "hasApiKey", "id", "insertedAt", "kind", "lastCheckedAt", "lastError", "lastErrorAt", "maxConcurrentRequests", "name", "requestTimeoutMs", "slug", "supportsHostedWebSearch", "updatedAt"] as const;
export type ProviderFilterField = (typeof providerFilterFields)[number];

export const searchProviderFilterFields = ["baseUrl", "default", "hasApiKey", "id", "kind", "name", "slug"] as const;
export type SearchProviderFilterField = (typeof searchProviderFilterFields)[number];

export const credentialFilterFields = ["allowedHosts", "authorizeUrl", "clientId", "expiresAt", "extraParams", "hasAccessToken", "hasClientSecret", "hasRefreshToken", "hasSecret", "header", "id", "insertedAt", "kind", "label", "lastError", "lastErrorAt", "name", "pkce", "refreshedAt", "registrationUrl", "scheme", "scopes", "status", "tokenUrl", "updatedAt"] as const;
export type CredentialFilterField = (typeof credentialFilterFields)[number];


export const projectFilterFields = ["agentSettings", "archivedAt", "description", "dirtyStart", "id", "insertedAt", "modelId", "name", "rootPath", "slug", "trustLocalAgent", "updatedAt", "webSearch", "model"] as const;
export type ProjectFilterField = (typeof projectFilterFields)[number];


export const threadFilterFields = ["agentPath", "cwd", "id", "insertedAt", "kernelThreadId", "lastActivityAt", "modelSlug", "parentThreadId", "preview", "projectId", "reasoningEffort", "status", "title", "updatedAt", "webSearch", "parentThread", "project"] as const;
export type ThreadFilterField = (typeof threadFilterFields)[number];

export const turnFilterFields = ["commitAfter", "commitBefore", "completedAt", "diff", "dirtyStart", "error", "id", "insertedAt", "kernelTurnId", "modelSlug", "reasoningEffort", "startedAt", "status", "threadId", "updatedAt", "usage", "userText", "thread"] as const;
export type TurnFilterField = (typeof turnFilterFields)[number];



export const modelSortFields = ["contextWindow", "default", "hostedWebSearch", "id", "insertedAt", "maxOutputTokens", "name", "providerId", "reasoningEffort", "reasoningLevels", "reasoningSummary", "slug", "updatedAt", "upstreamId"] as const;
export type ModelSortField = (typeof modelSortFields)[number];


export const providerSortFields = ["baseUrl", "hasApiKey", "id", "insertedAt", "kind", "lastCheckedAt", "lastError", "lastErrorAt", "maxConcurrentRequests", "name", "requestTimeoutMs", "slug", "supportsHostedWebSearch", "updatedAt"] as const;
export type ProviderSortField = (typeof providerSortFields)[number];

export const searchProviderSortFields = ["baseUrl", "default", "hasApiKey", "id", "kind", "name", "slug"] as const;
export type SearchProviderSortField = (typeof searchProviderSortFields)[number];

export const credentialSortFields = ["allowedHosts", "authorizeUrl", "clientId", "expiresAt", "extraParams", "hasAccessToken", "hasClientSecret", "hasRefreshToken", "hasSecret", "header", "id", "insertedAt", "kind", "label", "lastError", "lastErrorAt", "name", "pkce", "refreshedAt", "registrationUrl", "scheme", "scopes", "status", "tokenUrl", "updatedAt"] as const;
export type CredentialSortField = (typeof credentialSortFields)[number];


export const projectSortFields = ["agentSettings", "archivedAt", "description", "dirtyStart", "id", "insertedAt", "modelId", "name", "rootPath", "slug", "trustLocalAgent", "updatedAt", "webSearch"] as const;
export type ProjectSortField = (typeof projectSortFields)[number];


export const threadSortFields = ["agentPath", "cwd", "id", "insertedAt", "kernelThreadId", "lastActivityAt", "modelSlug", "parentThreadId", "preview", "projectId", "reasoningEffort", "status", "title", "updatedAt", "webSearch"] as const;
export type ThreadSortField = (typeof threadSortFields)[number];

export const turnSortFields = ["commitAfter", "commitBefore", "completedAt", "diff", "dirtyStart", "error", "id", "insertedAt", "kernelTurnId", "modelSlug", "reasoningEffort", "startedAt", "status", "threadId", "updatedAt", "usage", "userText"] as const;
export type TurnSortField = (typeof turnSortFields)[number];



// Utility Types

// Sort string type — allows optional direction prefix on sort field names
// Prefixes per Ash.Query.sort/3: + (asc), - (desc), ++ (asc_nils_first), -- (desc_nils_last)
export type SortString<T extends string> = T | `+${T}` | `-${T}` | `++${T}` | `--${T}`;

// Nested relationship pagination input, keyed by the relationship's
// __pagination marker ("offset" | "keyset" | "mixed"). Keys of the other
// pagination family are typed `never` so passing them is a structural
// error (excess-property checking does not fire through the envelope's
// conditional types).
export type NestedPageInput<P extends string> = P extends "offset"
  ? { limit?: number; offset?: number; count?: boolean; after?: never; before?: never }
  : P extends "keyset"
    ? { limit?: number; after?: string; before?: string; count?: boolean; offset?: never }
    :
        | { limit?: number; offset?: number; count?: boolean; after?: never; before?: never }
        | { limit?: number; after?: string; before?: string; count?: boolean; offset?: never };

// Resource schema constraint
export type TypedSchema = {
  __type: "Resource" | "TypedMap" | "Union";
  __primitiveFields: string;
};

// Utility type to convert union to intersection
export type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;

// Helper type to infer union field values, avoiding duplication between array and non-array unions
// Selection-object walkers use key remapping to drop keys whose value is
// undefined: hoisting a selection with `satisfies` widens the array to a
// union whose object members grow synthetic `?: undefined` siblings, and
// walking those as real selections would collapse the result to never.
// `FieldSelection[FieldIndex] extends infer Sel` re-binds the element to a
// naked type parameter so widened (non-tuple) selections distribute over
// their element union instead of falling through to never.
export type InferUnionFieldValue<
  UnionSchema extends { __type: "Union"; __primitiveFields: any },
  FieldSelection extends any[],
> = UnionToIntersection<
  {
    [FieldIndex in keyof FieldSelection]: FieldSelection[FieldIndex] extends infer Sel
      ? Sel extends UnionSchema["__primitiveFields"]
        ? Sel extends keyof UnionSchema
          ? { [P in Sel]: UnionSchema[Sel] }
          : never
        : Sel extends Record<string, any>
          ? {
              [UnionKey in keyof Sel as Sel[UnionKey] extends undefined ? never : UnionKey]: UnionKey extends keyof UnionSchema
                ? NonNullable<UnionSchema[UnionKey]> extends { __array: true; __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
                  ? Sel[UnionKey] extends any[]
                    ? Array<
                        UnionToIntersection<
                          {
                            [FieldIdx in keyof Sel[UnionKey]]: Sel[UnionKey][FieldIdx] extends TypedMapFields
                              ? Sel[UnionKey][FieldIdx] extends keyof NonNullable<UnionSchema[UnionKey]>
                                ? { [P in Sel[UnionKey][FieldIdx]]: NonNullable<UnionSchema[UnionKey]>[P] }
                                : never
                              : never;
                          }[number]
                        >
                      > | null
                    : never
                  : NonNullable<UnionSchema[UnionKey]> extends { __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
                    ? Sel[UnionKey] extends any[]
                      ? UnionToIntersection<
                          {
                            [FieldIdx in keyof Sel[UnionKey]]: Sel[UnionKey][FieldIdx] extends TypedMapFields
                              ? Sel[UnionKey][FieldIdx] extends keyof NonNullable<UnionSchema[UnionKey]>
                                ? { [P in Sel[UnionKey][FieldIdx]]: NonNullable<UnionSchema[UnionKey]>[P] }
                                : never
                              : never;
                          }[number]
                        > | null
                      : never
                    : NonNullable<UnionSchema[UnionKey]> extends TypedSchema
                      ? InferResult<NonNullable<UnionSchema[UnionKey]>, Sel[UnionKey]>
                      : never
                : never;
            }
          : never
      : never;
  }[number]
>;

export type HasComplexFields<T extends TypedSchema> = keyof Omit<
  T,
  "__primitiveFields" | "__type" | T["__primitiveFields"]
> extends never
  ? false
  : true;

export type ComplexFieldKeys<T extends TypedSchema> = keyof Omit<
  T,
  "__primitiveFields" | "__type" | T["__primitiveFields"]
>;

export type LeafFieldSelection<T extends TypedSchema> = T["__primitiveFields"];

// Query-option envelope for many-cardinality relationships. Each optional
// key is usable only when the corresponding capability marker is present
// and the action-level flag (F = filter, S = sort) is enabled; otherwise
// the key is typed `never` so passing a value is a structural error (plain
// excess-property checking does not fire through these conditional types).
// `page` and bare `limit`/`offset` are mutually exclusive: the pagination
// part is a union of the two shapes, each `never`-typing the other's keys.
export type RelationshipQueryEnvelope<
  Meta,
  Dest extends TypedSchema,
  F extends boolean = true,
  S extends boolean = true,
> = {
  fields: UnifiedFieldSelection<Dest, F, S>[];
} & (F extends true
  ? Meta extends { __filterInput: infer FI }
    ? { filter?: FI }
    : { filter?: never }
  : { filter?: never }) &
  (S extends true
    ? Meta extends { __sortField: infer SF extends string }
      ? { sort?: SortString<SF> | SortString<SF>[] }
      : { sort?: never }
    : { sort?: never }) &
  (Meta extends { __pagination: infer P extends string }
    ? (
        | { page?: NestedPageInput<P>; limit?: never; offset?: never }
        | { limit?: number; offset?: number; page?: never }
      )
    : { limit?: number; offset?: number; page?: never });

export type ComplexFieldSelection<
  T extends TypedSchema,
  F extends boolean = true,
  S extends boolean = true,
> = {
  [K in ComplexFieldKeys<T>]?: T[K] extends {
    __type: "Relationship";
    __resource: infer Resource;
  }
    ? NonNullable<Resource> extends TypedSchema
      ? T[K] extends { __array: true }
        ?
            | UnifiedFieldSelection<NonNullable<Resource>, F, S>[]
            | RelationshipQueryEnvelope<T[K], NonNullable<Resource>, F, S>
        : UnifiedFieldSelection<NonNullable<Resource>, F, S>[]
      : never
    : T[K] extends {
          __type: "ComplexCalculation";
          __returnType: infer ReturnType;
        }
      ? T[K] extends { __args: infer Args }
        ? NonNullable<ReturnType> extends TypedSchema
          ? {
              args: Args;
              fields: UnifiedFieldSelection<NonNullable<ReturnType>, F, S>[];
            }
          : { args: Args }
        : NonNullable<ReturnType> extends TypedSchema
          ? { fields: UnifiedFieldSelection<NonNullable<ReturnType>, F, S>[] }
          : never
      : T[K] extends { __type: "TypedMap" }
        ? NonNullable<T[K]> extends TypedSchema
          ? UnifiedFieldSelection<NonNullable<T[K]>, F, S>[]
          : never
        : T[K] extends { __type: "Union"; __primitiveFields: infer PrimitiveFields }
          ? T[K] extends { __array: true }
            ? (PrimitiveFields | {
                [UnionKey in keyof Omit<T[K], "__type" | "__primitiveFields" | "__array">]?: NonNullable<T[K][UnionKey]> extends { __type: "TypedMap"; __primitiveFields: any }
                  ? NonNullable<T[K][UnionKey]>["__primitiveFields"][]
                  : NonNullable<T[K][UnionKey]> extends TypedSchema
                    ? UnifiedFieldSelection<NonNullable<T[K][UnionKey]>, F, S>[]
                    : never;
              })[]
            : (PrimitiveFields | {
                [UnionKey in keyof Omit<T[K], "__type" | "__primitiveFields">]?: NonNullable<T[K][UnionKey]> extends { __type: "TypedMap"; __primitiveFields: any }
                  ? NonNullable<T[K][UnionKey]>["__primitiveFields"][]
                  : NonNullable<T[K][UnionKey]> extends TypedSchema
                    ? UnifiedFieldSelection<NonNullable<T[K][UnionKey]>, F, S>[]
                    : never;
              })[]
            : NonNullable<T[K]> extends TypedSchema
              ? UnifiedFieldSelection<NonNullable<T[K]>, F, S>[]
              : never;
};

// Main type: Use explicit base case detection to prevent infinite recursion
export type UnifiedFieldSelection<
  T extends TypedSchema,
  F extends boolean = true,
  S extends boolean = true,
> =
  HasComplexFields<T> extends false
    ? LeafFieldSelection<T> // Base case: only primitives, no recursion
    : LeafFieldSelection<T> | ComplexFieldSelection<T, F, S>; // Recursive case

// Infers the result value of one selected member inside a TypedMap:
// Relationship-wrapped members (embedded resources) recurse through the
// wrapped resource; plain TypedSchema members (nested TypedMaps) recurse
// directly. The Selection guard satisfies InferResult's constraint.
export type InferTypedMapMemberValue<M, Selection> = M extends {
  __type: "Relationship";
  __resource: infer Resource;
}
  ? NonNullable<Resource> extends TypedSchema
    ? Selection extends UnifiedFieldSelection<NonNullable<Resource>>[] | undefined
      ? M extends { __array: true }
        ? null extends Resource
          ? Array<InferResult<NonNullable<Resource>, Selection>> | null
          : Array<InferResult<NonNullable<Resource>, Selection>>
        : null extends Resource
          ? InferResult<NonNullable<Resource>, Selection> | null
          : InferResult<NonNullable<Resource>, Selection>
      : never
    : never
  : NonNullable<M> extends TypedSchema
    ? Selection extends UnifiedFieldSelection<NonNullable<M>>[] | undefined
      ? null extends M
        ? InferResult<NonNullable<M>, Selection> | null
        : InferResult<NonNullable<M>, Selection>
      : never
    : never;

export type InferFieldValue<
  T extends TypedSchema,
  Field,
> = Field extends T["__primitiveFields"]
  ? Field extends keyof T
    ? { [K in Field]: T[Field] }
    : never
  : Field extends Record<string, any>
    ? {
        [K in keyof Field as Field[K] extends undefined ? never : K]: K extends keyof T
          ? T[K] extends {
              __type: "Relationship";
              __resource: infer Resource;
            }
            ? NonNullable<Resource> extends TypedSchema
              ? Field[K] extends { fields: infer NestedFields }
                ? NestedFields extends UnifiedFieldSelection<NonNullable<Resource>>[]
                  ? Field[K] extends { page: infer Page }
                    ? T[K] extends { __pagination: infer P extends string }
                      ? NestedPageResult<NonNullable<Resource>, NestedFields, P, Page>
                      : never
                    : T[K] extends { __array: true }
                      ? Array<InferResult<NonNullable<Resource>, NestedFields>>
                      : never
                  : never
                : T[K] extends { __array: true }
                  ? null extends Resource
                    ? Array<InferResult<NonNullable<Resource>, Field[K]>> | null
                    : Array<InferResult<NonNullable<Resource>, Field[K]>>
                  : null extends Resource
                    ? InferResult<NonNullable<Resource>, Field[K]> | null
                    : InferResult<NonNullable<Resource>, Field[K]>
            : never
          : T[K] extends {
                __type: "ComplexCalculation";
                __returnType: infer ReturnType;
              }
            ? NonNullable<ReturnType> extends TypedSchema
              ? null extends ReturnType
                ? InferResult<NonNullable<ReturnType>, Field[K]["fields"]> | null
                : InferResult<NonNullable<ReturnType>, Field[K]["fields"]>
              : ReturnType
            : NonNullable<T[K]> extends { __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
              ? NonNullable<T[K]> extends { __array: true }
                ? Field[K] extends any[]
                  ? null extends T[K]
                    ? Array<
                        UnionToIntersection<
                          {
                            [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                              ? E extends TypedMapFields
                                ? E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                                : E extends Record<string, any>
                                  ? {
                                      [NestedKey in keyof E as E[NestedKey] extends undefined ? never : NestedKey]: NestedKey extends keyof NonNullable<T[K]>
                                          ? InferTypedMapMemberValue<NonNullable<T[K]>[NestedKey], E[NestedKey]>
                                        : never;
                                    }
                                  : E extends keyof NonNullable<T[K]>
                                    ? { [P in E]: NonNullable<T[K]>[P] }
                                    : never
                              : never;
                          }[number]
                        >
                      > | null
                    : Array<
                        UnionToIntersection<
                          {
                            [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                              ? E extends TypedMapFields
                                ? E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                                : E extends Record<string, any>
                                  ? {
                                      [NestedKey in keyof E as E[NestedKey] extends undefined ? never : NestedKey]: NestedKey extends keyof NonNullable<T[K]>
                                          ? InferTypedMapMemberValue<NonNullable<T[K]>[NestedKey], E[NestedKey]>
                                        : never;
                                    }
                                  : E extends keyof NonNullable<T[K]>
                                    ? { [P in E]: NonNullable<T[K]>[P] }
                                    : never
                              : never;
                          }[number]
                        >
                      >
                  : never
                : Field[K] extends any[]
                  ? null extends T[K]
                    ? UnionToIntersection<
                        {
                          [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                            ? E extends TypedMapFields
                              ? E extends keyof NonNullable<T[K]>
                                ? { [P in E]: NonNullable<T[K]>[P] }
                                : never
                              : E extends Record<string, any>
                                ? {
                                    [NestedKey in keyof E as E[NestedKey] extends undefined ? never : NestedKey]: NestedKey extends keyof NonNullable<T[K]>
                                        ? InferTypedMapMemberValue<NonNullable<T[K]>[NestedKey], E[NestedKey]>
                                      : never;
                                  }
                                : E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                            : never;
                        }[number]
                      > | null
                    : UnionToIntersection<
                        {
                          [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                            ? E extends TypedMapFields
                              ? E extends keyof T[K]
                                ? { [P in E]: T[K][P] }
                                : never
                              : E extends Record<string, any>
                                ? {
                                    [NestedKey in keyof E as E[NestedKey] extends undefined ? never : NestedKey]: NestedKey extends keyof NonNullable<T[K]>
                                        ? InferTypedMapMemberValue<NonNullable<T[K]>[NestedKey], E[NestedKey]>
                                      : never;
                                  }
                                : E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                            : never;
                        }[number]
                      >
                  : never
              : T[K] extends { __type: "Union"; __primitiveFields: any }
                ? T[K] extends { __array: true }
                  ? Field[K] extends any[]
                    ? null extends T[K]
                      ? Array<InferUnionFieldValue<T[K], Field[K]>> | null
                      : Array<InferUnionFieldValue<T[K], Field[K]>>
                    : never
                  : Field[K] extends any[]
                    ? null extends T[K]
                      ? InferUnionFieldValue<T[K], Field[K]> | null
                      : InferUnionFieldValue<T[K], Field[K]>
                    : never
                  : NonNullable<T[K]> extends TypedSchema
                    ? null extends T[K]
                      ? InferResult<NonNullable<T[K]>, Field[K]> | null
                      : InferResult<NonNullable<T[K]>, Field[K]>
                    : never
          : never;
      }
    : never;

export type InferResult<
  T extends TypedSchema,
  SelectedFields extends UnifiedFieldSelection<T>[] | undefined,
> = SelectedFields extends undefined
  ? {}
  : SelectedFields extends []
  ? {}
  : SelectedFields extends UnifiedFieldSelection<T>[]
  ? UnionToIntersection<
      {
        [K in keyof SelectedFields]: InferFieldValue<T, SelectedFields[K]>;
      }[number]
    >
  : {};

// Pagination conditional types
// Checks if a page configuration object has any pagination parameters.
// A limit-only page (e.g. { limit: 20 } for the first page) also paginates.
export type HasPaginationParams<Page> =
  Page extends { offset: any } ? true :
  Page extends { after: any } ? true :
  Page extends { before: any } ? true :
  Page extends { limit: any } ? true :
  false;

// Infer which pagination type is being used from the page config.
// A limit-only page resolves to keyset — when an action supports both
// strategies, Ash paginates limit-only requests with keyset.
export type InferPaginationType<Page> =
  Page extends { offset: any } ? "offset" :
  Page extends { after: any } | { before: any } ? "keyset" :
  Page extends { limit: any } ? "keyset" :
  never;

// Returns either non-paginated (array) or paginated result based on page params
// For single pagination type support (offset-only or keyset-only)
// @ts-ignore
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export type ConditionalPaginatedResult<
  Page,
  RecordType,
  PaginatedType
> = Page extends undefined
  ? RecordType
  : HasPaginationParams<Page> extends true
    ? PaginatedType
    : RecordType;

// For actions supporting both offset and keyset pagination
// Infers the specific pagination type based on which params were passed
export type ConditionalPaginatedResultMixed<
  Page,
  RecordType,
  OffsetType,
  KeysetType
> = Page extends undefined
  ? RecordType
  : HasPaginationParams<Page> extends true
    ? InferPaginationType<Page> extends "offset"
      ? OffsetType
      : InferPaginationType<Page> extends "keyset"
        ? KeysetType
        : OffsetType | KeysetType  // Fallback to union if can't determine
    : RecordType;

// Nested relationship pagination results — shaped identically to the
// top-level page payloads, but generic over the destination schema.
export type NestedOffsetPageResult<R extends TypedSchema, Fields> = {
  results: Fields extends UnifiedFieldSelection<R>[] ? Array<InferResult<R, Fields>> : never;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
};

export type NestedKeysetPageResult<R extends TypedSchema, Fields> = {
  results: Fields extends UnifiedFieldSelection<R>[] ? Array<InferResult<R, Fields>> : never;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string | null;
  nextPage: string | null;
  count?: number | null;
  type: "keyset";
};

// P is the relationship's __pagination marker; Page is the page input the
// caller actually passed (used to narrow "mixed" to a concrete side).
export type NestedPageResult<R extends TypedSchema, Fields, P extends string, Page> =
  P extends "offset"
    ? NestedOffsetPageResult<R, Fields>
    : P extends "keyset"
      ? NestedKeysetPageResult<R, Fields>
      : InferPaginationType<Page> extends "offset"
        ? NestedOffsetPageResult<R, Fields>
        : InferPaginationType<Page> extends "keyset"
          ? NestedKeysetPageResult<R, Fields>
          : NestedOffsetPageResult<R, Fields> | NestedKeysetPageResult<R, Fields>;

export type SuccessDataFunc<T extends (...args: any[]) => Promise<any>> = Extract<
  Awaited<ReturnType<T>>,
  { success: true }
>["data"];


export type ErrorData<T extends (...args: any[]) => Promise<any>> = Extract<
  Awaited<ReturnType<T>>,
  { success: false }
>["errors"];

/**
 * Represents an error from an unsuccessful RPC call.
 *
 * This type matches the error structure defined in the AshTypescript.Rpc.Error protocol.
 *
 * @example
 * const error: AshRpcError = {
 *   type: "invalid_changes",
 *   message: "Invalid value for field %{field}",
 *   shortMessage: "Invalid changes",
 *   vars: { field: "email" },
 *   fields: ["email"],
 *   path: ["user", "email"],
 *   details: { suggestion: "Provide a valid email address" }
 * }
 *
 * @example
 * // An internal error withholds detail and carries a correlation ID
 * const error: AshRpcError = {
 *   type: "internal_error",
 *   message: "Something went wrong. Unique error id: 4f3c...",
 *   shortMessage: "Internal error",
 *   vars: {},
 *   fields: [],
 *   path: [],
 *   errorId: "4f3c..."
 * }
 */
export type AshRpcError = {
  /** Machine-readable error type (e.g., "invalid_changes", "not_found") */
  type: string;
  /** Full error message (may contain template variables like %{key}) */
  message: string;
  /** Concise version of the message */
  shortMessage: string;
  /** Variables to interpolate into the message template */
  vars: Record<string, any>;
  /** List of affected field names (for field-level errors) */
  fields: string[];
  /** Path to the error location in the data structure */
  path: string[];
  /** Optional map with extra details (e.g., suggestions, hints) */
  details?: Record<string, any>;
  /**
   * Correlation ID for an error whose details were withheld. Present on
   * internal errors, where the full exception is written to the server log
   * under this same ID — surface it so a user can quote it to support.
   */
  errorId?: string;
}

/**
 * Represents the result of a validation RPC call.
 *
 * All validation actions return this same structure, indicating either
 * successful validation or a list of validation errors.
 *
 * @example
 * // Successful validation
 * const result: ValidationResult = { success: true };
 *
 * // Failed validation
 * const result: ValidationResult = {
 *   success: false,
 *   errors: [
 *     {
 *       type: "required",
 *       message: "is required",
 *       shortMessage: "Required field",
 *       vars: { field: "email" },
 *       fields: ["email"],
 *       path: []
 *     }
 *   ]
 * };
 */
export type ValidationResult =
  | { success: true }
  | { success: false; errors: AshRpcError[]; };




