defmodule Longx.Git.Ignore do
  @moduledoc """
  The `.gitignore` Longx writes when it initialises git for a project:
  build outputs, dependency trees and caches of the common toolchains. It
  is a starting point the user owns from then on.
  """

  @patterns ~w(
    _build/ deps/ .elixir_ls/ erl_crash.dump
    node_modules/ .next/ .nuxt/ dist/ build/ coverage/ .turbo/ .parcel-cache/
    target/ vendor/ Pods/ DerivedData/ .gradle/ bin/obj/
    __pycache__/ .venv/ venv/ .pytest_cache/ .mypy_cache/ *.pyc
    .cache/ .idea/ .vscode/ .DS_Store Thumbs.db
    *.log *.tmp *.swp
    .env .env.* !.env.example
    .longx/local/
  )

  @spec default() :: String.t()
  def default do
    header = "# Generated by Longx — build outputs, dependencies and caches. Edit freely.\n"
    header <> Enum.join(@patterns, "\n") <> "\n"
  end

  @spec patterns() :: [String.t()]
  def patterns, do: @patterns
end
