// UI copy in one place (zh-CN today; i18n later without touching screens).
export const t = {
  app: "Longx",
  projects: "项目",
  newProject: "新建项目",
  noProjects: "还没有项目",
  noProjectsHint: "一个项目就是一个工作目录，agent 在里面干活。",
  name: "名称",
  rootPath: "目录（绝对路径）",
  description: "描述（可选）",
  create: "创建",
  creating: "创建中…",
  cancel: "取消",
  back: "返回",
  settings: "设置",
  threads: "会话",
  newThread: "新会话",
  noThreads: "还没有会话",
  git: "Git",
  noGit: "这个目录还不是 git 仓库",
  noGitHint: "没有 git，每一轮的改动就没有存档，无法回退到某一轮之前。",
  initGit: "初始化 git",
  initializing: "初始化中…",
  head: "HEAD",
  clean: "工作树干净",
  dirty: (n: number) => `${n} 个文件有改动`,
  lfs: "LFS",
  codex: "Codex 进程",
  stopped: "未启动",
  running: "运行中",
  handshaking: "启动中",
  stop: "停止",
  restart: "重启",
  home: "目录",
  memory: "内存",
  processes: "进程",
  turns: "轮数",
  uptime: "运行时长",
  connectionLost: "连接已断开，正在重连…",
  sandboxUnavailable: "沙箱不可用：agent 的命令会被 codex 拒绝或需要逐条批准。",
  sandboxReason: (r: string) => `原因：${r}`,
  notFound: "没有这个页面",
  lastActivity: "最近活动",
  status: {
    idle: "空闲",
    active: "进行中",
    disconnected: "已断开",
    unrecoverable: "无法恢复",
    archived: "已归档",
  } as Record<string, string>,
  searchThreads: "搜索会话…",
  loadingThreads: "正在加载会话",
  today: "今天",
  yesterday: "昨天",
  earlier: "更早",
  rename: "重命名",
  archive: "归档",
  delete: "删除",
  // welcome / wizard
  welcome: "欢迎",
  openOrCreate: "新建 / 打开项目",
  searchProjects: "搜索项目…",
  noMatch: "没有匹配的项目",
  chooseDirectory: "选择目录",
  chooseDirectoryHint: "选一个目录作为项目根。已经是 git 仓库的目录会标出来。",
  useThisDirectory: "就用这个目录",
  showHidden: "显示隐藏目录",
  typePath: "或直接输入路径",
  go: "前往",
  parent: "上一级",
  emptyDirectory: "这里没有子目录",
  gitRepo: "git 仓库",
  details: "项目信息",
  initGitOption: "初始化 git（推荐：每一轮的改动才有存档）",
  alreadyRepo: "这个目录已经是 git 仓库",
  advanced: "高级",
  sandbox: "沙箱",
  approval: "审批",
  network: "允许联网（workspace-write 沙箱内）",
  sandboxOptions: { read_only: "只读", workspace_write: "可写工作区", danger_full_access: "完全访问（危险）" } as Record<string, string>,
  approvalOptions: { never: "从不询问", on_request: "按需询问", untrusted: "不信任时询问" } as Record<string, string>,
  next: "下一步",
  // frame
  tools: { threads: "会话", git: "Git", process: "进程", files: "文件" } as Record<string, string>,
  pickThread: "选择一个会话，或者开始新的",
  untitledThread: "未命名会话",
  filesPending: "某一轮改了什么，在下一步接入。",
  close: "关闭",
  commandPalette: "命令面板",
  searchEverywhere: "输入项目、会话或命令…",
  noResults: "没有结果",
  actions: "操作",
  // status
  turnRunning: "进行中",
  awaitingApproval: "等待审批",
  codexDown: "codex 已停止",
  codexReady: "codex 就绪",
  // chat
  welcomeChat: "让 agent 在这个项目里干活",
  welcomeChatHint: "描述要做的事；命令、改动和审批都会显示在这里。",
  composerPlaceholder: "输入消息… (Enter 发送，Shift+Enter 换行)",
  send: "发送",
  stopTurn: "停止",
  scrollToBottom: "回到底部",
  copy: "复制",
  more: "更多",
  exportMarkdown: "导出为 Markdown",
  edit: "编辑",
  model: "模型",
  threadModel: "会话当前模型",
  defaultModel: "默认",
  threadNotFound: "找不到这个会话",
  threadDisabled: {
    unrecoverable: "codex 已不认识这个会话，不能再发消息。",
    archived: "这个会话已归档。",
    disconnected: "codex 断开了，正在恢复这个会话…",
  } as Record<string, string>,
  threadError: (reason: string) => `会话加载失败：${reason}`,
  loadingThread: "正在加载会话…",
  timing: { title: "这一轮的耗时", firstToken: "首个输出", total: "总耗时", speed: "速度", items: "条目" },
  stalledFor: (s: number) => `${s} 秒没有新输出`,
  // chat: tools
  approvalNeeded: "需要审批",
  agentAsks: "agent 有问题要问",
  needsAnswer: "等待回答",
  answered: "已回答",
  otherAnswer: "其他…",
  approveCommand: "允许执行这条命令？",
  approveFileChange: "允许修改这些文件？",
  allowOnce: "允许",
  allowSession: "本会话都允许",
  deny: "拒绝",
  declined: "已拒绝",
  runningCommand: "运行中",
  exitCode: (n: number) => `exit ${n}`,
  fileChanges: (n: number) => `${n} 个文件改动`,
  webSearch: "网页搜索",
  searching: "搜索中…",
  readSources: (n: number) => `读了 ${n} 个来源`,
  reasoning: "思考",
  usedTool: "调用工具",
  toolCalls: (n: number) => `${n} 次工具调用`,
  cancelledTool: "已取消",
  toolResult: "结果",
  toolError: "错误",
  // chat: dirty tree
  dirtyTreeTitle: "工作树有未提交的改动",
  dirtyTreeHint: "每一轮从一个提交开始，之后才能回退到这一轮之前。",
  dirtyCommit: "先提交再开始",
  dirtyIgnore: "忽略，直接开始",
  moreFiles: (n: number) => `…还有 ${n} 个`,
  // settings
  settingsSections: { models: "模型与 Provider", tools: "工具", sandbox: "沙箱与权限", appearance: "外观" } as Record<string, string>,
  sectionPending: "这一节在后面的分支接入。",
  theme: "主题",
  themes: { dark: "深色", light: "浅色", system: "跟随系统" } as Record<string, string>,
} as const;
