// English UI copy. Keep this tree aligned with strings.ts; tests check coverage.
export const en = {
  app: "Longx",
  projects: "Projects",
  newProject: "New project",
  noProjects: "No projects yet",
  noProjectsHint: "A project is a working directory where your agent works.",
  name: "Name",
  rootPath: "Directory (absolute path)",
  description: "Description (optional)",
  create: "Create",
  creating: "Creating…",
  cancel: "Cancel",
  back: "Back",
  settings: "Settings",
  toolWindows: "Tool windows",
  workbench: "Workspace",
  switchToTab: "Switch to this tab",
  path: "Path",
  runningJobs: (n: number) => `${n} running`,
  entryActions: (name: string) => `Actions for ${name}`,
  levelFor: (label: string) => `${label} effort`,
  extensionVersionLabel: (version: string) => `Extension ${version}`,
  actionsFor: (name: string) => `Actions for ${name}`,
  threads: "Sessions",
  newThread: "New session",
  noThreads: "No sessions yet",
  git: "Git",
  noGit: "This directory is not a Git repository",
  noGitHint: "Without Git, changes are not saved and you cannot return to an earlier state.",
  initGit: "Initialize Git",
  initializing: "Initializing…",
  head: "HEAD",
  clean: "Working tree clean",
  dirty: (n: number) => `${n} changed file${n === 1 ? "" : "s"}`,
  lfs: "LFS",
  connectionLost: "Connection lost. Reconnecting…",
  connectionUnstable: "The connection keeps dropping. The server may be having trouble (check the Longx logs); reconnecting more slowly.",
  threadUnstable: "Loading this session keeps disconnecting. Retries have stopped; the rest of Longx is unaffected. Check the logs for details.",
  notFound: "Page not found",
  lastActivity: "Last activity",
  status: { idle: "Idle", active: "In progress", disconnected: "Disconnected", unrecoverable: "Unrecoverable", archived: "Archived" },
  searchThreads: "Search sessions…",
  loadingThreads: "Loading sessions",
  today: "Today",
  yesterday: "Yesterday",
  earlier: "Earlier",
  rename: "Rename",
  archive: "Archive",
  delete: "Delete",
  welcome: "Welcome",
  openOrCreate: "Open or create a project",
  searchProjects: "Search projects…",
  runningNow: "In progress",
  sending: "Sending…",
  steerPending: "Queued for the agent's next step",
  sendFailed: (why: string) => `Couldn't send: ${why}`,
  runningStrip: (n: number, waiting: number, finished = 0) =>
    [n > 0 ? `${n} running` : "", waiting > 0 ? `${waiting} waiting for you` : "", finished > 0 ? `${finished} just finished` : ""].filter(Boolean).join(" · "),
  projectJobs: {
    title: "Background jobs",
    chip: (count: number) => `Jobs ${count}`,
    empty: "No background jobs in this project",
    running: "Running",
    completed: "Completed",
    exit: (code: number) => `Exit code ${code}`,
    stopped: "Stopped",
    failed: "Did not finish successfully",
    session: (title: string | null, id: string) => title || `Session ~${id.slice(-6)}`,
    recent: "Recently completed",
  },
  finishedOutcome: { completed: "Completed", failed: "Failed", interrupted: "Stopped" },
  runningTurn: "Running",
  agentsWorking: (names: string[]) => `${names.join(", ")} working`,
  waitingForYou: "Waiting for you",
  noMatch: "No matching projects",
  chooseDirectory: "Choose a directory",
  chooseDirectoryHint: "Choose a directory for the project root. Existing Git repositories are marked.",
  useThisDirectory: "Use this directory",
  showHidden: "Show hidden directories",
  newDirectory: "New directory",
  directoryName: "Directory name",
  typePath: "Or enter a path",
  go: "Go",
  parent: "Parent directory",
  emptyDirectory: "No subdirectories",
  gitRepo: "Git repository",
  details: "Project details",
  initGitOption: "Initialize Git (recommended, to save changes)",
  alreadyRepo: "This directory is already a Git repository",
  queueSend: "Queue message",
  queueHint: "Send after this turn finishes",
  copyApi: "Copy API URL",
  apiCopied: "API URL copied",
  apiCopyFailed: "Couldn't copy the API URL; it is shown below",
  waitingHint: "Message from elsewhere · handled after this turn",
  waitingPaused: "You stopped this turn. These messages will wait until you continue.",
  waitingInsert: "Insert now",
  waitingJob: (name: string) => `Background job ${name}`,
  waitingFrom: "Message",
  waitingMine: "You",
  stoppedByPerson: "You stopped this turn",
  stoppedByWatchdog: "Longx stopped this turn because it made no progress",
  stoppedContinue: "Continue",
  stoppedDiscard: "Discard",
  continueText: "Continue",
  queueInsert: "Insert",
  queueRemove: "Remove",
  agentDefinition: {
    title: "Project agent",
    hint: "Agents run from the description in .longx/: agent.exs records differences from the built-in pipeline; shared/ contains reviewed agents, plugs and knowledge committed to Git; local/ contains machine-specific drafts and is not committed. Longx ships with no roles. When an agent needs a teammate, it declares one in local/agents/; once it works well, promote it to shared/ here.",
    agents: "Available agents",
    agentLayer: { global: "Global", project: "shared", local: "local" },
    localFiles: "Files in local/ (not committed to Git)",
    promote: "Promote to shared",
    promoted: (path: string) => `Moved to ${path}`,
    overrides: "Kernel settings (project overrides)",
    overridesHint: "Leave blank to use the global setting.",
    trust: "Trust and load definitions from .longx/",
    trustHint: "Controls agent.exs and .exs files in shared/ (they run as you inside Longx). Review cloned projects before enabling this. Files in local/ are written by agents on this machine and are always loaded.",
    none: "This project has no .longx/ directory yet; an agent will create one if needed.",
    files: "Files",
    plugs: "Active pipeline",
    errors: "Load errors (also shown to the model)",
    model: "Model specified by the description",
    browser: "Browser",
    browserDefault: "Default alias",
    browserState: {
      online: (name: string) => `${name} (online)`,
      offline: (name: string) => `${name} (offline)`,
      no_default: "No default alias",
      unknown_alias: "This alias is not configured on this Longx instance",
    },
    browserTabs: (n: number) => `Up to ${n} tabs`,
    browserSettings: "Browser settings",
  },
  webSearch: "Web search (Longx searches and reads pages for the agent)",
  next: "Next",
  tools: { threads: "Sessions", git: "Git", agents: "Agents & sessions", files: "Files" },
  home: "Home",
  projectSettingsTab: "Project settings",
  chatHistory: "Chat history",
  chatTab: "Session",
  closeTab: "Close",
  unsavedChanges: "Unsaved changes",
  saveFile: "Save",
  saving: "Saving…",
  editFile: "Edit",
  previewFile: "Preview",
  savedFile: "Saved",
  binaryFile: "Binary file; it cannot be viewed here.",
  truncatedFile: (kb: number) => `File is too large (${kb} KB). Only the first 1 MB is shown; editing is disabled.`,
  fileLoadFailed: (reason: string) => `Couldn't open this file: ${reason}`,
  discardEdits: "Discard changes",
  diffTab: (path: string) => `Changes to ${path}`,
  noDiff: "No changes",
  diffSplit: "Side by side",
  diffUnified: "Unified",
  unchangedLines: "$ unchanged lines",
  binaryDiff: "Binary file; no diff to display.",
  gitChanges: "Changes",
  gitHistory: "History",
  currentBranch: (name: string) => `Current branch: ${name}`,
  detachedHead: "Detached HEAD",
  branches: "Branches",
  filterBranches: "Find a branch…",
  newBranchName: "New branch name",
  createBranch: "Create branch",
  deleteBranch: (name: string) => `Delete branch ${name}`,
  deleteBranchTitle: (name: string) => `Delete branch ${name}?`,
  deleteBranchHint: "Only the local branch is deleted; pushed commits are not lost.",
  switchDirtyTitle: (name: string) => `The working tree has changes before switching to ${name}`,
  switchDirtyHint: "You can stash the changes and restore them after switching back, or switch with the changes. Git will reject the latter if they conflict with the target branch.",
  stashAndSwitch: "Stash and switch",
  switchWithChanges: "Switch with changes",
  stashes: (n: number) => `${n} stash${n === 1 ? "" : "es"}`,
  popStash: "Apply latest stash",
  sync: "Sync",
  fetch: "Fetch",
  pull: (n: number) => (n > 0 ? `Pull ${n} commit${n === 1 ? "" : "s"}` : "Pull"),
  push: (n: number) => (n > 0 ? `Push ${n} commit${n === 1 ? "" : "s"}` : "Push"),
  noRemote: "No remote configured",
  addRemote: "Add remote…",
  editRemote: "Edit remote…",
  remoteTitle: "Remote repository",
  remoteUrl: "URL",
  remoteHint: "SSH (git@github.com:you/repo.git) or HTTPS URL. Authentication uses SSH keys or credentials already available on this machine.",
  syncing: "Syncing…",
  synced: "Synced",
  noChanges: "Working tree clean; nothing to commit.",
  selectAll: "Select all",
  summary: "Summary",
  summaryPlaceholder: "What changed?",
  descriptionOptional: "Description (optional)",
  commitTo: (branch: string) => `Commit to ${branch}`,
  committing: "Committing…",
  committed: "Committed",
  discardSelected: "Discard selected changes",
  discardTitle: (n: number) => `Discard changes to ${n} file${n === 1 ? "" : "s"}?`,
  discardHint: "These changes will be removed from disk and cannot be undone; new files will be deleted.",
  discard: "Discard",
  changedFilesCount: (n: number) => `${n} changed file${n === 1 ? "" : "s"}`,
  noCommits: "No commits yet",
  loadMoreCommits: "Load more commits",
  undoCommit: "Undo last commit",
  undoCommitTitle: "Undo the last commit?",
  undoCommitHint: "The commit will be undone and its changes returned to the working tree. Do not undo commits that have already been pushed.",
  undoCommitAction: "Undo commit",
  commitFiles: (n: number) => `${n} file${n === 1 ? "" : "s"}`,
  merging: "Merge in progress: conflicts need attention",
  mergingHint: "Open each conflicted file, resolve the content between <<<<<<< and >>>>>>>, then commit here. Or abort the merge to return to the previous state.",
  abortMerge: "Abort merge",
  abortMergeTitle: "Abort this merge?",
  abortMergeHint: "The working tree will return to its pre-merge state. Changes made in conflicted files will be lost.",
  closeDirtyTitle: (name: string) => `${name} has unsaved changes`,
  closeDirtyHint: "Closing will discard these changes.",
  closeWithoutSaving: "Close without saving",
  gitStatus: { modified: "Modified", added: "Added", untracked: "Untracked", deleted: "Deleted", renamed: "Renamed", copied: "Copied", unmerged: "Conflict", type_changed: "Type changed", unknown: "?" },
  newFile: "New file",
  newFolder: "New folder",
  uploadFiles: "Upload files",
  downloadFile: "Download",
  uploadedFiles: (count: number) => `Uploaded ${count} file${count === 1 ? "" : "s"}`,
  refresh: "Refresh",
  collapseAll: "Collapse all",
  renameEntry: "Rename",
  deleteEntry: "Delete",
  deleteEntryTitle: (name: string) => `Delete ${name}?`,
  deleteEntryHint: "This removes it from disk. If the project uses Git, committed content can still be recovered from history.",
  deleteFolderHint: "The folder and everything inside it will be deleted.",
  entryName: "Name",
  emptyFolder: "Empty folder",
  filesLoadFailed: (reason: string) => `Couldn't read this directory: ${reason}`,
  filterFiles: "Filter by filename…",
  watchOff: "File watching is not running. Changes on disk will not appear automatically; refresh to update.",
  watchPartial: "Some directories could not be watched (often due to the system inotify limit). Refresh to see changes there.",
  noFilesMatch: "No matching files",
  pickThread: "Choose a session or start a new one",
  untitledThread: "Untitled session",
  close: "Close",
  done: "Done",
  chatgptLogin: {
    title: "Sign in to ChatGPT",
    hint: "Use your ChatGPT Plus, Pro or Team subscription with Codex models—no API key required. Sign in once; the token refreshes automatically before it expires.",
    deviceTitle: "Enter the device code",
    deviceHint: "Open the page below, enter this code, then return here and wait for sign-in to finish.",
    asking: "Requesting a device code from OpenAI…",
    waiting: "Waiting for you to enter this code on OpenAI…",
    failed: "Sign-in did not complete",
    loggedIn: "Signed in",
    browserTitle: "Or sign in with a browser",
    browserHint: "A new window will open on OpenAI's sign-in page. After signing in, the browser will go to an unreachable localhost:1455 URL. Copy the entire URL and paste it here.",
    useBrowser: "Sign in with a browser instead",
    pasteHint: (uri: string) => `After signing in, the browser will stop at ${uri} (it is expected not to open). Paste the full address here.`,
    pasteLabel: "Address after sign-in",
    completePasted: "Complete sign-in",
  },
  commandPalette: "Command palette",
  searchEverywhere: "Search projects, sessions or commands…",
  noResults: "No results",
  actions: "Actions",
  turnRunning: "Running",
  stopSubagent: "Stop",
  openSubagent: "Open",
  agentsPanel: {
    title: "Subagents",
    fold: "Collapse",
    nobody: "No agents working",
    recentlyDone: "Recently completed",
    workingCount: (n: number) => `${n} working`,
    waitingCount: (n: number) => `${n} waiting for your action`,
  },
  subagentPage: "Open its session →",
  turnWriting: (tool: string, bytes: string) => `Writing arguments for ${tool} (${bytes})`,
  turnRetrying: (why: string) => `Connection interrupted; retrying: ${why}`,
  turnWaitingOn: (model: string) => `Waiting for ${model}`,
  upstreamQuiet: (seconds: number) => `No data from upstream for ${seconds}s`,
  turnCompacting: (bytes: string | null) => (bytes ? `Compacting context (summary ${bytes})` : "Compacting context…"),
  modelFailed: {
    title: (model: string) => `Model ${model} failed repeatedly. This turn has stopped. Choose another model to continue:`,
    pick: "Choose a model",
    go: "Continue with another model",
    continueText: "Continue",
  },
  awaitingAction: "Waiting for your action",
  presentCard: "Card",
  presentDrawing: "Drawing",
  promptUser: "Waiting for your choice",
  promptAnswered: "Choice submitted",
  openedFile: "Opened",
  openedDiff: "Opened changes",
  sentFile: "Shared a file",
  drawing: "Generating an image",
  drewImage: "Generated an image",
  imageFailed: "Image generation failed",
  openedArtifact: "Opened",
  openSurface: "Open",
  download: "Download",
  uncommittedDiff: "Uncommitted changes",
  artifactTab: "Page",
  openLink: "Open link",
  actionDone: "Done",
  welcomeChat: "Put your agent to work in this project",
  welcomeChatHint: "Describe what you need. Commands, changes and anything that needs your attention will appear here.",
  composerPlaceholder: "Message your agent",
  mentionFiles: { back: "Back", empty: "No matching files or sessions", loading: "Searching…", none: "Type a filename or session name", sessionHint: "Recipient · finish here, then send the full result", sessionSearch: "Type a filename or session name", sessionEmpty: "No matching files or on-duty sessions" },
  addAttachment: "Add attachment",
  removeAttachment: "Remove attachment",
  attachmentUnreadable: (name: string) =>
    `Your browser cannot read ${name}. Its location may block browser access (for example, another app's folder on macOS, a network share or a cloud placeholder), or the file may have changed, moved or still be writing. Move it to Downloads or the Desktop and select it again.`,
  attachmentFailed: (name: string, why: string) => `${name}: ${why}`,
  attachmentUnsent: (name: string) =>
    `${name} was not uploaded. Your browser could not read the file (some app folders on macOS, network shares and cloud placeholders block access; it may also have changed, moved or still be writing), or the network disconnected. Move it to Downloads or the Desktop and try again.`,
  dictate: "Dictate",
  stopDictation: "Stop dictation",
  commands: {
    back: "Back",
    empty: "No such command",
    new: "New session",
    compact: "Compact context (summarize earlier conversation)",
    init: "Ask the agent to write an AGENTS.md for this project",
    git: "Open Git tools",
    files: "Open the file tree",
    settings: "Open project settings",
    goal: "Set a goal: the agent keeps working in successive turns until it is complete",
    compacted: "Context compacted",
    needsThread: "Send a message first to create a session",
  },
  initPrompt: "Write an AGENTS.md for this repository in its root directory. First inspect the codebase: its structure, build/test/run commands, conventions and pitfalls. Keep it concise, specific and actionable for future agents working here. If an AGENTS.md already exists, improve it rather than replacing it.",
  send: "Send",
  stopTurn: "Stop",
  scrollToBottom: "Scroll to bottom",
  copy: "Copy",
  more: "More",
  exportMarkdown: "Export as Markdown",
  edit: "Edit",
  model: "Model",
  defaultModel: "Default",
  searchModels: "Search models…",
  noModelFound: "No matching models",
  reasoningLevel: "Reasoning",
  threadNotFound: "Session not found",
  threadDisabled: {
    unrecoverable: "This session cannot be recovered and cannot accept new messages.",
    archived: "This session is archived.",
    disconnected: "Connection lost. Recovering this session…",
  },
  threadError: (reason: string) => `Failed to load session: ${reason}`,
  loadingThread: "Loading session…",
  context: { trigger: "Context usage", full: (p: number) => `${p}% used`, input: "Input", cachedInput: "Cache hit", output: "Output", reasoning: "Reasoning" },
  timing: { title: "Turn duration", model: "Model", level: "Effort", firstToken: "First token", total: "Total", speed: "Speed", items: "Items" },
  stalledFor: (s: number) => `No new output for ${s}s`,
  history: {
    hidden: (turns: number) => `${turns} earlier turn${turns === 1 ? "" : "s"}`,
    partial: (items: number) => `${items} earlier item${items === 1 ? "" : "s"} in this turn`,
    more: (items: number) => `Show ${items} earlier items`,
    all: "Show all",
    loading: "Loading…",
  },
  goal: {
    title: "Goal",
    status: { active: "In progress", paused: "Paused", blocked: "Blocked", usageLimited: "Usage limit reached", budgetLimited: "Budget used up", complete: "Completed" },
    reason: {
      rounds: "Too many turns ran in one round, so work paused for your review. Send a message to continue.",
      budget: "The token budget is exhausted. Increase it or continue.",
    },
    pause: "Pause",
    resume: "Resume",
    edit: "Edit",
    clear: "Clear",
    budget: "Token budget (leave blank for unlimited)",
    objective: "Goal",
    objectiveHint: "The desired end state. The agent starts another turn after each one until the goal is complete, blocked or out of budget.",
    dialogTitle: "Session goal",
    save: "Save",
    tokens: (used: string, budget: string | null) => (budget ? `${used} / ${budget}` : used),
  },
  modelRerouted: (from: string, to: string) => `Model switched: ${from} → ${to}`,
  agentMessageKind: { report: "Report", question: "Question", answer: "Reply" },
  agentMessageCount: (n: number) => `${n} message${n === 1 ? "" : "s"}`,
  asked: "Asked",
  askedFailed: "Could not ask",
  expand: "Expand",
  modelReroutedReason: {},
  agentAsks: "The agent has a question",
  needsAnswer: "Waiting for an answer",
  answered: "Answered",
  otherAnswer: "Other…",
  deny: "Decline",
  declined: "Declined",
  runningCommand: "Running",
  commandCwd: "Directory",
  ranCommand: "Ran a command",
  ranScript: "Ran in the browser",
  runningScript: "Controlling the browser",
  scriptCode: "Code",
  scriptScreenshots: "Screenshots",
  command: "Command",
  commandFailed: "Command failed to start",
  changedFiles: "Changed",
  changingFiles: "Changing",
  searchedWeb: "Searched the web",
  readPage: "Read page",
  readingPage: "Reading",
  pageRead: "Page read",
  foundInPage: "Found on page",
  findingInPage: "Searching page",
  exitCode: (n: number) => `Exit code ${n}`,
  fileChanges: (n: number) => `${n} file change${n === 1 ? "" : "s"}`,
  searching: "Searching…",
  readSources: (n: number) => `Read ${n} source${n === 1 ? "" : "s"}`,
  reasoning: "Reasoning",
  reasoningLive: "Thinking",
  reasoningDone: "Reasoning",
  usedTool: "Used tool",
  toolCalls: (n: number) => `${n} tool call${n === 1 ? "" : "s"}`,
  cancelledTool: "Cancelled",
  toolResult: "Result",
  toolError: "Error",
  compacted: "Context compacted",
  goalRound: (round: number) => `Goal continuation · round ${round}`,
  jobEnded: (name: string) => `Background job ${name} finished`,
  jobStopped: (name: string) => `Background job ${name} was stopped`,
  jobExitCode: (code: number) => `Exit code ${code}`,
  goalRoundUnknown: "Goal continuation",
  subagent: "Subagent",
  subagentWorking: "Subagent working",
  subagentDone: "Subagent completed",
  subagentInterrupted: "Subagent interrupted",
  subagentNeedsAction: "Waiting for your action",
  subagentState: { started: "Started", interacted: "Working", completed: "Completed", interrupted: "Interrupted" },
  noSubagents: "This session has no subagents",
  subagentsTitle: "Subagents",
  subagentsCount: (ready: number, running: number) => (running > 0 ? `${running} running` : `${ready} completed`),
  subagentsHint: "Open a subagent to view its full session in the adjacent tab.",
  directory: {
    title: "Project sessions",
    otherProjects: "Other projects",
    otherEmpty: "No on-duty sessions in other projects. Enable duty or set a handle in the target session first.",
    search: "Search sessions or addresses",
    noMatches: "No matching sessions",
    copyAddress: "Copy full address",
    addressCopied: "Full address copied",
    handoff: "Delegate here",
    handoffHint: "Delegate here adds instructions to your draft. Review the task before sending.",
    handoffDraft: (address: string) => `Call send_message to delegate the following task to session ${JSON.stringify(address)} (use this full address for the to parameter), then pass its reply back to me:`,
    hint: "Across projects, use the full address project:handle (or project:~last-six-ID-characters). Only on-duty sessions can receive tasks from other agents; a handle or active goal also enables duty.",
    onDuty: "On duty",
    onDutyImplied: "Sessions with a handle or goal are always on duty",
    states: { running: "Running", waiting: "Waiting for you", idle: "Idle", asleep: "Asleep", archived: "Archived", unrecoverable: "Unrecoverable" },
    handle: "Handle",
    handlePlaceholder: "For example, main or ops",
    setHandle: "Save",
    clearHandle: "Remove",
    goal: "Goal",
    team: "Team",
    empty: "No sessions yet",
    watchSession: "Scheduled job session",
  },
  projectSettings: "Project",
  threadDefaults: "Defaults for new sessions",
  threadDefaultsHint: "You can temporarily change these beside the composer in any session. These are the defaults for new ones.",
  globalDefaultModel: "Global default model",
  save: "Save",
  saved: "Saved",
  dangerZone: "Danger zone",
  dangerHint: "These actions only affect project records in Longx, never your working directory.",
  archiveProject: "Archive project",
  archiveProjectHint: "The project disappears from the list; its directory and session history are kept.",
  confirmArchive: "Confirm archive",
  deleteProject: "Delete project",
  deleteProjectHint: (name: string) => `Delete this project and its sessions from Longx; files in the working directory will stay untouched. Type "${name}" to confirm.`,
  confirmDelete: "Confirm delete",
  projectDeleted: "Project deleted",
  settingsSections: {
    models: "Models", providers: "Providers", dependencies: "System dependencies", knowledge: "Knowledge", agent: "Agent kernel",
    files: "File watching", credentials: "Credentials", update: "Version & updates", requests: "Request log", watches: "Monitoring & schedules",
    processes: "Processes", browsers: "Browsers", https: "HTTPS", keys: "Keyboard shortcuts", appearance: "Appearance",
  },
  keys: {
    menu: "Quick menu",
    menuHint: "Esc to close · ⌫ to go back",
    idleHint: "Space: quick menu",
    typingHint: "Esc to leave the input",
    tabs: "Tab N",
    help: "All shortcuts",
    helpHint: "Shortcuts are always available. Outside an input, press Space to open the quick menu, then press the indicated keys. Dimmed commands are unavailable right now.",
    customize: "Customize shortcuts",
    common: "Common",
    armed: (title: string) => `Press Esc again: ${title}`,
    noWaiting: "No sessions waiting for you",
    runningThreads: "Running and recently completed sessions",
    noRunning: "No running or recently completed sessions",
    groupRunning: "Running",
    groupFinished: "Recently completed",
    current: "Current",
    threadsHere: "Sessions in this project",
    recentThreads: "Recent sessions",
    running: "Running",
    waiting: "Waiting for you",
    section: "Shortcuts",
    windowApp: "This is an installed app: Longx handles keys such as ⌘W and Ctrl+Tab.",
    windowTab: "This is a browser tab: the browser handles ⌘W and Ctrl+Tab. Shortcuts marked “App” work only when installed as an app.",
    appOnly: "App",
    appOnlyHint: "Unavailable in a browser tab; works when installed as an app",
    record: "Add",
    recording: "Press a new shortcut…",
    recordingHint: "Esc cancels; sequences starting with Space are quick-menu shortcuts. Press Enter to finish.",
    removeKey: (keys: string) => `Remove ${keys}`,
    reset: "Restore default",
    resetAll: "Restore all defaults",
    changed: "Changed",
    search: "Search commands",
    unavailable: "Unavailable now",
    commands: "Commands",
    switchProject: "Switch project",
    switchThread: "Switch session",
    switchTab: "Switch tab",
    findFile: "Find file",
    findFilePlaceholder: "Filename; letters may appear in sequence",
    pickModel: "Change model",
    pickEffort: "Change effort",
    defaultModel: "Default model",
    defaultEffort: "Model default effort",
    renameThread: "Rename session",
    renameLabel: "Session name",
    rename: "Rename",
    renamed: "Renamed",
    archived: "Archived",
    pushed: "Pushed",
    pulled: "Pulled",
    compacted: "Context compacted",
    noPicked: "No matches",
    searching: "Searching…",
  },
  https: {
    hint: "Enable HTTPS for Longx with your own domain. Let's Encrypt issues the certificate using DNS validation: add a TXT record to your domain's DNS and Longx can get a browser-trusted certificate, even on a local network. HTTPS is required for installing the PWA, system notifications and seamless OAuth callbacks. Renewal is checked daily and automatic 30 days before expiry.",
    off: "Disabled",
    noCertificate: "No certificate yet",
    serving: "Enabled",
    expiresIn: (days: number) => (days >= 0 ? `Expires in ${days} days` : `Expired ${-days} days ago`),
    stages: { downloading: "Downloading certificate tool", verifying: "Verifying certificate tool", extracting: "Extracting certificate tool", issuing: "Requesting certificate (DNS validation usually takes a minute or two)" },
    failed: "Issuance failed",
    domains: "Domains",
    domainsHint: "One or more, separated by commas or spaces; for example, lx.example.com.",
    aRecord: (addresses: string) => `Add a DNS A record pointing this name to this machine: ${addresses}`,
    resolvesHere: "Points to this machine",
    fakeIpNote: (local: string) => `This machine's DNS resolves it to ${local}: this is a proxy fake IP (Clash, mihomo, sing-box, etc.), not your A record. The result above came directly from public DNS (223.5.5.5, 119.29.29.29); Longx also uses public DNS to verify the TXT record.`,
    fakeIpClients: "If the computer or phone running your browser also uses this kind of proxy, add these lines to its proxy config so this name resolves to its real address and bypasses the proxy:",
    checkResolvers: "DNS resolvers for checking TXT records",
    checkResolversAuto: (resolvers: string[]) => (resolvers.length > 0 ? `Automatic: ${resolvers.join(", ")} (this machine uses fake-IP DNS)` : "Automatic: this machine's DNS"),
    checkResolversHint: "Enter IP addresses, optionally with ports, separated by commas. If blank and this machine uses fake-IP DNS, public DNS is used instead.",
    propagationCheck: "Verify the TXT record before requesting",
    propagationWait: "Wait instead (seconds)",
    propagationHint: "If DNS queries are blocked, turn this off and wait after adding the record before asking Let's Encrypt to verify it.",
    resolvesElsewhere: (addresses: string) => `Currently resolves to ${addresses}, not this machine`,
    unresolved: "Does not resolve yet",
    provider: "DNS provider",
    providerSearch: "Search providers…",
    providerNone: "Provider not found",
    featured: "Popular",
    allProviders: "All",
    chooseProvider: "Choose the provider hosting your domain's DNS",
    credentials: "Credentials",
    credentialsHint: "Create a token or sub-account with DNS-only access. It is encrypted when saved and will not be shown again.",
    keepStored: "Configured; leave blank to keep current value",
    clearStored: "Clear",
    cleared: "Will be cleared when saved",
    more: "More options",
    additional: "Additional provider options",
    directory: "Certificate authority",
    directories: { letsencrypt: "Let's Encrypt", "letsencrypt-staging": "Let's Encrypt staging (not browser-trusted; for testing)" },
    email: "Email (optional; for Let's Encrypt expiry notices)",
    port: "HTTPS port",
    portHint: (http: number | null) => `Runs alongside the HTTP port${http ? ` (${http})` : ""}; port 443 requires extra permission.`,
    redirect: "Redirect HTTP pages to HTTPS",
    redirectHint: (http: number | null) => `This page is excluded: if the domain stops resolving, you can still visit Settings → HTTPS over HTTP${http ? ` (port ${http})` : ""} to change or disable it.`,
    saveAndIssue: "Save and request certificate",
    save: "Save",
    saved: "Saved",
    renew: "Renew now",
    disable: "Disable HTTPS",
    disableTitle: "Disable HTTPS?",
    disableHint: "HTTPS will stop working immediately. The certificate and settings are kept, so you can re-enable it without requesting another certificate.",
    disableConfirm: "Confirm disable",
    tool: (version: string, installed: boolean) => `Certificate tool longx-cert ${version}${installed ? "" : " (downloaded automatically on first request, about 19 MB)"}`,
  },
  browsers: {
    hint: "Agents control your browser through the Longx browser bridge (a Chrome extension): open pages, inspect accessibility trees, click, type, take screenshots and view the console. The extension on your computer connects to Longx. Allow connections, name browsers and assign aliases here. To use one in a project, add plug Browser, browser: \"alias\" to its description.",
    extension: "Chrome extension",
    extensionVersion: (v: string) => `Version ${v}`,
    extensionNotBuilt: "This Longx build does not include the extension (mix assets.build)",
    needsChrome: (v: string) => `Requires Chrome / Edge ${v}+`,
    download: "Download extension",
    steps: (origin: string) => [
      "Download the ZIP and extract it to a permanent folder.",
      "Open chrome://extensions, enable Developer mode, choose “Load unpacked” and select that folder.",
      `Click the extension icon, enter this Longx address (${origin || "http://…"}), then click Connect.`,
      "Return here and click Allow under “Waiting for approval”. It will reconnect automatically next time.",
    ],
    pending: "Waiting for approval",
    pendingHint: "These browsers have the extension installed and are waiting for your approval. Do not approve browsers you do not recognize.",
    allow: "Allow",
    reject: "Reject",
    paired: "Connected browsers",
    none: "No browsers connected yet.",
    name: "Name",
    online: "Online",
    offline: "Offline",
    revoked: "Revoked",
    aliasesOf: "Aliases",
    revoke: "Revoke",
    revokeTitle: (name: string) => `Revoke access for “${name}”?`,
    revokeHint: "Its token will immediately stop working and the extension will disconnect. If it reconnects, it will appear under “Waiting for approval”.",
    revokeConfirm: "Confirm revoke",
    maxTabs: "Tab limit",
    inUse: "In use:",
    tabCount: (n: number) => `${n} tab${n === 1 ? "" : "s"}`,
    noTabs: "No sessions are using it right now.",
    aliases: "Aliases",
    aliasesHint: "Project descriptions use aliases (plug Browser, browser: \"qa-chrome\"). An alias can point to multiple browsers; the first online one is used. The default alias is used when a project says only plug Browser.",
    aliasEmpty: "(no browser)",
    default: "Default",
    noAliases: "No aliases yet.",
    aliasName: "Alias",
    saveAlias: "Save alias",
  },
  fileRules: {
    hint: "While a project is open, Longx watches its files so the file tree, Git view and agent description stay in sync with disk. Watching stops when all project pages close. These rules decide which paths are ignored: ignored directories are not watched, are dimmed in the tree and are skipped by @ search.",
    layers: "Rules use gitignore syntax and override earlier layers: built-in → here → project settings → .gitignore → always watch → .longxignore at the project root (highest priority; !target/reports/ can bring back a directory ignored by .gitignore).",
    ignore: "Ignore",
    watch: "Always watch",
    placeholder: { ignore: "logs/\n*.tmp", watch: "generated/api/" },
    hints: { ignore: "One gitignore-style rule per line; lines starting with # are comments.", watch: "Paths to watch even when ignored by .gitignore (for example, agent descriptions in .longx/)." },
    builtin: "Built in:",
    save: "Save rules",
    project: "File watching rules",
    projectHint: "Applies only to this project and overrides global rules. The project-root .longxignore has higher priority and is committed with the code.",
  },
  processes: {
    hint: "Commands currently running for agents: which session, which subagent and for how long. Stop a stuck backtest or unwanted loop here—the whole process tree is killed, and the model is told you stopped it. Refreshes every 2 seconds.",
    none: "No commands are running.",
    noSession: "(no session)",
    openSession: "Open session",
    runningFor: (d: string) => `Running for ${d}`,
    end: "Stop",
    confirmTitle: "Stop this command?",
    confirmHint: "The command and all its child processes will be killed; partial results will not be saved. The model will be told what happened and will not automatically rerun it.",
    confirm: "Confirm stop",
    ended: "Stopped",
  },
  credentialsPage: {
    hint: "API keys and OAuth2 tokens used by agents are encrypted here. Agents know only credential names; Longx sends requests on their behalf, only to allowed hosts, and redacts credential values from responses. OAuth2 tokens refresh automatically before expiry.",
    redirectHint: "The callback URL (redirect URI) registered with the OAuth2 provider. Providers accept only HTTPS or 127.0.0.1: use the external HTTPS address when available, otherwise Longx's loopback address. If your browser is on another machine, paste the address back after signing in:",
    none: "No credentials yet.",
    addApiKey: "Add API key",
    addOauth2: "Add OAuth2",
    kind: { api_key: "API key", oauth2: "OAuth2" },
    status: { ready: "Ready", expired: "Expired", needs_login: "Sign-in required", error: "Error" },
    hosts: "Allowed hosts",
    expires: (at: string) => `Expires ${at}`,
    login: "Sign in",
    loginStarted: "Sign-in opened in a new window. This page will update when it is complete.",
    loginStartedLoopback: "Sign-in opened in a new window. If the browser ends at an unreachable 127.0.0.1 address, paste that address here to finish.",
    pasteHint: (uri: string) => `After sign-in, the browser will open ${uri}. It completes automatically when the browser is on this machine; otherwise paste the full address here.`,
    pasteLabel: "Address after sign-in",
    completeLogin: "Complete sign-in",
    loggedIn: "Signed in",
    refresh: "Refresh now",
    refreshed: "Refreshed",
    delete: "Delete",
    deleteConfirm: (name: string) => `Delete credential “${name}”? Tools using it will stop working.`,
    created: "Credential saved",
    updated: "Updated",
    edit: "Edit",
    editTitle: (name: string) => `Edit credential ${name}`,
    keepSecret: "Leave blank to keep the current value",
    clearClientSecret: "Clear existing client secret (public client; Longx registers it at sign-in)",
    clientByRegistration: "Registered by Longx at sign-in",
    name: "Name",
    nameHint: "Short lowercase name (coros, github…). Agents use it to refer to this credential.",
    label: "Description",
    hostsField: "Hosts this credential may be sent to",
    hostsHint: "One hostname per line, such as api.example.com. Requests are sent only to these hosts.",
    header: "Header",
    scheme: "Scheme",
    schemeHint: "Bearer (default); leave blank to send the raw value",
    secret: "API key / token",
    authorizeUrl: "Authorization URL",
    tokenUrl: "Token URL",
    registrationUrl: "Dynamic client registration URL (optional, RFC 7591)",
    registrationHint: "Often provided by MCP servers. When set, Client ID is not needed; Longx registers itself.",
    scopes: "Scopes (space-separated)",
    clientId: "Client ID",
    clientSecret: "Client secret (leave blank for public clients)",
    pkce: "PKCE",
    save: "Save",
    cancel: "Cancel",
  },
  updatePage: {
    version: (v: string) => `Longx ${v}`,
    hint: "Check GitHub Releases (mjason/longx) for updates. Download, verify and replace the application, then restart the service. Data is untouched; a database snapshot is saved to backups first.",
    notInstalled: "This instance was not installed with install.sh (RELEASE_ROOT is missing). You can check for updates but cannot upgrade here.",
    inContainer: "This instance runs in Docker. Upgrade with docker compose pull && docker compose up -d; data in the /data volume is untouched.",
    neverChecked: "Never checked",
    checkedAt: (at: string) => `Checked ${at}`,
    upToDate: "Already up to date",
    latest: (v: string) => `New version available: ${v}`,
    notes: "Release notes",
    check: "Check for updates",
    checking: "Checking…",
    upgrade: (v: string) => `Upgrade to ${v} and restart`,
    confirmTitle: (from: string, to: string) => `Upgrade from ${from} to ${to}?`,
    confirmHint: "The application will be downloaded, verified and replaced before the service restarts. Running sessions will be interrupted; this page reloads when the new version is ready. Roll back with: sh install.sh --rollback.",
    confirm: "Upgrade and restart",
    stages: { downloading: "Downloading…", verifying: "Verifying…", installing: "Installing…", restarting: "Restarting; waiting for the new version…" },
    installedManual: "Installed; waiting for a manual restart",
    failed: "Upgrade failed:",
    token: "GitHub token",
    tokenHint: "Optional. Anonymous GitHub API access is limited to 60 requests per hour. A token with public_repo read access removes the limit. It is encrypted on the server; this page shows only whether one is set.",
    tokenSet: "Set",
    tokenUnset: "Not set",
    saveToken: "Save token",
    clearToken: "Clear token",
    tokenSaved: "Token saved",
    tokenCleared: "Token cleared",
    newVersion: (v: string) => `New version ${v}`,
  },
  agentKernel: {
    hint: "Team-wide agent kernel settings: how deeply agents can delegate, how many can run at once, how long idle agents stay alive, and the default model for child agents. Project settings can override these values.",
    maxDepth: "Maximum delegation depth",
    maxDepthHint: "The primary agent is depth 0. Agents at the limit cannot delegate further.",
    maxChildren: "Maximum concurrent subagents",
    idleMinutes: "Exit after this many idle minutes",
    idleMinutesHint: "A message wakes the agent from its saved state in milliseconds.",
    modelRetries: "Model retries",
    modelRetriesHint: "5xx responses, disconnects, interrupted streams and timeouts each count as a failure. When retries run out, the next model in the effort/alias chain takes over; if none is available, the turn stops so you can choose another model.",
    memoryFloorPercent: "Minimum available memory (%)",
    memoryFloorPercentHint: "If available memory drops below this percentage, stop every running command and tell the model why. This is the only way to protect memory the GPU driver may reclaim. 0 disables the limit.",
    commandOomPriority: "OOM kill priority for commands",
    commandOomPriorityHint: "0–1000; higher values make the kernel's OOM killer choose the process sooner. This lets agent commands be killed before the browser, desktop or Longx itself. Linux only.",
    commandShell: "Shell for commands",
    commandShellAuto: "Automatic (system default)",
    commandShellHint: "Used by exec_command and start_job. Automatic mode uses the shell of the user who started Longx.",
    commandShellManualWarning: "A manually selected shell reads its own login/interactive configuration; it does not inherit PATH or environment variables from another shell. For example, credentials exported only in .zshrc will not be available in bash. Make sure the selected shell has the required PATH and variables; do not copy credentials into shared environment files.",
    extraPath: "Additional PATH directories",
    extraPathHint: "One directory per line, prepended to command PATH. Includes the built-in web_fetch browser by default; edit, clear or restore defaults.",
    extraPathReset: "Restore defaults",
    childModel: "Default model for subagents",
    childModelHint: "Used when the role description does not specify a model; a model in the description takes precedence.",
    inherit: "Inherit",
    sameAsThread: "Same as the primary agent",
    effortAuto: "Model default effort",
    save: "Save",
    saved: "Saved",
    publicUrl: "Public URL",
    publicUrlHint: (effective: string) => `Used for third-party sign-in callbacks (<URL>/callback/…). Leave blank to use LONGX_PUBLIC_URL (set it in compose for containers), then the address used by your browser. Currently active: ${effective}. OAuth providers accept only HTTPS or 127.0.0.1 callbacks: HTTPS returns directly to Longx; otherwise Longx uses its loopback address, which you may need to paste back when your browser is on another machine.`,
    publicUrlSaved: "Saved",
    browserTitle: "Built-in browser (obscura)",
    browserHint: "The web_fetch tool uses this browser to render pages. It is not bundled with Longx: it downloads to the data directory the first time it is needed, or you can download it here in advance. If your container image includes obscura, set LONGX_OBSCURA to its binary path to skip the download.",
    browserUnavailable: "No obscura build is available for this platform; web_fetch is unavailable.",
    browserNotInstalled: (version: string) => `Not downloaded (obscura ${version}, about 60 MB).`,
    browserInstalled: (path: string) => `Installed: ${path}`,
    browserEnv: (path: string, version: string | null) => `Set by LONGX_OBSCURA${version ? ` (obscura ${version})` : ""}: ${path}`,
    browserUpgradable: (from: string | null, to: string) => `Upgrade to ${to}${from ? ` (currently ${from})` : ""}, about 60 MB.`,
    browserUpgrade: "Upgrade",
    browserFailed: (error: string) => `Download failed: ${error}`,
    browserDownload: "Download",
    browserRetry: "Retry",
    browserStages: { idle: "", downloading: "Downloading", verifying: "Verifying", extracting: "Extracting", installed: "", failed: "" },
    browserStrip: (percent: number | null) => (percent === null ? "Downloading browser" : `Downloading browser ${percent}%`),
    privateNetwork: "Allow access to private / local network addresses",
    privateNetworkHint: "By default, addresses such as 127.0.0.1 and 192.168.x.x are blocked (SSRF protection). In fake-IP network environments where a VPN resolves all domains to private addresses, pages will not open unless this is enabled. Obscura provides only this all-or-nothing setting.",
  },
  dependenciesPage: {
    hint: "Agents rely on these command-line tools in the shell (search, file lookup, diffs and GitHub). Longx checks for them but does not install them. Install missing tools with the command below, then check again.",
    missing: (n: number) => `${n} missing dependenc${n === 1 ? "y" : "ies"}`,
    allFound: "All dependencies found",
    recheck: "Check again",
    installHint: (os: string) => (os === "darwin" ? "Install on macOS with Homebrew:" : os === "windows" ? "Install on Windows with winget:" : "Install on Debian / Ubuntu with apt (use your distribution's package manager otherwise):"),
    versionUnknown: "Version unknown",
    notFound: "Not installed",
  },
  knowledgePage: {
    hint: "Agent knowledge is stored in Markdown files grouped by topic (<topic>/<name>.md). Files with always: true are included in every prompt; others appear as a one-line topic index and are read when needed. This is your global knowledge, shared by all projects; it is the only global layer—there are no global agents, plugs or skills. When Git is available, each save is a commit; otherwise it is just a file. Project knowledge lives in .longx/shared/knowledge/ (committed) and .longx/local/knowledge/ (machine-local, where agents write by default). Shipped Longx knowledge is read-only.",
    global: "My global knowledge",
    shipped: "Shipped with Longx",
    none: "No global knowledge yet. Agents can add useful facts about you here, or you can write your own.",
    always: "Include every turn",
    create: "New",
    newPath: "Filename",
    newPathHint: "topic/name; .md is added automatically, for example tools/deploy (every note belongs to a topic)",
    needsTopic: "Use the format topic/name",
    template: (name: string) => `---\ntitle: ${name}\nsummary: When to read this note\ntags: []\nalways: false\n---\n\n`,
    save: "Save",
    remove: "Delete",
    confirmRemove: (path: string) => `Delete ${path}?`,
    saved: "Saved",
    removed: "Deleted",
    close: "Close",
    readOnly: "Shipped knowledge is read-only",
  },
  ai: {
    providers: "Providers",
    providersHint: "Where models come from: service URLs, keys, each model's context window and reasoning efforts. Change the default model and effort on the Models page.",
    addProvider: "Add provider",
    editProvider: "Edit provider",
    deleteProvider: "Delete provider",
    deleteProviderTitle: (name: string) => `Delete ${name}?`,
    deleteProviderHint: "Its models will be deleted too. The provider containing the default model cannot be deleted.",
    name: "Name",
    slug: "Slug",
    slugHint: "Lowercase letters, numbers and hyphens; use this in sessions and descriptions to refer to the model.",
    baseUrl: "Base URL",
    apiKey: "API key",
    apiKeySet: "Key configured",
    apiKeyMissing: "Key not configured",
    loginSet: "Signed in",
    loginMissing: "Not signed in",
    loginExpired: "Sign-in expired",
    loginChatGpt: "Sign in to ChatGPT",
    presetLoginHint: "This template does not need an API key. Add it, then sign in to your ChatGPT account.",
    keepKey: "Leave blank to keep current value",
    kind: "Type",
    kinds: { openai: "OpenAI", openai_compatible: "OpenAI-compatible" },
    kindHint: "Only OpenAI can read its encrypted reasoning. Choose “OpenAI-compatible” for other services.",
    hostedSearch: "Built-in web search (web_search tool)",
    promptCacheKeyHint: "Send the session ID as prompt_cache_key so the service can cache the shared prompt prefix. This is an OpenAI option also used by Codex CLI. Automatic sends it to OpenAI but not compatible services; enable it manually if another service supports it.",
    promptCacheKeyOptions: { auto: "Automatic (by type)", on: "Send", off: "Do not send" },
    timeout: "Request timeout (seconds)",
    idleTimeout: "Stream idle timeout (seconds)",
    idleTimeoutHint: "After a response starts, retry if the upstream sends no data for this long (Codex default: 300 seconds).",
    concurrency: "Concurrency limit",
    unlimited: "Unlimited",
    lastError: "Latest error",
    lastChecked: (at: string) => `Last checked ${at}`,
    models: "Models",
    addModel: "Add model",
    discover: "Fetch models from API",
    discoverTitle: (name: string) => `Models from ${name}`,
    discoverHint: "Fetch the model list using the OpenAI GET /models convention. Select the models to add. Context windows and reasoning efforts are filled in when provided (for example, by OpenRouter); otherwise defaults are used and can be edited later.",
    discoverFilter: "Filter",
    discoverLoading: "Fetching model list…",
    discoverEmpty: "The API did not return any models that are not already added",
    discoverAdd: (n: number) => `Add ${n}`,
    discoverAdded: (n: number) => `Added ${n} model${n === 1 ? "" : "s"}`,
    editModel: "Edit model",
    deleteModel: "Delete model",
    deleteModelTitle: (name: string) => `Delete model ${name}?`,
    deleteModelHint: "Sessions using this model will not be able to use it on their next turn. The default model cannot be deleted.",
    upstreamId: "Model ID",
    upstreamIdHint: "The model field sent to the provider, for example deepseek-flash",
    contextWindow: "Context window",
    contextWindowHint: "Token count used by the kernel to compact context",
    reasoningLevels: "Reasoning efforts",
    reasoningLevelsHint: "Effort levels provided by the model, shown in order in the composer model menu. If none is selected, no effort is sent. Add unlisted efforts in the last field.",
    customLevel: "Custom effort",
    customLevelPlaceholder: "Effort name",
    addLevel: "Add",
    reasoningEffort: "Default effort",
    reasoningEffortHint: "Leave blank to let the model decide",
    reasoningEffortFree: "Reasoning effort",
    reasoningEffortFreeHint: "Any value accepted by the model; leave blank to omit",
    reasoningSummary: "Reasoning summary",
    hostedWebSearch: "Web search",
    hostedWebSearchOptions: { provider: "Use provider setting", hosted: "Built into the model (run by provider)", longx: "Search via Longx (Tavily)" },
    hostedWebSearchHint: "Built-in search uses the provider's web_search tool. Some models under the same provider do not support it (such as Kimi, MiniMax and GLM-5 on Bailian); choose “Search via Longx” for those.",
    imageGeneration: "Image generation",
    imageGenerationHint: "Expose the provider's image_generation tool to the model. It can create images when asked; images are saved as project attachments and shown in chat. Only OpenAI Responses API (including ChatGPT subscriptions) supports this; enabling it for other providers will fail.",
    advanced: "Advanced",
    chooseTemplate: "Add from template",
    chooseTemplateHint: "API URL, context window and reasoning efforts are prefilled; you only need an API key.",
    custom: "Custom",
    customHint: "Enter the API URL and model yourself",
    presetInstalled: "Added",
    presetTitle: (name: string) => `Add ${name}`,
    presetMoreTitle: (name: string) => `Add models from the ${name} template`,
    presetKeyHint: (env: string) => `You can also provide this with the ${env} environment variable`,
    getKey: "Get API key",
    presetDocs: "Setup guide",
    presetModels: "Models to add",
    presetAllInstalled: "All models in this template are already added",
    defaultModel: "Default model",
    keepDefault: "Keep current default",
    addFromPreset: "Add models from template",
    add: "Add",
    image: "Image",
    levels: "Efforts",
    reasoningSummaries: { auto: "Automatic (OpenAI decides the length)", concise: "Concise", detailed: "Detailed", none: "No summary" },
    reasoningSummaryHint: "Useful only for models that hide their reasoning, such as OpenAI: ask them to include a summary alongside the answer and show it under Reasoning. DeepSeek, Bailian, Spark and others expose reasoning directly and ignore this setting. “—” means automatic.",
    verbosity: "Answer detail",
    verbosities: { low: "Concise", medium: "Medium", high: "Detailed" },
    verbosityHint: "OpenAI text.verbosity controls answer length; reasoning effort controls how much the model thinks. Only GPT-5 models use it. Codex sends “Concise” by default for gpt-5.x; DeepSeek and Bailian accept but ignore it. “—” omits the setting.",
    maxOutputTokens: "Maximum output tokens",
    default: "Default",
    makeDefault: "Set as fallback model",
    defaultModelHint: "Used for new sessions, projects without a model and subagents. Model tiers (plus / pro / ultra) are recommended: change the model mapped to a tier when switching providers, without changing sessions or role descriptions. You can also choose an alias or a specific model.",
    defaultModelTiers: "Tiers",
    defaultModelAliases: "Aliases",
    defaultModelModels: "Specific models",
    defaultModelBase: "Fallback model",
    defaultModelNow: (slug: string, level?: string | null) => `Current: ${slug}${level ? ` · ${level}` : ""}`,
    defaultModelUnresolved: "No usable model is configured",
    defaultModelSaved: "Default model saved",
    check: "Test",
    checkOk: (ms: number) => `Model available (${ms} ms)`,
    checkFailed: (error: string) => `Test failed: ${error}`,
    noModels: "No models yet",
    aliases: "Aliases",
    modelsHint: "Choose models and reasoning efforts for new sessions, projects and subagents. Use plus / pro / ultra or an alias in sessions and descriptions; change the mapping here when switching providers.",
    tiers: "Tiers",
    tiersHint: "Each tier maps to a model and its reasoning effort. Fallbacks are tried in order when a model is unavailable (quota exhausted, key rejected or upstream down), each with its own effort. Unmapped tiers use the fallback model.",
    aliasesOnlyHint: "Team-defined names work like tiers.",
    addFallback: "＋ Fallback",
    fallbacks: "Fallbacks",
    addFallbackLabel: (name: string) => `Add a fallback model for ${name}`,
    removeFallback: (name: string, slug: string) => `Remove fallback ${slug} from ${name}`,
    fallbackLevel: (name: string, slug: string) => `Reasoning effort for ${name}'s fallback ${slug}`,
    fallbackModel: "Fallback",
    fallbackHint: (slug: string) => `${slug}: used only when no model is mapped to the tier.`,
    searchOwn: "Built-in search",
    searchOurs: "Search via Longx",
    searchOursLong: "Search via Longx",
    searchCardHint: "How web search works when enabled for a session. Models use one of two methods; search switches along with fallback models.",
    searchOwnHint: "The provider searches on its own service (for example, OpenAI, Bailian Qwen, DeepSeek-v4 and GLM-5.2). Configure it on the provider's model page.",
    searchOursHint: "Other models use Longx's web_search tool, which requires a search-service key.",
    searchNoModels: "None",
    searchKeyNeeded: "No key configured; these models cannot search yet",
    providerModels: (n: number) => `${n} model${n === 1 ? "" : "s"}`,
    usedBy: (names: string) => `Used by ${names}`,
    levelsCount: (n: number) => `${n} reasoning effort${n === 1 ? "" : "s"}`,
    aliasesHint: "Use a tier or alias instead of a specific model in descriptions, subagents and sessions. Change the mapping here when switching providers; no .longx files need changes. Each name is a chain: the first model is used, then fallbacks if it is unavailable (quota exhausted, key rejected or upstream down). Unmapped tiers use the default model.",
    aliasPrimary: "Primary model",
    aliasFallback: (n: number) => `Fallback ${n}`,
    aliasNone: "(unmapped: default model)",
    followTier: (level: string) => `Follow tier · ${level}`,
    followTierDefault: "Follow tier",
    aliasLevel: (slot: string) => `Reasoning effort for ${slot}`,
    aliasLevelDefault: "Model default",
    aliasNoFallback: "(none)",
    aliasAdd: "Add alias",
    aliasNamePlaceholder: "Blue Dragon",
    aliasRemove: "Delete",
    aliasSaved: "Saved",
    search: "Web search",
    searchHint: "Models without built-in search use Longx's web_search tool; a search-service key is required.",
    saved: "Saved",
    deleted: "Deleted",
  },
  watches: {
    title: "Monitoring & schedules",
    hint: "Scheduled jobs are script files in the project (.longx/local/watches/<name>.exs), written by you or an agent. Longx checks for due jobs every minute and records their results here. Each script decides what to check and which session to message.",
    projectHint: "Scheduled jobs for this project. Edit the script file directly; enable, test or delete it here. local/ jobs run only on this machine. Promote a job to shared/ to commit it so every trusted team machine runs it.",
    promote: "Promote to shared",
    promoted: (path: string) => `Moved to ${path}`,
    sharedUntrusted: (names: string) => `${names} in shared/watches/ will not run until this project trusts and loads its .longx/ definitions.`,
    none: "No scheduled jobs yet",
    allNone: "No projects have scheduled jobs yet",
    columns: { name: "Name", project: "Project", schedule: "Schedule", state: "State", last: "Last run", next: "Next run", counts: "Runs" },
    kinds: { cron: "Every", once: "Once", webhook: "Webhook" },
    scheduledChip: (count: number) => `Scheduled ${count}`,
    nextDue: (date: string) => `Next run: ${date}`,
    inspectScript: "View script to be run",
    scriptLoading: "Reading script…",
    scriptUnavailable: "Script content is temporarily unavailable",
    states: { running: "Running", on: "Enabled", by_person: "Disabled", load_error: "Could not load", budget: "Paused: quota exhausted", expired: "Ended", done: "Completed" },
    runningFor: (s: string) => `Running ${s}`,
    lastRun: (when: string, ms: number) => `${when} (${ms} ms)`,
    neverRan: "Never run",
    counts: (runs: number, sends: number) => `Ran ${runs} times · sent ${sends} messages`,
    sentTo: (to: string) => `Recently sent to ${to}`,
    dryRun: "Test run",
    dryRunTitle: (name: string) => `Test run: ${name}`,
    dryRunHint: "Run the script once now without actually sending messages.",
    dryRunOk: "Script finished successfully",
    dryRunFailed: "Script failed",
    wouldSend: "Messages that would be sent",
    logged: "Output",
    nothingSent: "No messages would be sent",
    enable: "Enable",
    disable: "Disable",
    remove: "Delete",
    removeConfirm: (name: string) => `Delete scheduled job ${name} and its script file?`,
    webhook: "Trigger URL",
    file: "File",
    layer: { local: "This machine", project: "Shared" },
    openProject: "Open project",
  },
  sentry: {
    title: "Error reporting (Sentry)",
    hint: "Add a Sentry project DSN to report request exceptions, process crashes, server-side failures and failed turns for troubleshooting. Clear the DSN to stop reporting. The DSN is encrypted at rest.",
    on: "Enabled",
    off: "Disabled",
    current: "Current",
    environment: "Environment",
    release: "Version",
    placeholder: "https://<key>@<host>/<project>",
    save: "Save",
    saved: "Error reporting enabled",
    cleared: "Error reporting stopped",
    clear: "Clear and stop",
    test: "Send test event",
    testOk: (id: string) => `Sent; event ${id}`,
    testFailed: (why: string) => `Send failed: ${why}`,
  },
  faults: {
    title: "Recent server-side faults",
    hint: "Issues caught by Longx, such as data that could not be encoded as JSON and was replaced with an error frame or sanitized. Kept in memory and cleared on restart; details are in the Longx logs.",
    none: "No recent faults",
    strip: (n: number) => `${n} server-side fault${n === 1 ? "" : "s"}`,
  },
  requestsPage: {
    hint: (keep: number) => `The gateway's ${keep} most recent model requests: model, reasoning effort and tools requested by the kernel, and the result. Use this to check whether UI selections were actually sent. Kept in memory and cleared on restart.`,
    empty: "No requests yet",
    refresh: "Refresh",
    columns: { at: "Time", model: "Model", effort: "Reasoning effort", kind: "Type", status: "Result", duration: "Duration", details: "Details" },
    reasoning: "Reasoning effort",
    noEffort: "Not specified",
    details: "Details",
    thread: "Session",
    turn: "Turn",
    tools: "Tools",
    input: (items: number, chars: number) => `Input: ${items} items · ${chars} characters`,
    instructions: (chars: number) => `Instructions: ${chars} characters`,
    maxOutput: (n: number) => `max_output_tokens ${n}`,
    noTools: "No tools",
  },
  pwa: {
    device: "This device",
    deviceHint: "These preferences are stored only on this device (this browser).",
    spaceMenu: "Spacebar quick menu",
    spaceMenuHint: "Outside an input, press Space to open the quick menu and follow the key hints. Esc leaves the input; SPC ? shows all shortcuts. Disabled on phones.",
    reasoningOpen: "Expand reasoning by default",
    reasoningOpenHint: "Show model reasoning expanded by default (toggle with SPC T r).",
    notifications: "System notifications",
    notificationsHint: "When the page is in the background or unfocused, show a system notification for requests waiting on you and turns that complete or fail. Keep the page (or installed app) open.",
    notificationsNeedHttps: "System notifications require HTTPS (Settings → HTTPS) or localhost on this machine.",
    notificationsDenied: "The browser denied notification permission. Allow it in site settings before enabling notifications.",
    notificationsOn: "System notifications enabled",
    offlineCache: "Offline cache",
    offlineCacheHint: "Store UI files on this device for faster loading. After upgrades, the first page and diff load without another download; the last page can also open temporarily when the server is unreachable.",
    offlineCacheNeedsHttps: "Offline cache requires HTTPS (Settings → HTTPS) or localhost on this machine.",
    offlineShell: "The server is temporarily unavailable. Showing this device's cached page; it will refresh when the connection returns.",
  },
  theme: "Theme",
  themes: { dark: "Dark", light: "Light", system: "System" },
  core: {
    keyGroups: {
      a: "Chat", t: "Sessions", b: "Tabs", f: "Files", g: "Git", w: "Tool windows",
      p: "Projects", j: "Jump to", T: "Toggles", m: "Current page",
    },
    keyCommands: {
      "ai.focus": "Chat with the AI",
      "palette.open": "Command palette",
      "help.keys": "All keyboard shortcuts",
      "settings.open": "Settings",
      "turn.stop": "Stop this turn",
      "turn.continue": "Continue",
      "turn.discard": "Discard this turn",
      "thread.new": "New session",
      "thread.compact": "Compact context",
      "goal.open": "Goal",
      "model.pick": "Change model",
      "effort.pick": "Change effort",
      "waiting.release": "Insert a waiting message now",
      "ask.open": "Answer a pending request",
      "thread.switch": "Switch session",
      "thread.last": "Return to the previous session",
      "thread.next": "Next session",
      "thread.prev": "Previous session",
      "thread.waiting": "Next session waiting for you",
      "thread.running": "Running and recently completed sessions",
      "thread.rename": "Rename session",
      "thread.archive": "Archive session",
      "subagents.open": "Subagents",
      "tab.switch": "Switch tabs",
      "tab.close": "Close tab",
      "tab.reopen": "Reopen last closed tab",
      "tab.next": "Next tab",
      "tab.prev": "Previous tab",
      "tab.last": "Last tab",
      "tab.recent": "Switch to the most recently used tab",
      "tab.recentBack": "Switch to the least recently used tab",
      "tab.chat": "Return to chat",
      "tab.goto.1": "Tab 1", "tab.goto.2": "Tab 2", "tab.goto.3": "Tab 3",
      "tab.goto.4": "Tab 4", "tab.goto.5": "Tab 5", "tab.goto.6": "Tab 6",
      "tab.goto.7": "Tab 7", "tab.goto.8": "Tab 8", "tab.goto.9": "Tab 9",
      "file.find": "Find file",
      "files.open": "File tree",
      "file.save": "Save file",
      "file.reveal": "Reveal in file tree",
      "git.open": "Open Git",
      "git.commit": "Commit",
      "git.push": "Push",
      "git.pull": "Pull",
      "git.history": "History",
      "git.branches": "Branches",
      "tool.threads": "Sessions window",
      "tool.git": "Toggle Git window",
      "tool.agents": "Agents window",
      "tool.files": "Files window",
      "tool.toggle": "Show / hide sidebar",
      "agents.panel": "Agents panel",
      "project.switch": "Switch project",
      "project.settings": "Project settings",
      "project.new": "New project",
      "jump.bottom": "Latest message",
      "jump.ask": "Requests waiting for you",
      "jump.error": "Recent errors",
      "toggle.theme": "Dark / light theme",
      "toggle.reasoning": "Expand reasoning by default",
      "editor.preview": "Preview / edit",
      "diff.next": "Next change",
      "diff.prev": "Previous change",
    },
    keyErrors: {
      ime: "This key is used by your input method (for switching input methods or Chinese/English punctuation). Choose another.",
      conflict: (command: string) => `Already assigned to “${command}”`,
    },
    format: {
      never: "Never",
      justNow: "Just now",
      seconds: (n: number) => `${n}s`,
      minutesAgo: (n: number) => `${n}m ago`,
      hoursAgo: (n: number) => `${n}h ago`,
      daysAgo: (n: number) => `${n}d ago`,
      elapsedSeconds: (n: number) => `${n} sec`,
      elapsedMinutes: (n: number) => `${n} min`,
      elapsedHours: (hours: number, minutes: number) => minutes ? `${hours} h ${minutes} min` : `${hours} h`,
    },
    attachment: {
      saved: "(The file is stored at this server path. Read or extract it when needed.)",
      uploadFailed: (status: number) => `Upload failed (${status})`,
      notUploaded: (name: string) => `Attachment ${name} was not uploaded successfully`,
    },
    dnsProviders: {
      tencentcloud: "Tencent Cloud DNSPod",
      alidns: "Alibaba Cloud DNS",
      huaweicloud: "Huawei Cloud DNS",
      cloudflare: "Cloudflare",
      dnsupdate: "Custom DNS (RFC 2136)",
      exec: "Custom script",
    },
  },
} as const;

type DeepPartial<T> = T extends (...args: never[]) => unknown
  ? T
  : T extends object
    ? { [K in keyof T]?: DeepPartial<T[K]> }
    : T;

export type EnglishUiStrings = DeepPartial<typeof en>;
