// UI copy in one place (zh-CN today; i18n later without touching screens).
export const t = {
  app: "Longx",
  projects: "项目",
  newProject: "新建项目",
  noProjects: "还没有项目",
  noProjectsHint: "一个项目就是一个工作目录，agent 在里面干活。",
  name: "名称",
  rootPath: "目录（绝对路径）",
  description: "描述（可选）",
  create: "创建",
  creating: "创建中…",
  cancel: "取消",
  back: "返回",
  settings: "设置",
  threads: "会话",
  newThread: "新会话",
  noThreads: "还没有会话",
  git: "Git",
  noGit: "这个目录还不是 git 仓库",
  noGitHint: "没有 git，每一轮的改动就没有存档，无法回退到某一轮之前。",
  initGit: "初始化 git",
  initializing: "初始化中…",
  head: "HEAD",
  clean: "工作树干净",
  dirty: (n: number) => `${n} 个文件有改动`,
  lfs: "LFS",
  connectionLost: "连接已断开，正在重连…",
  connectionUnstable: "连接反复断开，可能是服务端故障（看 Longx 的日志）；正在放慢重连。",
  threadUnstable: "这个会话的视图加载会让连接断开，已停止重试；其余部分不受影响。看 Longx 的日志找原因。",
  notFound: "没有这个页面",
  lastActivity: "最近活动",
  status: {
    idle: "空闲",
    active: "进行中",
    disconnected: "已断开",
    unrecoverable: "无法恢复",
    archived: "已归档",
  } as Record<string, string>,
  searchThreads: "搜索会话…",
  loadingThreads: "正在加载会话",
  today: "今天",
  yesterday: "昨天",
  earlier: "更早",
  rename: "重命名",
  archive: "归档",
  delete: "删除",
  // welcome / wizard
  welcome: "欢迎",
  openOrCreate: "新建 / 打开项目",
  searchProjects: "搜索项目…",
  runningNow: "正在进行",
  runningTurn: "进行中",
  agentsWorking: (names: string[]) => `${names.join("、")} 工作中`,
  waitingForYou: "等待你",
  noMatch: "没有匹配的项目",
  chooseDirectory: "选择目录",
  chooseDirectoryHint: "选一个目录作为项目根。已经是 git 仓库的目录会标出来。",
  useThisDirectory: "就用这个目录",
  showHidden: "显示隐藏目录",
  newDirectory: "新建目录",
  directoryName: "目录名",
  typePath: "或直接输入路径",
  go: "前往",
  parent: "上一级",
  emptyDirectory: "这里没有子目录",
  gitRepo: "git 仓库",
  details: "项目信息",
  initGitOption: "初始化 git（推荐：每一轮的改动才有存档）",
  alreadyRepo: "这个目录已经是 git 仓库",
  /** the composer's queue while a turn runs */
  queueSend: "加入队列",
  queueHint: "这一轮结束后发送",
  queueInsert: "插入",
  queueRemove: "取消",
  agentDefinition: {
    title: "这个项目的 agent",
    hint: "agent 按 .longx/ 里的描述运行：agent.exs 记录和出厂管道的差异；shared/ 里的 agents、plugs、knowledge 进 git，是审过的；local/ 是本机和 agent 自己的草稿，不进 git。Longx 不带任何角色：需要派人时 agent 自己在 local/agents/ 里声明一个，用顺了你在这里提升到 shared。",
    agents: "可派出的 agent",
    agentLayer: { global: "全局", project: "shared", local: "local" } as Record<string, string>,
    localFiles: "local/ 里的文件（未进 git）",
    promote: "提升到 shared",
    promoted: (path: string) => `已移到 ${path}`,
    overrides: "内核参数（本项目覆盖）",
    overridesHint: "留空即沿用全局设置。",
    trust: "信任并加载 .longx/ 里的定义",
    trustHint: "管 agent.exs 和 shared/ 里的 .exs（它们会以你的身份在 Longx 里执行）。clone 来的项目先看一眼再打开。local/ 是本机 agent 自己写的，不用开关，一直加载。",
    none: "这个项目还没有 .longx/ 目录；agent 需要时会自己建。",
    files: "文件",
    plugs: "生效的管道",
    errors: "加载失败（会以提示告诉模型）",
    model: "描述指定的模型",
  },
  webSearch: "网页搜索（搜索 + 读网页，由 Longx 代为访问）",
  next: "下一步",
  // frame
  tools: {
    threads: "会话",
    git: "Git",
    agents: "Agent 与会话",
    files: "文件",
  } as Record<string, string>,
  // workbench (the centre: chat + files + diffs as tabs)
  chatTab: "会话",
  closeTab: "关闭",
  unsavedChanges: "有未保存的改动",
  saveFile: "保存",
  saving: "保存中…",
  editFile: "编辑",
  previewFile: "预览",
  savedFile: "已保存",
  binaryFile: "二进制文件，不能在这里查看。",
  truncatedFile: (kb: number) =>
    `文件太大（${kb} KB），只显示开头的 1 MB，不能编辑。`,
  fileLoadFailed: (reason: string) => `打不开这个文件：${reason}`,
  discardEdits: "放弃改动",
  diffTab: (path: string) => `${path} 的改动`,
  noDiff: "没有改动",
  diffSplit: "并排",
  diffUnified: "单栏",
  unchangedLines: "$ 行未改动",
  binaryDiff: "二进制文件，没有可显示的差异。",
  // git tool (GitHub Desktop's shape)
  gitChanges: "更改",
  gitHistory: "历史",
  currentBranch: (name: string) => `当前分支 ${name}`,
  detachedHead: "游离的 HEAD",
  branches: "分支",
  filterBranches: "查找分支…",
  newBranchName: "新分支名",
  createBranch: "新建分支",
  deleteBranch: (name: string) => `删除分支 ${name}`,
  deleteBranchTitle: (name: string) => `删除分支 ${name}？`,
  deleteBranchHint: "只删本地的这条分支；已经推送过的提交不会丢。",
  switchDirtyTitle: (name: string) => `切换到 ${name} 前，工作树里有改动`,
  switchDirtyHint:
    "可以先把改动暂存起来（切回来后再取出），或者带着改动一起切过去——后者在改动和目标分支冲突时会被 git 拒绝。",
  stashAndSwitch: "暂存并切换",
  switchWithChanges: "带着改动切换",
  stashes: (n: number) => `${n} 个暂存`,
  popStash: "取出最近的暂存",
  sync: "同步",
  fetch: "获取更新",
  pull: (n: number) => (n > 0 ? `拉取 ${n} 个提交` : "拉取"),
  push: (n: number) => (n > 0 ? `推送 ${n} 个提交` : "推送"),
  noRemote: "还没有远程仓库",
  addRemote: "添加远程仓库…",
  editRemote: "修改远程仓库…",
  remoteTitle: "远程仓库",
  remoteUrl: "地址",
  remoteHint:
    "SSH（git@github.com:you/repo.git）或 HTTPS 地址；认证用这台机器上已有的 SSH 密钥或凭据。",
  syncing: "同步中…",
  synced: "已同步",
  noChanges: "工作树干净，没有要提交的改动。",
  selectAll: "全选",
  summary: "摘要",
  summaryPlaceholder: "这次改了什么",
  descriptionOptional: "描述（可选）",
  commitTo: (branch: string) => `提交到 ${branch}`,
  committing: "提交中…",
  committed: "已提交",
  discardSelected: "丢弃所选改动",
  discardTitle: (n: number) => `丢弃 ${n} 个文件的改动？`,
  discardHint: "改动会从磁盘上消失，没法撤销；新文件会被删掉。",
  discard: "丢弃",
  changedFilesCount: (n: number) => `${n} 个文件有改动`,
  noCommits: "还没有提交",
  loadMoreCommits: "更多提交",
  undoCommit: "撤销上一次提交",
  undoCommitTitle: "撤销上一次提交？",
  undoCommitHint:
    "提交会取消，它的改动回到工作树里（不会丢）。已经推送出去的提交不要撤销。",
  undoCommitAction: "撤销提交",
  commitFiles: (n: number) => `${n} 个文件`,
  merging: "正在合并：有冲突要解决",
  mergingHint:
    "打开冲突的文件，把 <<<<<<< 到 >>>>>>> 之间的内容改成你要的样子，保存后在这里提交；或者放弃这次合并，回到合并前。",
  abortMerge: "放弃合并",
  abortMergeTitle: "放弃这次合并？",
  abortMergeHint: "工作树回到合并开始前的样子，你在冲突文件里做的修改会丢。",
  closeDirtyTitle: (name: string) => `${name} 有未保存的改动`,
  closeDirtyHint: "关闭会丢掉这些改动。",
  closeWithoutSaving: "不保存，关闭",
  gitStatus: {
    modified: "修改",
    added: "新增",
    untracked: "新文件",
    deleted: "删除",
    renamed: "重命名",
    copied: "复制",
    unmerged: "冲突",
    type_changed: "类型变化",
    unknown: "?",
  } as Record<string, string>,
  // files tool
  newFile: "新建文件",
  newFolder: "新建文件夹",
  refresh: "刷新",
  collapseAll: "全部折叠",
  renameEntry: "重命名",
  deleteEntry: "删除",
  deleteEntryTitle: (name: string) => `删除 ${name}？`,
  deleteEntryHint:
    "会从磁盘上删掉。如果项目有 git，已提交过的内容还能从历史里找回。",
  deleteFolderHint: "整个文件夹连同里面的所有文件都会删掉。",
  entryName: "名称",
  emptyFolder: "空文件夹",
  filesLoadFailed: (reason: string) => `读不了这个目录：${reason}`,
  filterFiles: "按文件名查找…",
  noFilesMatch: "没有匹配的文件",
  pickThread: "选择一个会话，或者开始新的",
  untitledThread: "未命名会话",
  close: "关闭",
  done: "完成",
  chatgptLogin: {
    title: "登录 ChatGPT",
    hint: "用你的 ChatGPT 订阅（Plus / Pro / Team）跑 Codex 的模型，不用 API Key。登录一次，令牌到期前会自动续。",
    deviceTitle: "输入设备码",
    deviceHint: "打开下面的页面，输入这串码，回到这里等它自动完成。",
    asking: "正在向 OpenAI 要设备码…",
    waiting: "等你在 OpenAI 的页面输入这串码…",
    failed: "登录没有完成",
    loggedIn: "已登录",
    browserTitle: "或者用浏览器登录",
    browserHint: "会在新窗口打开 OpenAI 的登录页；登录后浏览器会跳到一个打不开的 localhost:1455 地址，把那个地址整条复制回来贴在这里。",
    useBrowser: "改用浏览器登录",
    pasteHint: (uri: string) => `登录后浏览器会停在 ${uri}（打不开是正常的），把地址栏里的完整地址贴到这里。`,
    pasteLabel: "登录后的地址",
    completePasted: "完成登录",
  },
  commandPalette: "命令面板",
  searchEverywhere: "输入项目、会话或命令…",
  noResults: "没有结果",
  actions: "操作",
  // status
  turnRunning: "进行中",
  stopSubagent: "停止",
  openSubagent: "打开",
  agentsPanel: {
    title: "子 agent",
    fold: "收起",
    nobody: "没有在工作的",
    recentlyDone: "最近完成",
    workingCount: (n: number) => `${n} 个工作中`,
    waitingCount: (n: number) => `${n} 个等你操作`,
  },
  subagentPage: "到它的页面去对话 →",
  turnWriting: (tool: string, bytes: string) => `正在写 ${tool} 的参数（${bytes}）`,
  turnRetrying: (why: string) => `连接中断，正在重试：${why}`,
  modelFailed: {
    title: (model: string) => `模型 ${model} 连续出错，这一轮停下了。换一个模型继续：`,
    pick: "选择模型",
    go: "换个模型继续",
    continueText: "继续",
  },
  awaitingAction: "等待你操作",
  presentCard: "卡片",
  presentDrawing: "正在绘制",
  promptUser: "等待你选择",
  promptAnswered: "已选择",
  openedFile: "打开了",
  openedDiff: "打开了改动",
  sentFile: "发来了文件",
  drawing: "正在生成图片",
  drewImage: "生成了图片",
  imageFailed: "图片生成失败",
  openedArtifact: "打开了",
  openSurface: "打开",
  download: "下载",
  uncommittedDiff: "未提交的改动",
  artifactTab: "页面",
  openLink: "打开链接",
  actionDone: "已完成",
  // chat
  welcomeChat: "让 agent 在这个项目里干活",
  welcomeChatHint: "描述要做的事；命令、改动和需要你操作的地方都会显示在这里。",
  composerPlaceholder: "随心输入",
  mentionFiles: {
    back: "返回",
    empty: "没有匹配的文件",
    loading: "搜索中…",
    none: "输入文件名",
  },
  addAttachment: "添加附件",
  removeAttachment: "移除附件",
  dictate: "语音输入",
  stopDictation: "停止语音输入",
  commands: {
    back: "返回",
    empty: "没有这个命令",
    new: "新会话",
    compact: "压缩上下文（把前面的对话折叠成摘要）",
    init: "让 agent 为这个项目写一份 AGENTS.md",
    git: "打开 git 工具",
    files: "打开文件树",
    settings: "打开项目设置",
    goal: "设一个目标：agent 会一轮接一轮自己干下去，直到完成",
    compacted: "上下文已压缩",
    needsThread: "先发一条消息，会话才存在",
  },
  initPrompt:
    "请为这个仓库写一份 AGENTS.md（放在项目根目录）。先看一遍代码库：目录结构、构建 / 测试 / 运行的命令、代码风格与约定、需要注意的坑。写得简短、具体、可执行——它是给以后在这个项目里干活的 agent 看的说明。已经有 AGENTS.md 的话，在它的基础上补充和修正，不要推倒重来。",
  send: "发送",
  stopTurn: "停止",
  scrollToBottom: "回到底部",
  copy: "复制",
  more: "更多",
  exportMarkdown: "导出为 Markdown",
  edit: "编辑",
  model: "模型",
  defaultModel: "默认",
  searchModels: "搜索模型…",
  noModelFound: "没有匹配的模型",
  reasoningLevel: "思考",
  threadNotFound: "找不到这个会话",
  threadDisabled: {
    unrecoverable: "这个会话已无法恢复，不能再发消息。",
    archived: "这个会话已归档。",
    disconnected: "连接断开了，正在恢复这个会话…",
  } as Record<string, string>,
  threadError: (reason: string) => `会话加载失败：${reason}`,
  loadingThread: "正在加载会话…",
  context: {
    trigger: "上下文用量",
    full: (p: number) => `已用 ${p}%`,
    input: "输入",
    cachedInput: "缓存命中",
    output: "输出",
    reasoning: "思考",
  },
  timing: {
    title: "这一轮的耗时",
    model: "模型",
    level: "档位",
    firstToken: "首个输出",
    total: "总耗时",
    speed: "速度",
    items: "条目",
  },
  stalledFor: (s: number) => `${s} 秒没有新输出`,
  // chat: goal mode
  goal: {
    title: "目标",
    status: {
      active: "进行中",
      paused: "已暂停",
      blocked: "卡住了",
      usageLimited: "额度用尽",
      budgetLimited: "预算用尽",
      complete: "已完成",
    } as Record<string, string>,
    reason: {
      rounds: "一个回合里连跑了太多轮，停下来等你看一眼；说一句话它就接着跑",
      budget: "token 预算用完了；提高预算或按继续",
    } as Record<string, string>,
    pause: "暂停",
    resume: "继续",
    edit: "编辑",
    clear: "清除",
    budget: "token 预算（留空不限）",
    objective: "目标",
    objectiveHint: "要达成的最终状态。agent 会在每轮结束后自己开下一轮，直到目标完成、卡住或预算用完。",
    dialogTitle: "会话目标",
    save: "保存",
    tokens: (used: string, budget: string | null) => (budget ? `${used} / ${budget}` : used),
  },
  modelRerouted: (from: string, to: string) => `模型已切换：${from} → ${to}`,
  agentMessageFrom: (name: string) => `agent ${name}`,
  asked: "问了",
  askedFailed: "没问到",
  expand: "展开",
  modelReroutedReason: {} as Record<string, string>,
  // chat: tools
  agentAsks: "agent 有问题要问",
  needsAnswer: "等待回答",
  answered: "已回答",
  otherAnswer: "其他…",
  deny: "拒绝",
  declined: "已拒绝",
  runningCommand: "正在运行",
  commandCwd: "目录",
  ranCommand: "运行了",
  command: "命令",
  commandFailed: "命令没有跑起来",
  changedFiles: "修改了",
  changingFiles: "正在修改",
  searchedWeb: "搜索了",
  readPage: "读取了",
  readingPage: "正在读取",
  pageRead: "读取完成",
  foundInPage: "在页面里查找了",
  findingInPage: "正在页面里查找",
  exitCode: (n: number) => `exit ${n}`,
  fileChanges: (n: number) => `${n} 个文件改动`,
  searching: "搜索中…",
  readSources: (n: number) => `读了 ${n} 个来源`,
  reasoning: "思考",
  reasoningLive: "思考中",
  reasoningDone: "思考过程",
  usedTool: "调用工具",
  toolCalls: (n: number) => `${n} 次工具调用`,
  cancelledTool: "已取消",
  toolResult: "结果",
  toolError: "错误",
  // chat: agents
  compacted: "上下文已压缩",
  goalRound: (round: number) => `目标续跑 · 第 ${round} 轮`,
  goalRoundUnknown: "目标续跑",
  subagent: "子 agent",
  subagentWorking: "子 agent 工作中",
  subagentDone: "子 agent 完成",
  subagentInterrupted: "子 agent 已中断",
  subagentNeedsAction: "等待你操作",
  subagentState: {
    started: "已启动",
    interacted: "工作中",
    completed: "完成",
    interrupted: "已中断",
  } as Record<string, string>,
  noSubagents: "这个会话没有派出子 agent",
  subagentsTitle: "子 agent",
  subagentsCount: (ready: number, running: number) =>
    running > 0 ? `${running} 个在跑` : `${ready} 个完成`,
  subagentsHint: "点开一个子 agent，它的完整会话在旁边的标签页里打开。",
  directory: {
    title: "本项目的会话",
    hint: "每个会话都有一个地址：句柄（@名字）或 ~ 加 id 末六位。只有值班中的会话会被别的 agent 和定时任务叫醒；聊完搁下的对话默认不值班。给会话起个句柄、或设了目标，就一直值班。",
    onDuty: "值班",
    onDutyImplied: "有句柄或目标的会话始终值班",
    states: {
      running: "运行中",
      waiting: "等待你操作",
      idle: "空闲",
      asleep: "已休眠",
      archived: "已归档",
      unrecoverable: "不可恢复",
    } as Record<string, string>,
    handle: "句柄",
    handlePlaceholder: "例如 main、ops",
    setHandle: "保存",
    clearHandle: "去掉",
    goal: "目标",
    team: "团队",
    empty: "还没有会话",
    watchSession: "定时任务的会话",
  },
  // project settings
  projectSettings: "项目",
  threadDefaults: "新会话的默认设置",
  threadDefaultsHint: "每个会话可以在输入框旁边临时改；这里是新会话的起点。",
  globalDefaultModel: "全局默认模型",
  save: "保存",
  saved: "已保存",
  dangerZone: "危险操作",
  dangerHint: "这些操作只碰 Longx 里的项目记录，从不碰你的工作目录。",
  archiveProject: "归档项目",
  archiveProjectHint: "项目从列表里消失，它的目录和会话记录都保留。",
  confirmArchive: "确认归档",
  deleteProject: "删除项目",
  deleteProjectHint: (name: string) =>
    `从 Longx 删除这个项目和它的会话记录；工作目录里的文件不会动。输入项目名「${name}」确认。`,
  confirmDelete: "确认删除",
  projectDeleted: "项目已删除",
  // settings
  settingsSections: {
    models: "模型与 Provider",
    dependencies: "系统依赖",
    knowledge: "知识",
    agent: "Agent 内核",
    credentials: "凭证",
    update: "版本与更新",
    requests: "请求记录",
    watches: "监控与定时",
    processes: "进程",
    appearance: "外观",
  } as Record<string, string>,
  processes: {
    hint: "agent 此刻正在跑的命令：哪个会话、哪个子 agent、跑了多久。卡死的回测、没人想要的循环，在这里结束——整棵进程树被杀，模型会被告知是你结束的。每 2 秒刷新。",
    none: "现在没有命令在跑。",
    noSession: "（没有会话）",
    openSession: "打开会话",
    runningFor: (d: string) => `已运行 ${d}`,
    end: "结束",
    confirmTitle: "结束这条命令？",
    confirmHint: "命令和它派出的所有进程都会被杀掉，跑到一半的结果不会保存；模型会收到说明，不会原样重跑。",
    confirm: "确认结束",
    ended: "已结束",
  },
  credentialsPage: {
    hint: "agent 用到的 API Key 和 OAuth2 令牌都放在这里，加密保存。agent 只知道凭证的名字，请求由 Longx 代发：值只发给允许的主机，回来的内容里值会被抹掉；OAuth2 令牌快到期时后台自动刷新。",
    redirectHint: "OAuth2 提供方那边登记的回调地址（redirect URI）。提供方只接受 https 或 127.0.0.1：外部地址是 https 时直接用它，否则用 Longx 自己的回环地址，浏览器不在这台机器上时登录后要把地址粘贴回来：",
    none: "还没有凭证。",
    addApiKey: "添加 API Key",
    addOauth2: "添加 OAuth2",
    kind: { api_key: "API Key", oauth2: "OAuth2" } as Record<string, string>,
    status: { ready: "就绪", expired: "已过期", needs_login: "待登录", error: "出错" } as Record<string, string>,
    hosts: "允许的主机",
    expires: (at: string) => `到期 ${at}`,
    login: "登录",
    loginStarted: "已在新窗口打开登录页，登录完成后这里会自动更新。",
    loginStartedLoopback: "已在新窗口打开登录页。登录后如果浏览器停在打不开的 127.0.0.1 地址，把那个地址粘贴回来完成登录。",
    pasteHint: (uri: string) => `登录后浏览器会跳到 ${uri}——浏览器在这台机器上时自动完成；打不开的话，把地址栏里的完整地址贴到这里。`,
    pasteLabel: "登录后的地址",
    completeLogin: "完成登录",
    loggedIn: "已登录",
    refresh: "立即刷新",
    refreshed: "已刷新",
    delete: "删除",
    deleteConfirm: (name: string) => `删除凭证「${name}」？用它的工具会失效。`,
    created: "凭证已保存",
    updated: "已更新",
    edit: "编辑",
    editTitle: (name: string) => `编辑凭证 ${name}`,
    keepSecret: "留空则保持现在的值",
    clearClientSecret: "清除现有 Client Secret（公开客户端，登录时由 Longx 注册）",
    clientByRegistration: "登录时由 Longx 注册",
    // the forms
    name: "名字",
    nameHint: "小写短名（coros、github…），agent 用它指代这个凭证",
    label: "说明",
    hostsField: "允许发送到的主机",
    hostsHint: "每行一个主机名，如 api.example.com；请求只会发到这些主机",
    header: "请求头",
    scheme: "前缀",
    schemeHint: "Bearer（默认）；留空则直接放原值",
    secret: "API Key / Token",
    authorizeUrl: "授权地址（authorize URL）",
    tokenUrl: "令牌地址（token URL）",
    registrationUrl: "动态注册地址（可选，RFC 7591）",
    registrationHint: "MCP 服务常提供；填了就不用 Client ID，Longx 自己去注册",
    scopes: "Scopes（空格分隔）",
    clientId: "Client ID",
    clientSecret: "Client Secret（公开客户端留空）",
    pkce: "PKCE",
    save: "保存",
    cancel: "取消",
  },
  updatePage: {
    version: (v: string) => `Longx ${v}`,
    hint: "从 GitHub Releases（mjason/longx）检查新版本，点一下就下载、校验、替换程序目录并重启服务。数据目录不动，升级前会先把数据库快照存到 backups。",
    notInstalled: "这个实例不是用 install.sh 安装的（没有 RELEASE_ROOT），只能检查版本，不能在这里升级。",
    inContainer: "这个实例跑在 Docker 镜像里：升级就是换新镜像——docker compose pull && docker compose up -d；数据在 /data 卷里，不动。",
    neverChecked: "还没检查过",
    checkedAt: (at: string) => `${at}检查过`,
    upToDate: "已经是最新版本",
    latest: (v: string) => `有新版本 ${v}`,
    notes: "更新说明",
    check: "检查更新",
    checking: "检查中…",
    upgrade: (v: string) => `升级到 ${v} 并重启`,
    confirmTitle: (from: string, to: string) => `从 ${from} 升级到 ${to}？`,
    confirmHint: "下载、校验通过后替换程序目录并重启服务，正在跑的会话会被打断，页面会在新版本起来后自动刷新。回退：sh install.sh --rollback。",
    confirm: "升级并重启",
    stages: {
      downloading: "正在下载…",
      verifying: "正在校验…",
      installing: "正在安装…",
      restarting: "正在重启，等新版本起来…",
    } as Record<string, string>,
    installedManual: "已安装，等待手动重启",
    failed: "升级失败：",
    token: "GitHub token",
    tokenHint: "可选。匿名访问 GitHub API 每小时限 60 次；填一个 token（只需 public_repo 读权限）就不受限。加密存在服务端，页面上只看得到有没有设置。",
    tokenSet: "已设置",
    tokenUnset: "未设置",
    saveToken: "保存 token",
    clearToken: "清除 token",
    tokenSaved: "token 已保存",
    tokenCleared: "token 已清除",
    newVersion: (v: string) => `新版本 ${v}`,
  },
  agentKernel: {
    hint: "内核的团队参数：agent 能派多深、同时几个、闲多久自己退出，孩子默认跑哪个模型。这些是每个 agent 描述最上面的一层，项目设置里可以覆盖。",
    maxDepth: "派出深度上限",
    maxDepthHint: "主 agent 是 0 层；到了上限的 agent 不能再派。",
    maxChildren: "同时存活的子 agent",
    idleMinutes: "闲置多少分钟后退出",
    idleMinutesHint: "退出后下一条消息会从记录里毫秒级拉起来，不丢状态。",
    modelRetries: "模型出错后重试几次",
    modelRetriesHint: "5xx、连接断开、流中断、超时都算一次；用完后档位/别名里的下一个模型接手，没有下一个就停下来让你换模型继续。",
    commandMemoryPercent: "每条命令的内存上限（%）",
    commandMemoryPercentHint: "0–100，占物理内存的比例，作为命令整棵进程树的地址空间上限（RLIMIT_AS）；超出时分配失败，模型会看到报错自己缩小规模。CUDA 会把整块显存也映射进地址空间，独立显卡的机器要放宽或设 0 关闭。macOS 不生效。",
    memoryFloorPercent: "内存下限（%）",
    memoryFloorPercentHint: "机器可用内存低于这个比例时，杀掉正在运行的所有命令并告诉模型原因。这是唯一能拦住显卡驱动从内存里切走的那部分的办法。0 关闭。",
    commandOomPriority: "命令被 OOM 先杀的优先级",
    commandOomPriorityHint: "0–1000，越大越先被内核的 OOM killer 选中；让 agent 的命令先于浏览器、桌面和 Longx 自己被杀。仅 Linux。",
    childModel: "子 agent 默认模型",
    childModelHint: "角色声明里没写模型时用；写了的以声明为准。",
    inherit: "沿用",
    sameAsThread: "和主 agent 一样",
    effortAuto: "模型默认档位",
    save: "保存",
    saved: "已保存",
    publicUrl: "外部访问地址",
    publicUrlHint: (effective: string) =>
      `第三方登录跳回来时用的地址（回调是 <地址>/callback/…）。留空则用环境变量 LONGX_PUBLIC_URL（容器里在 compose 里设一次），再没有就用你浏览器连上来的地址；现在生效的是 ${effective}。OAuth 提供方只接受 https 或 127.0.0.1 的回调：这里是 https 时登录后直接回到 Longx，否则用 Longx 自己的回环地址、浏览器在别的机器上时要把地址贴回来。`,
    publicUrlSaved: "已保存",
    browserTitle: "内置浏览器（obscura）",
    browserHint: "web_fetch 工具用它渲染网页。不随 Longx 打包：第一次用到时自动下载到数据目录，也可以在这里先下好。容器镜像自带 obscura 时，用环境变量 LONGX_OBSCURA 指向那个二进制，就不会下载。",
    browserUnavailable: "这个平台没有 obscura 的构建，web_fetch 不可用。",
    browserNotInstalled: (version: string) => `尚未下载（obscura ${version}，约 60 MB）。`,
    browserInstalled: (path: string) => `已安装：${path}`,
    browserEnv: (path: string, version: string | null) =>
      `由 LONGX_OBSCURA 指定${version ? `（obscura ${version}）` : ""}：${path}`,
    browserUpgradable: (from: string | null, to: string) =>
      `可升级到 ${to}${from ? `（当前 ${from}）` : ""}，约 60 MB。`,
    browserUpgrade: "升级",
    browserFailed: (error: string) => `下载失败：${error}`,
    browserDownload: "下载",
    browserRetry: "重试",
    browserStages: {
      idle: "",
      downloading: "下载中",
      verifying: "校验中",
      extracting: "解压中",
      installed: "",
      failed: "",
    } as Record<string, string>,
    browserStrip: (percent: number | null) => (percent === null ? "浏览器下载中" : `浏览器下载中 ${percent}%`),
    privateNetwork: "允许访问私网 / 局域网地址",
    privateNetworkHint: "默认拒绝 127.0.0.1、192.168.x.x 这类地址（防 SSRF）。在 fake-ip 的网络环境里（VPN 把所有域名解析到私网地址），不打开这个开关所有页面都打不开；obscura 只有这一个全有全无的开关。",
  },
  dependenciesPage: {
    hint: "agent 在 shell 里干活依赖这些命令行工具（搜索、找文件、看 diff、调 GitHub）。Longx 只检测，不代装：缺的用下面这一行自己装上，再点重新检测。",
    missing: (n: number) => `缺少 ${n} 个依赖`,
    allFound: "依赖齐全",
    recheck: "重新检测",
    installHint: (os: string) => (os === "darwin" ? "macOS 用 Homebrew 装：" : os === "windows" ? "Windows 用 winget 装：" : "Debian / Ubuntu 用 apt 装（其他发行版换成自己的包管理器）："),
    versionUnknown: "版本未知",
    notFound: "未安装",
  },
  knowledgePage: {
    hint: "agent 的知识：markdown 文件，按主题分目录（<主题>/<名字>.md），front matter 里 always: true 的每轮都进 prompt，其余按主题折成一行索引，agent 按需读。这里是你自己的全局知识——全局层面只有它，没有全局的 agent、plug 或技能——对所有项目生效；机器上有 git 时每次保存是一个提交，没有 git 就只是文件。项目的知识在仓库的 .longx/shared/knowledge/（进 git）和 .longx/local/knowledge/（本机，agent 默认写这里）。Longx 出厂的那批只读。",
    global: "我的全局知识",
    shipped: "Longx 出厂",
    none: "还没有全局知识；agent 学到关于你的事会写在这里，你也可以自己写。",
    always: "每轮注入",
    create: "新建",
    newPath: "文件名",
    newPathHint: "主题/名字，.md 会自动加上，如 tools/deploy（每篇必须属于一个主题）",
    needsTopic: "请写成 主题/名字",
    template: (name: string) => `---\ntitle: ${name}\nsummary: 一句话说明什么时候该读它\ntags: []\nalways: false\n---\n\n`,
    save: "保存",
    remove: "删除",
    confirmRemove: (path: string) => `删除 ${path}？`,
    saved: "已保存",
    removed: "已删除",
    close: "关闭",
    readOnly: "出厂知识只读",
  },
  ai: {
    providers: "Provider",
    providersHint:
      "每个 Provider 是一个 OpenAI Responses API 兼容的服务；密钥加密存在服务端，页面上只看得到有没有设置。",
    addProvider: "添加 Provider",
    editProvider: "编辑 Provider",
    deleteProvider: "删除 Provider",
    deleteProviderTitle: (name: string) => `删除 ${name}？`,
    deleteProviderHint:
      "它下面的模型一起删除。默认模型所在的 Provider 不能删。",
    name: "名称",
    slug: "标识",
    slugHint: "小写字母、数字和连字符；会话和描述里用它指模型",
    baseUrl: "Base URL",
    apiKey: "API Key",
    apiKeySet: "已设置密钥",
    apiKeyMissing: "未设置密钥",
    loginSet: "已登录",
    loginMissing: "未登录",
    loginExpired: "登录已过期",
    loginChatGpt: "登录 ChatGPT",
    presetLoginHint: "这个模版不用 API Key：添加后登录你的 ChatGPT 账号即可。",
    keepKey: "留空则不改",
    kind: "类型",
    kinds: { openai: "OpenAI", openai_compatible: "OpenAI 兼容" } as Record<
      string,
      string
    >,
    kindHint: "只有 OpenAI 自己能读回它的加密推理；其它服务选“OpenAI 兼容”",
    hostedSearch: "自带联网搜索（web_search 工具）",
    promptCacheKeyHint: "请求里带上会话 id 作为 prompt_cache_key，让服务端按会话缓存前缀（OpenAI 的参数；Codex CLI 也这么发）。自动 = OpenAI 发、兼容服务不发；别的服务支持的话手动打开。",
    promptCacheKeyOptions: { auto: "自动（按类型）", on: "发送", off: "不发" } as Record<string, string>,
    timeout: "请求超时（秒）",
    concurrency: "并发上限",
    unlimited: "不限",
    lastError: "最近错误",
    lastChecked: (at: string) => `上次检测 ${at}`,
    models: "模型",
    addModel: "添加模型",
    discover: "从接口获取模型",
    discoverTitle: (name: string) => `${name} 提供的模型`,
    discoverHint: "按 OpenAI 的 GET /models 标准向接口要模型列表；勾选要添加的。列表给了上下文窗口和思考档位的（OpenRouter）会一并填好，没给的用默认值，之后可以编辑。",
    discoverFilter: "筛选",
    discoverLoading: "正在向接口要列表…",
    discoverEmpty: "接口没有列出未添加的模型",
    discoverAdd: (n: number) => `添加 ${n} 个`,
    discoverAdded: (n: number) => `添加了 ${n} 个模型`,
    editModel: "编辑模型",
    deleteModel: "删除模型",
    deleteModelTitle: (name: string) => `删除模型 ${name}？`,
    deleteModelHint: "用它的会话下一轮会拿不到模型。默认模型不能删。",
    upstreamId: "模型 ID",
    upstreamIdHint: "发给 Provider 的 model 字段，如 deepseek-flash",
    contextWindow: "上下文窗口",
    contextWindowHint: "token 数；内核按它压缩上下文",
    reasoningLevels: "推理档位",
    reasoningLevelsHint:
      "模型提供的思考强度，按顺序显示在输入栏的模型菜单里；一档不选则不传强度。没列出的档位，在最后的框里填名字添加。",
    customLevel: "自定义档位",
    customLevelPlaceholder: "自定义档位名",
    addLevel: "添加",
    reasoningEffort: "默认档",
    reasoningEffortHint: "不选则不传强度，由模型决定",
    reasoningEffortFree: "推理强度",
    reasoningEffortFreeHint: "模型接受的任意值；留空不传",
    reasoningSummary: "推理摘要",
    hostedWebSearch: "联网搜索",
    hostedWebSearchOptions: {
      provider: "跟 Provider 的设置",
      hosted: "模型自带（provider 服务端执行）",
      longx: "Longx 代搜（Tavily）",
    },
    hostedWebSearchHint: "模型自带的搜索是 provider 在服务端跑的 web_search 工具；同一个 provider 下有的模型不支持（百炼的 kimi、MiniMax、glm-5），那些模型选「Longx 代搜」。",
    imageGeneration: "图片生成",
    imageGenerationHint: "把 provider 服务端的 image_generation 工具交给模型，它在你要求时画图，图存进项目附件并在聊天里显示。仅 OpenAI 的 Responses API（含 ChatGPT 订阅）支持，别的 provider 开了会报错。",
    advanced: "高级",
    // templates
    chooseTemplate: "从模版添加",
    chooseTemplateHint: "接口地址、模型窗口和思考档位都已填好，只差密钥。",
    custom: "自定义",
    customHint: "自己填接口地址和模型",
    presetInstalled: "已添加",
    presetTitle: (name: string) => `添加 ${name}`,
    presetMoreTitle: (name: string) => `从 ${name} 模版添加模型`,
    presetKeyHint: (env: string) => `也可以用环境变量 ${env} 提供`,
    getKey: "获取 API Key",
    presetDocs: "接入文档",
    presetModels: "要添加的模型",
    presetAllInstalled: "模版里的模型都已添加",
    defaultModel: "默认模型",
    keepDefault: "保持现在的默认",
    addFromPreset: "从模版添加模型",
    add: "添加",
    image: "图片",
    levels: "档",
    reasoningSummaries: {
      auto: "自动（由 OpenAI 决定长短）",
      concise: "简短",
      detailed: "详细",
      none: "不要摘要",
    } as Record<string, string>,
    reasoningSummaryHint:
      "只对 OpenAI 这类隐藏推理过程的模型有意义：请它随回答附一段思考摘要，显示在「思考过程」里。DeepSeek、百炼、星火等直接输出思考内容，这一项会被忽略。留「—」等于自动。",
    verbosity: "回答详略",
    verbosities: { low: "简短", medium: "中等", high: "详细" } as Record<string, string>,
    verbosityHint:
      "OpenAI 的 text.verbosity：管回答说多少（推理强度管想多少）。只有 GPT-5 系读它，codex 给 gpt-5.x 默认发「简短」；DeepSeek、百炼会收下但不执行。留「—」不发。",
    maxOutputTokens: "输出上限",
    default: "默认",
    makeDefault: "设为默认",
    defaultModelHint: "新会话、没有指定模型的项目和子 agent 都用它。推荐用档位（plus 普通 / pro 高级 / ultra 旗舰）：换 provider 时只要改档位对应的模型，会话和角色描述都不用动；也可以选别名或具体模型。档位还没对应模型时，落到下面标了「默认」的那个模型。",
    defaultModelTiers: "档位",
    defaultModelAliases: "别名",
    defaultModelModels: "具体模型",
    defaultModelBase: "标「默认」的模型",
    defaultModelNow: (slug: string) => `现在用的是 ${slug}`,
    defaultModelUnresolved: "现在没有能用的模型",
    defaultModelSaved: "默认模型已保存",
    check: "检测",
    checkOk: (ms: number) => `模型可用，${ms} ms`,
    checkFailed: (error: string) => `检测失败：${error}`,
    noModels: "还没有模型",
    aliases: "档位与别名",
    aliasesHint:
      "描述、子 agent、对话框里都可以写档位或别名而不是具体模型：换 provider 时只改这里的映射，.longx 一个字不用动。每个名字是一条链：第一个是用的，后面是它不可用（配额用完、密钥被拒、上游挂了）时的备选。三档没映射时等于默认模型。",
    aliasPrimary: "用的模型",
    aliasFallback: (n: number) => `备选 ${n}`,
    aliasNone: "（未映射：默认模型）",
    aliasNoFallback: "（无）",
    aliasAdd: "添加别名",
    aliasNamePlaceholder: "青龙",
    aliasRemove: "删除",
    aliasSaved: "已保存",
    search: "联网搜索",
    searchHint:
      "没有自带搜索的模型由 Longx 代为搜索（web_search 工具）；需要一个搜索服务的密钥。",
    saved: "已保存",
    deleted: "已删除",
  },
  watches: {
    title: "监控与定时",
    hint: "定时任务是项目里的脚本文件（.longx/local/watches/<名字>.exs），由 agent 或你来写；Longx 每分钟检查一次到期的，跑完把结果记在这里。脚本自己决定检查什么、把消息发给哪个会话。",
    projectHint: "这个项目的定时任务。改脚本直接改文件；这里能开关、试跑、删除。本机（local/）的只在这台机器上跑；提升到 shared/ 就进 git，团队的每台机器打开信任开关后都会跑。",
    promote: "提升到 shared",
    promoted: (path: string) => `已移到 ${path}`,
    sharedUntrusted: (names: string) => `shared/watches/ 里有 ${names}，但这个项目还没打开「信任并加载 .longx/ 里的定义」，它们不会运行。`,
    none: "还没有定时任务",
    allNone: "所有项目都还没有定时任务",
    columns: { name: "名字", project: "项目", schedule: "计划", state: "状态", last: "上次", next: "下次", counts: "次数" },
    kinds: { cron: "每", once: "一次", webhook: "webhook" } as Record<string, string>,
    states: {
      running: "运行中",
      on: "已开启",
      by_person: "已关闭",
      load_error: "无法加载",
      budget: "已暂停：配额用完",
      expired: "已结束",
      done: "已完成",
    } as Record<string, string>,
    runningFor: (s: string) => `运行中 ${s}`,
    lastRun: (when: string, ms: number) => `${when}（${ms} ms）`,
    neverRan: "还没跑过",
    counts: (runs: number, sends: number) => `跑过 ${runs} 次，发过 ${sends} 条`,
    sentTo: (to: string) => `最近发给 ${to}`,
    dryRun: "试跑",
    dryRunTitle: (name: string) => `试跑 ${name}`,
    dryRunHint: "现在跑一次脚本，不会真的发消息。",
    dryRunOk: "脚本正常结束",
    dryRunFailed: "脚本出错",
    wouldSend: "会发出的消息",
    logged: "输出",
    nothingSent: "这次不会发消息",
    enable: "开启",
    disable: "关闭",
    remove: "删除",
    removeConfirm: (name: string) => `删除定时任务 ${name}？会删掉它的脚本文件。`,
    webhook: "触发地址",
    file: "文件",
    layer: { local: "本机", project: "共享" } as Record<string, string>,
    openProject: "打开项目",
  },
  sentry: {
    title: "错误上报（Sentry）",
    hint: "填一个 Sentry 项目的 DSN 就开始收集：请求里的异常、进程崩溃、上面这些服务端故障、失败的轮次都会发过去，方便排查。清掉 DSN 就停止。DSN 加密保存。",
    on: "已开启",
    off: "未开启",
    current: "当前",
    environment: "环境",
    release: "版本",
    placeholder: "https://<key>@<host>/<project>",
    save: "保存",
    saved: "已开启错误上报",
    cleared: "已停止错误上报",
    clear: "清除并停止",
    test: "发送测试事件",
    testOk: (id: string) => `已发出，事件 ${id}`,
    testFailed: (why: string) => `发送失败：${why}`,
  },
  faults: {
    title: "最近的服务端故障",
    hint: "Longx 自己兜住的问题：发给浏览器的数据编不成 JSON（被替换成错误帧或清洗过）等。只在内存里，重启即清；细节在 Longx 的日志里。",
    none: "最近没有",
    strip: (n: number) => `${n} 个服务端故障`,
  },
  requestsPage: {
    hint: (keep: number) => `网关最近 ${keep} 次发给模型的请求：内核实际要了什么模型、思考档位、工具，结果如何。看这里能确认界面上的选择是否真的发出去了。只在内存里，重启即清。`,
    empty: "还没有请求",
    refresh: "刷新",
    columns: { at: "时间", model: "模型", effort: "思考档位", kind: "类型", status: "结果", duration: "耗时", details: "详情" },
    reasoning: "思考档位",
    noEffort: "未指定",
    details: "详情",
    thread: "会话",
    turn: "轮次",
    tools: "工具",
    input: (items: number, chars: number) => `输入 ${items} 项 · ${chars} 字符`,
    instructions: (chars: number) => `指令 ${chars} 字符`,
    maxOutput: (n: number) => `max_output_tokens ${n}`,
    noTools: "没有工具",
  },
  theme: "主题",
  themes: { dark: "深色", light: "浅色", system: "跟随系统" } as Record<
    string,
    string
  >,
} as const;
