defmodule Longx.Codex.HomeTest do
  use Longx.DataCase, async: false

  alias Longx.AI.Gateway.Token
  alias Longx.Codex.Home

  setup do
    Ash.bulk_destroy!(Longx.AI.Model, :destroy, %{}, authorize?: false)
    Ash.bulk_destroy!(Longx.AI.Provider, :destroy, %{}, authorize?: false)
    Ash.bulk_destroy!(Longx.AI.SearchProvider, :destroy, %{}, authorize?: false)

    dir = Path.join(System.tmp_dir!(), "longx-codex-home-#{System.unique_integer([:positive])}")
    on_exit(fn -> File.rm_rf!(dir) end)
    %{dir: dir}
  end

  test "prepare/1 creates the directory and writes a config pointing codex at our gateway", %{
    dir: dir
  } do
    {:ok, home} = Home.prepare(dir: dir, gateway_url: "http://127.0.0.1:4242/ai/v1")

    assert home.dir == dir
    assert File.dir?(dir)
    assert home.config_path == Path.join(dir, "config.toml")

    config = File.read!(home.config_path)
    assert config =~ ~s(model_provider = "longx")
    assert config =~ ~s(model = "longx")
    assert config =~ ~s([model_providers.longx])
    assert config =~ ~s(base_url = "http://127.0.0.1:4242/ai/v1")
    assert config =~ ~s(env_key = "LONGX_GATEWAY_TOKEN")
    assert config =~ ~s(wire_api = "responses")
    assert config =~ ~s(requires_openai_auth = false)
  end

  test "web search is disabled unless a standalone provider is configured", %{dir: dir} do
    {:ok, home} = Home.prepare(dir: dir, gateway_url: "http://127.0.0.1:4242/ai/v1")
    config = File.read!(home.config_path)

    assert config =~ ~s(web_search = "disabled")
    # the provider is always declared capable: threads switch modes per model
    assert config =~ "supports_standalone_web_search = true"
    refute config =~ "[features]\nstandalone_web_search = true"
  end

  test "web_search: :standalone routes codex's web.run tool to our /alpha/search", %{dir: dir} do
    {:ok, home} =
      Home.prepare(dir: dir, gateway_url: "http://127.0.0.1:4242/ai/v1", web_search: :standalone)

    config = File.read!(home.config_path)

    refute config =~ ~s(web_search = "disabled")
    assert config =~ "supports_standalone_web_search = true"
    assert config =~ "[features]\nstandalone_web_search = true"
  end

  test "web_search: :hosted lets codex use the upstream's own web_search tool", %{dir: dir} do
    {:ok, home} =
      Home.prepare(dir: dir, gateway_url: "http://127.0.0.1:4242/ai/v1", web_search: :hosted)

    config = File.read!(home.config_path)

    assert config =~ ~s(web_search = "live")
    refute config =~ "[features]\nstandalone_web_search = true"
  end

  test "without an explicit option the mode comes from Longx.AI.web_search_mode/0", %{dir: dir} do
    # nothing configured in the (sandboxed, cleared) DB → disabled
    {:ok, home} = Home.prepare(dir: dir, gateway_url: "http://127.0.0.1:4242/ai/v1")
    assert File.read!(home.config_path) =~ ~s(web_search = "disabled")
  end

  test "the env hands codex the home and the current gateway token", %{dir: dir} do
    {:ok, home} = Home.prepare(dir: dir, gateway_url: "http://127.0.0.1:4242/ai/v1")

    assert {"CODEX_HOME", dir} in home.env
    assert {"LONGX_GATEWAY_TOKEN", Token.current()} in home.env
  end

  test "prepare/1 rewrites a stale config every time", %{dir: dir} do
    File.mkdir_p!(dir)
    File.write!(Path.join(dir, "config.toml"), ~s(model_provider = "openai"\n))

    {:ok, home} = Home.prepare(dir: dir, gateway_url: "http://127.0.0.1:4242/ai/v1")
    config = File.read!(home.config_path)

    assert config =~ ~s(model_provider = "longx")
    refute config =~ ~s("openai")
  end

  test "the default gateway url is loopback on the endpoint's port" do
    port = LongxWeb.Endpoint.config(:http)[:port]
    assert Home.default_gateway_url() == "http://127.0.0.1:#{port}/ai/v1"
  end

  test "config.toml has a comment saying it is generated", %{dir: dir} do
    {:ok, home} = Home.prepare(dir: dir, gateway_url: "http://127.0.0.1:4242/ai/v1")
    assert File.read!(home.config_path) |> String.starts_with?("# Generated by Longx")
  end
end
