defmodule Longx.Codex.HomeTest do
  use ExUnit.Case, async: true

  alias Longx.AI.Gateway.Token
  alias Longx.Codex.Home

  setup do
    dir = Path.join(System.tmp_dir!(), "longx-codex-home-#{System.unique_integer([:positive])}")
    on_exit(fn -> File.rm_rf!(dir) end)
    %{dir: dir}
  end

  test "prepare/1 creates the directory and writes a config pointing codex at our gateway", %{
    dir: dir
  } do
    {:ok, home} = Home.prepare(dir: dir, gateway_url: "http://127.0.0.1:4242/ai/v1")

    assert home.dir == dir
    assert File.dir?(dir)
    assert home.config_path == Path.join(dir, "config.toml")

    config = File.read!(home.config_path)
    assert config =~ ~s(model_provider = "longx")
    assert config =~ ~s(model = "longx")
    assert config =~ ~s([model_providers.longx])
    assert config =~ ~s(base_url = "http://127.0.0.1:4242/ai/v1")
    assert config =~ ~s(env_key = "LONGX_GATEWAY_TOKEN")
    assert config =~ ~s(wire_api = "responses")
    assert config =~ ~s(requires_openai_auth = false)
  end

  test "the env hands codex the home and the current gateway token", %{dir: dir} do
    {:ok, home} = Home.prepare(dir: dir, gateway_url: "http://127.0.0.1:4242/ai/v1")

    assert {"CODEX_HOME", dir} in home.env
    assert {"LONGX_GATEWAY_TOKEN", Token.current()} in home.env
  end

  test "prepare/1 rewrites a stale config every time", %{dir: dir} do
    File.mkdir_p!(dir)
    File.write!(Path.join(dir, "config.toml"), ~s(model_provider = "openai"\n))

    {:ok, home} = Home.prepare(dir: dir, gateway_url: "http://127.0.0.1:4242/ai/v1")
    config = File.read!(home.config_path)

    assert config =~ ~s(model_provider = "longx")
    refute config =~ ~s("openai")
  end

  test "the default gateway url is loopback on the endpoint's port" do
    port = LongxWeb.Endpoint.config(:http)[:port]
    assert Home.default_gateway_url() == "http://127.0.0.1:#{port}/ai/v1"
  end

  test "config.toml has a comment saying it is generated", %{dir: dir} do
    {:ok, home} = Home.prepare(dir: dir, gateway_url: "http://127.0.0.1:4242/ai/v1")
    assert File.read!(home.config_path) |> String.starts_with?("# Generated by Longx")
  end
end
