import Config

# Fixed dev key for Longx.Vault (encrypts provider API keys). Never reuse in prod.
config :longx, Longx.Vault,
  ciphers: [
    default:
      {Cloak.Ciphers.AES.GCM,
       tag: "AES.GCM.V1", key: Base.decode64!("bG9uZ3gtZGV2LXZhdWx0LWtleS0wMTIzNDU2Nzg5YWI=")}
  ]

config :ash, policies: [show_policy_breakdowns?: true]

# Configure your database
config :longx, Longx.Repo,
  database: Path.expand("../longx_dev.db", __DIR__),
  pool_size: 5,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :longx, LongxWeb.Endpoint,
  # Bind to all interfaces on port 7788 so the dev server is reachable over the LAN.
  # See CLAUDE.md "Dev server" — do not change these.
  http: [ip: {0, 0, 0, 0}, port: 7788],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "4A38gUAMiHRAiBew4wUwtlx6FxYqEtZmR+vcsR2BeC+CNN6opnyxRfDLgI/nTFNu",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:longx, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:longx, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Where the bundled codex-app-server keeps its state (see Longx.Codex.Home)
config :longx, Longx.Codex.Home, dir: Path.expand("../data/codex_home", __DIR__)

# Enable dev routes for dashboard and mailbox
config :longx, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
