import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
# Static asset digests come from Vite's manifest (LongxWeb.Vite), not phx.digest.

# No force_ssl: a self-hosted Longx serves plain http on the LAN; TLS is a
# reverse proxy's job (config/runtime.exs builds links with PHX_HOST).

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

config :sentry, environment_name: :production
