defmodule Longx.Repo.Migrations.AddThreadHandle do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:project_threads) do
      add :handle, :text
    end

    create unique_index(:project_threads, [:project_id, :handle],
             name: "project_threads_unique_handle_in_project_index"
           )
  end

  def down do
    drop_if_exists unique_index(:project_threads, [:project_id, :handle],
                     name: "project_threads_unique_handle_in_project_index"
                   )

    alter table(:project_threads) do
      remove :handle
    end
  end
end
