defmodule Longx.Repo.Migrations.Credentials do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:credentials, primary_key: false) do
      add :encrypted_client_secret, :binary
      add :encrypted_refresh_token, :binary
      add :encrypted_access_token, :binary
      add :encrypted_secret, :binary
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_error_at, :utc_datetime_usec
      add :last_error, :text
      add :refreshed_at, :utc_datetime_usec
      add :expires_at, :utc_datetime_usec
      add :extra_params, :map, null: false, default: %{}
      add :pkce, :boolean, null: false
      add :scopes, :text
      add :registration_url, :text
      add :token_url, :text
      add :authorize_url, :text
      add :client_id, :text
      add :allowed_hosts, {:array, :text}, null: false, default: []
      add :scheme, :text, null: false
      add :header, :text, null: false
      add :kind, :text, null: false
      add :label, :text
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:credentials, [:name], name: "credentials_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:credentials, [:name], name: "credentials_unique_name_index")

    drop table(:credentials)
  end
end
