defmodule Longx.Repo.Migrations.ModelSettingsAndProviderLimits do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ai_providers) do
      add :request_timeout_ms, :bigint, null: false, default: 600_000
      add :max_concurrent_requests, :bigint
      add :last_checked_at, :utc_datetime_usec
      add :last_error, :text
      add :last_error_at, :utc_datetime_usec
    end

    alter table(:ai_models) do
      add :reasoning_effort, :text
      add :reasoning_summary, :text
      add :max_output_tokens, :bigint
    end
  end

  def down do
    alter table(:ai_models) do
      remove :max_output_tokens
      remove :reasoning_summary
      remove :reasoning_effort
    end

    alter table(:ai_providers) do
      remove :last_error_at
      remove :last_error
      remove :last_checked_at
      remove :max_concurrent_requests
      remove :request_timeout_ms
    end
  end
end
