defmodule Longx.Repo.Migrations.FillInProjectThreadsAndTurns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:project_turns) do
      add :user_text, :text
      add :model_slug, :text
      add :status, :text, null: false
      add :started_at, :utc_datetime_usec, null: false
      add :completed_at, :utc_datetime_usec
      add :commit_before, :text
      add :commit_after, :text
      add :dirty_start, :boolean, null: false
      add :diff, :text
      add :error, :text
    end

    alter table(:project_threads) do
      add :title, :text
      add :preview, :text
      add :cwd, :text, null: false
      add :model_slug, :text
      add :approval_policy, :text, null: false
      add :sandbox, :text, null: false
      add :tools, {:array, :text}, null: false, default: []
      add :status, :text, null: false
      add :last_activity_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:project_threads) do
      remove :last_activity_at
      remove :status
      remove :tools
      remove :sandbox
      remove :approval_policy
      remove :model_slug
      remove :cwd
      remove :preview
      remove :title
    end

    alter table(:project_turns) do
      remove :error
      remove :diff
      remove :dirty_start
      remove :commit_after
      remove :commit_before
      remove :completed_at
      remove :started_at
      remove :status
      remove :model_slug
      remove :user_text
    end
  end
end
