defmodule Longx.Repo.Migrations.MultiAgentAndSubagents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :multi_agent, :boolean, null: false, default: true
    end

    alter table(:project_threads) do
      add :multi_agent, :boolean, null: false, default: true
      add :agent_path, :text

      add :parent_thread_id,
          references(:project_threads,
            column: :id,
            name: "project_threads_parent_thread_id_fkey",
            type: :uuid
          )
    end
  end

  def down do
    alter table(:project_threads) do
      remove :parent_thread_id
      remove :agent_path
      remove :multi_agent
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `project_threads` table without the `project_threads_parent_thread_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    alter table(:projects) do
      remove :multi_agent
    end
  end
end
