defmodule Longx.Repo.Migrations.AddProviderKind do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ai_providers) do
      add :kind, :text, null: false, default: "openai_compatible"
    end
  end

  def down do
    alter table(:ai_providers) do
      remove :kind
    end
  end
end
