defmodule Longx.Repo.Migrations.AddProviderHostedWebSearch do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ai_providers) do
      add :supports_hosted_web_search, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:ai_providers) do
      remove :supports_hosted_web_search
    end
  end
end
