defmodule Longx.Repo.Migrations.AddWatches do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:watches, primary_key: false) do
      add :project_id,
          references(:projects, column: :id, name: "watches_project_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :webhook_token, :text
      add :load_error, :text
      add :disabled_reason, :text
      add :enabled, :boolean, null: false
      add :hour_started_at, :utc_datetime_usec
      add :sends_this_hour, :bigint, null: false
      add :sends, :bigint, null: false
      add :runs, :bigint, null: false
      add :last_sent_to, :text
      add :last_output, :text
      add :last_error, :text
      add :last_duration_ms, :bigint
      add :last_run_at, :utc_datetime_usec
      add :running_since, :utc_datetime_usec
      add :state, :map, null: false, default: %{}
      add :next_due_at, :utc_datetime_usec
      add :budget_per_hour, :bigint, null: false
      add :timeout_ms, :bigint, null: false
      add :max_runs, :bigint
      add :expires_at, :utc_datetime_usec
      add :at, :utc_datetime_usec
      add :cron, :text
      add :kind, :text, null: false
      add :layer, :text, null: false
      add :path, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:watches, [:project_id, :name],
             name: "watches_unique_name_in_project_index"
           )
  end

  def down do
    drop_if_exists unique_index(:watches, [:project_id, :name],
                     name: "watches_unique_name_in_project_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `watches` table without the `watches_project_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:watches)
  end
end
