defmodule Longx.Repo.Migrations.AddProviderStreamIdleTimeout do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ai_providers) do
      add :stream_idle_timeout_ms, :bigint, null: false, default: 300_000
    end
  end

  def down do
    alter table(:ai_providers) do
      remove :stream_idle_timeout_ms
    end
  end
end
