defmodule Longx.Repo.Migrations.AddProjectPassthroughPaths do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :passthrough_paths, {:array, :text}, null: false, default: []
    end
  end

  def down do
    alter table(:projects) do
      remove :passthrough_paths
    end
  end
end
