defmodule Longx.Repo.Migrations.AgentKernel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :engine, :text, null: false, default: "codex"
    end

    create table(:agent_items, primary_key: false) do
      add :inserted_at, :utc_datetime_usec, null: false
      add :model, :text
      add :ui, :map
      add :input, :map, null: false
      add :kind, :text, null: false
      add :seq, :bigint, null: false
      add :turn_id, :text
      add :thread_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:agent_items, ["thread_id", "seq"])
  end

  def down do
    drop_if_exists index(:agent_items, ["thread_id", "seq"],
                     name: "agent_items_thread_id_seq_index"
                   )

    drop table(:agent_items)

    alter table(:projects) do
      remove :engine
    end
  end
end
