defmodule Longx.Repo.Migrations.TrustLocalAgent do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :trust_local_agent, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:projects) do
      remove :trust_local_agent
    end
  end
end
