defmodule Longx.Repo.Migrations.AddTurnUsage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:project_turns) do
      add :usage, :map
    end
  end

  def down do
    alter table(:project_turns) do
      remove :usage
    end
  end
end
