defmodule Longx.Repo.Migrations.AddProviderCredential do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ai_providers) do
      add :credential_id, :uuid
    end
  end

  def down do
    alter table(:ai_providers) do
      remove :credential_id
    end
  end
end
