defmodule Longx.Repo.Migrations.AddSystemDevices do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:system_devices, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_seen_at, :utc_datetime_usec
      add :token_hash, :text, null: false
      add :platform, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:system_devices, [:token_hash],
             name: "system_devices_unique_token_hash_index"
           )
  end

  def down do
    drop_if_exists unique_index(:system_devices, [:token_hash],
                     name: "system_devices_unique_token_hash_index"
                   )

    drop table(:system_devices)
  end
end
