defmodule Longx.Repo.Migrations.AddCredentialDeviceFlow do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:credentials) do
      add :fixed_client, :boolean, null: false, default: false
      add :redirect_uri, :text
      add :authorize_params, :map, null: false, default: %{}
      add :device_flow, :text, null: false, default: "none"
    end
  end

  def down do
    alter table(:credentials) do
      remove :device_flow
      remove :authorize_params
      remove :redirect_uri
      remove :fixed_client
    end
  end
end
