defmodule Longx.Repo.Migrations.AddModelReasoningLevelLabels do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ai_models) do
      add :reasoning_level_labels, :map, null: false, default: %{}
    end
  end

  def down do
    alter table(:ai_models) do
      remove :reasoning_level_labels
    end
  end
end
