defmodule Longx.Repo.Migrations.AddWatchCreator do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:watches) do
      add :creator_thread_id, :uuid
    end
  end

  def down do
    alter table(:watches) do
      remove :creator_thread_id
    end
  end
end
