defmodule Longx.Repo.Migrations.AddChromeBrowsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:chrome_browsers, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :approved_at, :utc_datetime
      add :last_seen_at, :utc_datetime
      add :origins, :map, null: false, default: %{}
      add :max_tabs, :bigint, null: false
      add :token_hash, :text
      add :status, :text, null: false
      add :device, :map, null: false, default: %{}
      add :name, :text, null: false
      add :install_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:chrome_browsers, [:install_id],
             name: "chrome_browsers_unique_install_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:chrome_browsers, [:install_id],
                     name: "chrome_browsers_unique_install_id_index"
                   )

    drop table(:chrome_browsers)
  end
end
