defmodule Longx.Repo.Migrations.AddThreadMemoryExtractedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:project_threads) do
      add :memory_extracted_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:project_threads) do
      remove :memory_extracted_at
    end
  end
end
