defmodule Longx.Repo.Migrations.AddProviderPromptCacheKey do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ai_providers) do
      add :prompt_cache_key, :boolean
    end
  end

  def down do
    alter table(:ai_providers) do
      remove :prompt_cache_key
    end
  end
end
