defmodule Longx.Repo.Migrations.AddProjectGpuPassthrough do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :gpu_passthrough, :boolean, null: false, default: false
    end

    # rows that listed GPU nodes by hand (0.1.9–0.1.12's hint wrote them) become the
    # switch; the device entries leave the list, anything else there stays
    execute """
    UPDATE projects SET gpu_passthrough = 1
    WHERE passthrough_paths LIKE '%/dev/nvidia%' OR passthrough_paths LIKE '%/dev/dxg%'
    """

    execute """
    UPDATE projects SET passthrough_paths = COALESCE(
      (SELECT json_group_array(value) FROM json_each(projects.passthrough_paths)
       WHERE value NOT LIKE '/dev/nvidia%' AND value != '/dev/dxg' AND value != '/dev/dri'),
      '[]')
    WHERE gpu_passthrough = 1
    """
  end

  def down do
    alter table(:projects) do
      remove :gpu_passthrough
    end
  end
end
