defmodule Longx.Repo.Migrations.AddModelVerbosity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ai_models) do
      add :verbosity, :text
    end
  end

  def down do
    alter table(:ai_models) do
      remove :verbosity
    end
  end
end
