defmodule Longx.Repo.Migrations.AddProjects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:projects, primary_key: false) do
      add :model_id,
          references(:ai_models, column: :id, name: "projects_model_id_fkey", type: :uuid)

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :archived_at, :utc_datetime_usec
      add :dirty_start, :text, null: false
      add :tools, {:array, :text}, null: false, default: []
      add :sandbox, :text, null: false
      add :approval_policy, :text, null: false
      add :root_path, :text, null: false
      add :description, :text
      add :slug, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:projects, [:root_path], name: "projects_unique_root_path_index")

    create unique_index(:projects, [:slug], name: "projects_unique_slug_index")

    create table(:project_turns, primary_key: false) do
      add :thread_id,
          references(:project_threads,
            column: :id,
            name: "project_turns_thread_id_fkey",
            type: :uuid
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :codex_turn_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:project_threads, primary_key: false) do
      add :project_id,
          references(:projects,
            column: :id,
            name: "project_threads_project_id_fkey",
            type: :uuid
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :codex_thread_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:project_turns, [:codex_turn_id],
             name: "project_turns_unique_codex_turn_id_index"
           )

    create unique_index(:project_threads, [:codex_thread_id],
             name: "project_threads_unique_codex_thread_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:project_threads, [:codex_thread_id],
                     name: "project_threads_unique_codex_thread_id_index"
                   )

    drop_if_exists unique_index(:project_turns, [:codex_turn_id],
                     name: "project_turns_unique_codex_turn_id_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `project_threads` table without the `project_threads_project_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:project_threads)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `project_turns` table without the `project_turns_thread_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:project_turns)

    drop_if_exists unique_index(:projects, [:slug], name: "projects_unique_slug_index")

    drop_if_exists unique_index(:projects, [:root_path], name: "projects_unique_root_path_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `projects` table without the `projects_model_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:projects)
  end
end
