defmodule Longx.Repo.Migrations.AddThreadOnDuty do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:project_threads) do
      add :on_duty, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:project_threads) do
      remove :on_duty
    end
  end
end
