defmodule Longx.Repo.Migrations.AddModelReasoningLevels do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ai_models) do
      add :reasoning_levels, {:array, :text}, null: false, default: []
    end
  end

  def down do
    alter table(:ai_models) do
      remove :reasoning_levels
    end
  end
end
