defmodule Longx.Repo.Migrations.AddThreadTurnReasoningEffort do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:project_turns) do
      add :reasoning_effort, :text
    end

    alter table(:project_threads) do
      add :reasoning_effort, :text
    end
  end

  def down do
    alter table(:project_threads) do
      remove :reasoning_effort
    end

    alter table(:project_turns) do
      remove :reasoning_effort
    end
  end
end
