defmodule Longx.Repo.Migrations.AddAutoReview do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :auto_review, :boolean, null: false, default: true
    end

    alter table(:project_threads) do
      add :auto_review, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:project_threads) do
      remove :auto_review
    end

    alter table(:projects) do
      remove :auto_review
    end
  end
end
