defmodule Longx.Repo.Migrations.AddAiSearchProviders do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ai_search_providers, primary_key: false) do
      add :encrypted_api_key, :binary
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :default, :boolean, null: false
      add :base_url, :text, null: false
      add :kind, :text, null: false
      add :slug, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:ai_search_providers, [:slug],
             name: "ai_search_providers_unique_slug_index"
           )
  end

  def down do
    drop_if_exists unique_index(:ai_search_providers, [:slug],
                     name: "ai_search_providers_unique_slug_index"
                   )

    drop table(:ai_search_providers)
  end
end
