defmodule Longx.Repo.Migrations.AddAiTools do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ai_tools, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :enabled, :boolean, null: false
      add :name, :text, null: false
      add :namespace, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:ai_tools, [:namespace, :name],
             name: "ai_tools_unique_qualified_name_index"
           )
  end

  def down do
    drop_if_exists unique_index(:ai_tools, [:namespace, :name],
                     name: "ai_tools_unique_qualified_name_index"
                   )

    drop table(:ai_tools)
  end
end
