defmodule Longx.Repo.Migrations.AddProjectWritableRoots do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :writable_roots, {:array, :text}, null: false, default: ["~/.cache"]
    end
  end

  def down do
    alter table(:projects) do
      remove :writable_roots
    end
  end
end
