defmodule Longx.Repo.Migrations.AddAiProvidersAndModels do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ai_providers, primary_key: false) do
      add :encrypted_api_key, :binary
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :base_url, :text, null: false
      add :slug, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:ai_providers, [:slug], name: "ai_providers_unique_slug_index")

    create table(:ai_models, primary_key: false) do
      add :provider_id,
          references(:ai_providers, column: :id, name: "ai_models_provider_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :default, :boolean, null: false
      add :context_window, :bigint, null: false
      add :upstream_id, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `ai_models` table without the `ai_models_provider_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:ai_models)

    drop_if_exists unique_index(:ai_providers, [:slug], name: "ai_providers_unique_slug_index")

    drop table(:ai_providers)
  end
end
