defmodule Longx.Repo.Migrations.WebSearchSwitch do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :web_search, :boolean, null: false, default: true
    end

    alter table(:project_threads) do
      add :web_search, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:project_threads) do
      remove :web_search
    end

    alter table(:projects) do
      remove :web_search
    end
  end
end
