defmodule Longx.Repo.Migrations.AddTurnRevertedAndThreadFork do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:project_threads) do
      add :forked_from_id,
          references(:project_threads,
            column: :id,
            name: "project_threads_forked_from_id_fkey",
            type: :uuid
          )
    end
  end

  def down do
    alter table(:project_threads) do
      remove :forked_from_id
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `project_threads` table without the `project_threads_forked_from_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."
  end
end
