defmodule Longx.Repo.Migrations.AddProjectGlobalMemory do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :global_memory, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:projects) do
      remove :global_memory
    end
  end
end
