defmodule Longx.Repo.Migrations.AddModelSlug do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ai_models) do
      add :slug, :text
    end

    create unique_index(:ai_models, [:slug], name: "ai_models_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:ai_models, [:slug], name: "ai_models_unique_slug_index")

    alter table(:ai_models) do
      remove :slug
    end
  end
end
