defmodule Longx.Repo.Migrations.AgentSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :agent_settings, :map
    end
  end

  def down do
    alter table(:projects) do
      remove :agent_settings
    end
  end
end
