defmodule Longx.Repo.Migrations.AddSystemSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:system_settings, primary_key: false) do
      add :encrypted_value, :binary
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :key, :text, null: false, primary_key: true
    end
  end

  def down do
    drop table(:system_settings)
  end
end
