defmodule Longx.Repo.Migrations.AddModelHostedWebSearch do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ai_models) do
      add :hosted_web_search, :boolean
    end
  end

  def down do
    alter table(:ai_models) do
      remove :hosted_web_search
    end
  end
end
