defmodule Longx.Repo.Migrations.AddModelImageGeneration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ai_models) do
      add :image_generation, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:ai_models) do
      remove :image_generation
    end
  end
end
