defmodule Longx.Repo.Migrations.AddProjectFileRules do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :file_rules, :map, null: false, default: %{}
    end
  end

  def down do
    alter table(:projects) do
      remove :file_rules
    end
  end
end
