defmodule Longx.Codex.Home do
  @moduledoc """
  Our own `CODEX_HOME` for the bundled app-server — never `~/.codex`.

  Codex keeps its config, sqlite state, logs and skills under `CODEX_HOME`.
  We point it at a directory we control and regenerate `config.toml` on every
  boot so codex has exactly one model provider — the Longx gateway — and one
  placeholder model, `longx`. Which real model that means is decided per
  request by `Longx.AI` (see `Longx.AI.Gateway`).

  With `requires_openai_auth = false` codex needs no ChatGPT/OpenAI login at
  all; the only credential it holds is the per-boot gateway token, passed in
  via the environment we hand to `Longx.Shim`.

  Location: `config :longx, Longx.Codex.Home, dir: …` (dev: `./data/codex_home`;
  prod: `$LONGX_DATA_DIR/codex_home`). Not a temp dir — codex refuses to set
  up its PATH helpers there.
  """

  alias Longx.AI.Gateway.Token

  @enforce_keys [:dir, :config_path, :env]
  defstruct [:dir, :config_path, :env]

  @type t :: %__MODULE__{dir: Path.t(), config_path: Path.t(), env: [{String.t(), String.t()}]}

  @provider_id "longx"
  @placeholder_model "longx"

  @doc "`http://127.0.0.1:<endpoint port>/ai/v1` — codex always runs on this host."
  @spec default_gateway_url() :: String.t()
  def default_gateway_url do
    port = LongxWeb.Endpoint.config(:http)[:port]
    "http://127.0.0.1:#{port}/ai/v1"
  end

  @default_tokio_worker_threads 4

  @doc "`config :longx, Longx.Codex.Home, tokio_worker_threads:` (default 4)."
  @spec tokio_worker_threads() :: pos_integer
  def tokio_worker_threads do
    Application.get_env(:longx, __MODULE__, [])
    |> Keyword.get(:tokio_worker_threads, @default_tokio_worker_threads)
  end

  @doc "Configured home directory."
  @spec default_dir() :: Path.t()
  def default_dir do
    Application.get_env(:longx, __MODULE__, [])
    |> Keyword.get(:dir, Path.expand("data/codex_home"))
  end

  @doc """
  Creates the home directory (if needed), (re)writes `config.toml`, and
  returns the paths plus the environment to spawn codex with.

  Options: `:dir` (default `default_dir/0`), `:gateway_url` (default
  `default_gateway_url/0`), `:web_search` — a `t:Longx.AI.web_search_mode/0`
  (default: `Longx.AI.web_search_mode/0`, i.e. whatever is configured).
  """
  @spec prepare(keyword) :: {:ok, t} | {:error, File.posix()}
  def prepare(opts \\ []) do
    dir = Keyword.get(opts, :dir, default_dir()) |> Path.expand()
    gateway_url = Keyword.get(opts, :gateway_url, default_gateway_url())
    web_search = Keyword.get_lazy(opts, :web_search, &Longx.AI.web_search_mode/0)
    config_path = Path.join(dir, "config.toml")

    with :ok <- File.mkdir_p(dir),
         :ok <- File.write(config_path, config_toml(gateway_url, web_search)) do
      {:ok,
       %__MODULE__{
         dir: dir,
         config_path: config_path,
         env: [
           {"CODEX_HOME", dir},
           {Token.env_var(), Token.current()},
           # tokio honours this; codex's musl build contends on its allocator
           # with one worker per core on big machines (openai/codex#43170)
           {"TOKIO_WORKER_THREADS", Integer.to_string(tokio_worker_threads())}
         ]
       }}
    end
  end

  @doc "The `config.toml` codex boots with."
  @spec config_toml(String.t(), Longx.AI.web_search_mode()) :: String.t()
  def config_toml(gateway_url, web_search \\ :disabled) do
    [
      """
      # Generated by Longx (Longx.Codex.Home) on every boot — do not edit.
      # Codex talks only to the Longx AI gateway; the real model and API key
      # are configured in Longx, never here.

      model_provider = "#{@provider_id}"
      model = "#{@placeholder_model}"
      """,
      web_search_toml(web_search),
      """

      [model_providers.#{@provider_id}]
      name = "Longx Gateway"
      base_url = "#{gateway_url}"
      env_key = "#{Token.env_var()}"
      wire_api = "responses"
      requires_openai_auth = false
      stream_idle_timeout_ms = 600000
      # capability only: whether web.run is offered is the per-thread
      # `features.standalone_web_search` override (Longx.Codex.Thread)
      supports_standalone_web_search = true
      """
    ]
    |> IO.iodata_to_binary()
  end

  # :hosted   → the upstream's built-in web_search tool, live web access
  # :standalone → codex's web.run tool, executed by our /alpha/search
  # :disabled → no search tool at all
  defp web_search_toml(:hosted), do: ~s(web_search = "live"\n)
  defp web_search_toml(:standalone), do: "\n[features]\nstandalone_web_search = true\n"
  defp web_search_toml(:disabled), do: ~s(web_search = "disabled"\n)
end
