// All of the app's copy, zh-CN — one place, like the web's ui/strings.ts.
export const t = {
  appName: "Longx",
  pair: {
    title: "连接 Longx",
    hint: "在电脑上打开 Longx → 设置 → 移动端，把那里的地址和配对码填到这里。",
    server: "服务器地址",
    serverPlaceholder: "192.168.2.70:7788",
    code: "配对码",
    codePlaceholder: "6 位数字",
    device: "这台手机的名字",
    submit: "配对",
    working: "正在配对…",
    invalid: "这不是一个地址",
  },
  home: {
    running: "正在进行",
    waiting: "等待你",
    projects: "项目",
    noProjects: "还没有项目——在电脑上的 Longx 里新建一个。",
    settings: "设置",
    refresh: "刷新",
  },
  project: {
    threads: "会话",
    newThread: "新会话",
    noThreads: "还没有会话",
    files: "文件",
    git: "Git",
    history: "历史",
    agents: "子 agent",
    status: {
      idle: "空闲",
      active: "进行中",
      disconnected: "已断开",
      unrecoverable: "无法恢复",
      archived: "已归档",
    } as Record<string, string>,
  },
  thread: {
    welcome: "让 agent 在这个项目里干活",
    welcomeHint: "描述要做的事；命令、改动和审批都会显示在这里。",
    placeholder: "随心输入",
    running: "进行中",
    awaitingApproval: "等待审批",
    disabled: (reason: string) => (reason === "archived" ? "已归档的会话不能再发消息" : "codex 已不认识这个会话，不能再发消息"),
    tools: "工具",
    model: "模型",
    reasoning: "思考",
    defaultModel: "默认",
    mode: "访问模式",
    sandbox: "沙箱",
    approval: "审批",
    network: "联网",
    webSearch: "网页搜索",
    multiAgent: "子 agent",
    autoReview: "自动审核",
    newChatOnly: "新会话生效",
    sandboxOptions: { read_only: "只读", workspace_write: "可写工作区", danger_full_access: "完全访问（危险）" } as Record<string, string>,
    approvalOptions: { on_request: "按需询问", auto_accept: "全部放行", untrusted: "每条命令都问", never: "从不询问（申请一律拒绝）" } as Record<string, string>,
    ran: "运行了",
    running_: "运行中",
    declined: "已拒绝",
    failed: "失败",
    cancelled: "已取消",
    exit: (code: number) => `退出码 ${code}`,
    changed: "修改了文件",
    changing: "修改文件中",
    searched: "搜索了",
    searching: "搜索中",
    called: (name: string) => `调用了 ${name}`,
    calling: (name: string) => `调用 ${name}`,
    needsApproval: "需要你的批准",
    allowOnce: "本轮允许",
    allowSession: "本会话允许",
    deny: "拒绝",
    autoReviewRunning: "自动审核中…",
    autoReviewApproved: "自动审核通过",
    autoReviewDenied: "自动审核拒绝",
    stillAllow: "仍然允许",
    permissions: "申请权限",
    question: "agent 有问题问你",
    answer: "回答",
    subagent: (name: string) => `子 agent ${name}`,
    agentStates: { started: "运行中", interacted: "运行中", interrupted: "已中断", completed: "已完成" } as Record<string, string>,
    reasoningTitle: "思考过程",
    thinking: "思考中",
    output: "输出",
    stopped: "已停止",
    effortLevels: { none: "关闭", minimal: "最低", low: "低", medium: "中", high: "高", xhigh: "极高", max: "最高", ultra: "超高" } as Record<string, string>,
    dirtyTitle: "工作区有未提交的改动",
    dirtyHint: "先提交一次再开始，还是不管它直接开始？",
    dirtyCommit: "先提交",
    dirtyIgnore: "直接开始",
    cancel: "取消",
  },
  files: {
    title: "文件",
    empty: "空目录",
    binary: "二进制文件",
    tooLarge: "文件太大，只显示了前面的部分",
    open: "打开",
  },
  git: {
    title: "Git",
    notRepo: "这个项目没有 git 仓库",
    branch: "分支",
    changes: "改动",
    clean: "工作区干净",
    commit: "提交",
    summary: "提交说明",
    committed: "已提交",
    log: "历史",
  },
  history: {
    title: "历史",
    empty: "还没有轮次",
    restore: "恢复到这里",
    restoreTitle: "把文件恢复到这一轮开始时？",
    restoreHint: "会先把当前未提交的改动做一次安全提交，再把文件回到那时的样子；历史不变。",
    restoreConfirm: "恢复",
    status: { in_progress: "进行中", completed: "完成", failed: "失败", interrupted: "已中断", reverted: "已撤回" } as Record<string, string>,
  },
  settings: {
    title: "设置",
    server: "服务器",
    device: "这台手机",
    version: (v: string) => `Longx ${v}`,
    unpair: "解除配对",
    unpairHint: "退出这台服务器；要再用得重新配对。",
    notifications: "后台通知",
    notificationsHint: "保持一条到服务器的连接，等待审批、任务完成时提醒你。",
    appVersion: (v: string) => `app ${v}`,
    checkUpdate: "检查更新",
    checking: "正在检查…",
    upToDate: "已是最新版本",
    newVersion: (v: string) => `有新版本 ${v}`,
    update: "更新",
    later: "稍后",
    downloading: "正在下载…",
    theme: "外观",
  },
  common: {
    loading: "加载中…",
    retry: "重试",
    error: "出错了",
    ok: "好",
    cancel: "取消",
    back: "返回",
  },
};
